'use strict';

// 数据层独立于页面渲染；后续可将 commit/readState 替换成云端 API。
const STORAGE_KEY = 'paw-diary:v1';
const icons = {
  paw:'<ellipse cx="12" cy="16" rx="5.5" ry="4"/><ellipse cx="4.5" cy="9" rx="2" ry="2.8" transform="rotate(-20 4.5 9)"/><ellipse cx="9.5" cy="5.5" rx="2" ry="2.8"/><ellipse cx="15" cy="5.5" rx="2" ry="2.8"/><ellipse cx="20" cy="9" rx="2" ry="2.8" transform="rotate(20 20 9)"/>',
  home:'<path d="m3 10 9-7 9 7v10a1 1 0 0 1-1 1h-5v-7H9v7H4a1 1 0 0 1-1-1Z"/>',
  heart:'<path d="M20.8 4.8a5.5 5.5 0 0 0-7.8 0L12 6l-1-1.2a5.5 5.5 0 0 0-7.8 7.8L12 21l8.8-8.4a5.5 5.5 0 0 0 0-7.8Z"/><path d="M5 12h4l2-4 2 8 2-4h4"/>',
  pin:'<path d="M20 10c0 6-8 11-8 11S4 16 4 10a8 8 0 1 1 16 0Z"/><circle cx="12" cy="10" r="2.5"/>',
  community:'<circle cx="9" cy="7" r="3"/><path d="M3 21v-3a6 6 0 0 1 12 0v3M17 4a3 3 0 0 1 0 6m1 5a5 5 0 0 1 3 4v2"/>',
  leaf:'<path d="M20 3C7 2 2 7 4 14s10 7 13 1c2-4 2-8 3-12Z"/><path d="M4 21 15 9"/>',
  chevron:'<path d="m9 5 7 7-7 7"/>', down:'<path d="m6 9 6 6 6-6"/>', plus:'<path d="M12 5v14M5 12h14"/>', close:'<path d="m6 6 12 12M6 18 18 6"/>',
  weight:'<path d="M5 6h14l3 15H2Z"/><path d="M9 6V4a3 3 0 0 1 6 0v2M12 10v5m-3-3h6"/>',
  vaccine:'<path d="m14 3 7 7M16 1l7 7M4 17l3 3m-5 2 3-3m2-3 9-9 4 4-9 9H7v-4Zm5-6 3 3"/>',
  shield:'<path d="m12 3 8 3v6c0 5-8 9-8 9s-8-4-8-9V6Z"/><path d="m8 12 3 3 5-6"/>',
  calendar:'<rect x="3" y="5" width="18" height="16" rx="2"/><path d="M7 3v4M17 3v4M3 11h18m-13 4h2m4 0h2"/>',
  book:'<path d="M12 5C8 2 4 3 2 4v16c3-2 7-1 10 1 3-2 7-3 10-1V4c-2-1-6-2-10 1Zm0 0v16"/>',
  search:'<circle cx="10.5" cy="10.5" r="6.5"/><path d="m16 16 5 5"/>',
  like:'<path d="M20.8 4.8a5.5 5.5 0 0 0-7.8 0L12 6l-1-1.2a5.5 5.5 0 0 0-7.8 7.8L12 21l8.8-8.4a5.5 5.5 0 0 0 0-7.8Z"/>',
  comment:'<path d="M21 11.5A9 9 0 0 1 7 19l-5 2 2-5A9 9 0 1 1 21 11.5Z"/>',
  download:'<path d="M12 3v12m-5-5 5 5 5-5M4 17v4h16v-4"/>',
  camera:'<path d="M3 6h4l2-3h6l2 3h4v15H3Z"/><circle cx="12" cy="13" r="4"/>',
  check:'<path d="m5 12 4 4L19 6"/>', clock:'<circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/>'
};
const icon = name => `<svg class="icon" viewBox="0 0 24 24" aria-hidden="true">${icons[name] || icons.paw}</svg>`;
const esc = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const uid = () => globalThis.crypto?.randomUUID?.() || `id-${Date.now()}-${Math.random().toString(36).slice(2)}`;
const localDate = date => `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`;
const today = () => localDate(new Date());
const dayOffset = n => {const d=new Date(); d.setDate(d.getDate()+n); return localDate(d);};
const dayDiff = (a,b=today()) => Math.round((new Date(a+'T12:00:00')-new Date(b+'T12:00:00'))/86400000);
const shortDate = date => date ? `${Number(date.slice(5,7))}月${Number(date.slice(8,10))}日` : '未设置';
const types={weight:{label:'体重',icon:'weight'},vaccine:{label:'疫苗',icon:'vaccine'},deworm:{label:'驱虫',icon:'shield'},daily:{label:'日常',icon:'camera'}};
const cityOptions=['深圳','北京','上海','广州','杭州','成都'];
function seedState(){return {version:1,city:'深圳',activePet:'pet-mochi',pets:[{id:'pet-mochi',name:'糯米',type:'dog',breed:'金毛寻回犬',sex:'男孩子',birthday:dayOffset(-425),arrival:dayOffset(-365),image:'assets/dog.jpg'}],records:[
  {id:'w1',petId:'pet-mochi',type:'weight',date:dayOffset(-90),value:19.2,note:'第一次认真称重。'},
  {id:'w2',petId:'pet-mochi',type:'weight',date:dayOffset(-60),value:20.1,note:'饭吃得香，散步也很积极。'},
  {id:'w3',petId:'pet-mochi',type:'weight',date:dayOffset(-30),value:21.4,note:'记录每一次小小的变化。'},
  {id:'w4',petId:'pet-mochi',type:'weight',date:dayOffset(-1),value:22.5,note:'又长大了一点点，今天也好好吃饭啦。'},
  {id:'v1',petId:'pet-mochi',type:'vaccine',date:dayOffset(-350),title:'年度疫苗复查',note:'示例档案。下次时间以实际兽医安排为准。',nextDate:dayOffset(15)},
  {id:'d1',petId:'pet-mochi',type:'deworm',date:dayOffset(-25),title:'体外驱虫',note:'完成一次驱虫记录。',nextDate:dayOffset(5)},
  {id:'j1',petId:'pet-mochi',type:'daily',date:dayOffset(-3),title:'第一次去海边',note:'追着浪花跑了好久。回家的路上，累得睡着了。'}
],posts:[
  {id:'post1',author:'糯米的铲屎官',pet:'糯米',city:'深圳',topic:'遛宠搭子',title:'把周末交给草地和毛孩子',text:'今天的快乐是两只小狗给的。跑累了就一起躺在草地上，原来发呆也可以这么幸福。\n有人想一起解锁新的遛狗路线吗？',image:'assets/walk.jpg',avatar:'assets/dog.jpg',likes:28,liked:false,date:dayOffset(-1),comments:[{author:'豆豆妈妈',text:'一起！我们也很喜欢周末去草地玩。'}]},
  {id:'post2',author:'小橘的室友',pet:'小橘',city:'上海',topic:'今日萌宠',title:'今天的任务：在阳光下充满电',text:'认真观察了十分钟，结论是：猫咪真的很会享受生活。你家毛孩子最喜欢待在哪个角落？',image:'assets/cat.jpg',avatar:'assets/cat.jpg',likes:46,liked:false,date:dayOffset(-2),comments:[]},
  {id:'post3',author:'年糕同学',pet:'年糕',city:'深圳',topic:'养宠心得',title:'开始记体重以后，才看见小小的变化',text:'以前只觉得它长大了，现在把每次称重记下来，看着曲线一点点变化，陪伴好像有了形状。分享一个习惯：固定时间、用同一台秤，记录更好对比。',image:'',avatar:'assets/dog.jpg',likes:17,liked:false,date:dayOffset(-4),comments:[]}
]};}
function readState(){try{const s=JSON.parse(localStorage.getItem(STORAGE_KEY));if(s?.version===1&&Array.isArray(s.pets)&&s.pets.length&&Array.isArray(s.records)&&Array.isArray(s.posts))return s;}catch{}return seedState();}
let state=readState();
let page='home',healthFilter='all',nearbyFilter='all',communityFilter='all',postSearch='';
function commit(next){try{localStorage.setItem(STORAGE_KEY,JSON.stringify(next));state=next;return true;}catch{toast('保存失败：浏览器存储不可用或空间不足，请导出备份。');return false;}}
function update(mutator){const next=structuredClone(state);mutator(next);return commit(next);}
function pet(){return state.pets.find(p=>p.id===state.activePet)||state.pets[0];}
function petRecords(){return state.records.filter(r=>r.petId===pet().id).sort((a,b)=>b.date.localeCompare(a.date)||(b.createdAt||0)-(a.createdAt||0));}
function weights(){return petRecords().filter(r=>r.type==='weight').sort((a,b)=>a.date.localeCompare(b.date)||(a.createdAt||0)-(b.createdAt||0));}
function latestWeight(){return weights().at(-1)?.value;}
function recordTitle(r){return r.type==='weight'?`体重记录 · ${r.value} kg`:(r.title||types[r.type]?.label||'成长记录');}
function pending(){return petRecords().filter(r=>r.nextDate&&!r.reminderDone).sort((a,b)=>a.nextDate.localeCompare(b.nextDate));}
function ageText(p){const days=Math.max(0,-dayDiff(p.birthday));return `${Math.floor(days/365)}岁${Math.floor(days%365/30)}个月`;}
function empty(title,text,action=''){return `<div class="empty"><h3>${esc(title)}</h3><p>${esc(text)}</p>${action}</div>`;}
function button(label,action,kind='',ico='plus'){return `<button class="button ${kind}" data-action="${action}">${icon(ico)}${label}</button>`;}
function heading(title,subtitle,action=''){return `<div class="page-heading"><div><h1>${title}</h1><p>${subtitle}</p></div>${action}</div>`;}
function chartHTML(){const list=weights();if(!list.length)return empty('还没有体重记录','记录第一次体重，开始看见成长。');const visible=list.slice(-8),values=visible.map(r=>Number(r.value)),min=Math.max(0,Math.floor(Math.min(...values)-1)),max=Math.ceil(Math.max(...values)+1),range=max-min||1;
  const span=dayDiff(visible.at(-1).date,visible[0].date);
  const x=i=>visible.length===1?270:44+(span?dayDiff(visible[i].date,visible[0].date)/span:i/(visible.length-1))*440,y=v=>125-(v-min)/range*100;
  const points=visible.map((r,i)=>`${x(i)},${y(r.value)}`).join(' ');const ticks=[min,(min+max)/2,max];
  return `<div class="weight-summary"><strong>${values.at(-1)} <small>kg</small></strong><small>最近记录于 ${shortDate(visible.at(-1).date)}</small></div><svg class="chart" viewBox="0 0 520 150" role="img" aria-label="体重趋势，${visible.map(r=>`${r.date}：${r.value}千克`).join('，')}">${ticks.map(v=>`<line x1="42" y1="${y(v)}" x2="494" y2="${y(v)}" stroke="#e8ede4" stroke-dasharray="3 5"/><text x="3" y="${y(v)+4}">${v.toFixed(1)}</text>`).join('')}<polygon points="${x(0)},125 ${points} ${x(visible.length-1)},125" fill="#edf3e9"/><polyline points="${points}" fill="none" stroke="#43674b" stroke-width="2.5" stroke-linejoin="round"/>${visible.map((r,i)=>`<circle cx="${x(i)}" cy="${y(r.value)}" r="4" fill="#fff" stroke="#43674b" stroke-width="2"><title>${r.date} · ${r.value} kg</title></circle>`).join('')}</svg><div class="chart-label"><span>${shortDate(visible[0].date)}</span><span class="legend">体重 · kg</span><span>${shortDate(visible.at(-1).date)}</span></div>`;
}
function remindersHTML(){const list=pending();return list.length?list.slice(0,4).map(r=>{const days=dayDiff(r.nextDate);return `<div class="reminder"><span class="event-icon ${days<=7?'orange':''}">${icon(types[r.type]?.icon)}</span><div><h3>${esc(r.title)}</h3><p>${shortDate(r.nextDate)} · 手动设置</p></div><div class="due">${days<0?`已逾期 ${-days} 天`:days===0?'就是今天':`${days} 天后`}<button data-action="complete" data-id="${r.id}">记录完成</button></div></div>`;}).join(''):empty('健康事项已清空','添加疫苗或驱虫记录时，可以设置下一次日期。');}
function timelineHTML(limit=5){const list=petRecords().slice(0,limit);return list.length?`<ol class="timeline">${list.map(r=>`<li><span class="event-icon">${icon(types[r.type]?.icon)}</span><div class="timeline-content"><h3>${esc(recordTitle(r))}<time datetime="${r.date}">${shortDate(r.date)}</time></h3><p>${esc(r.note||'把今天的小小成长记下来。')}</p><span class="small-badge">${types[r.type]?.label||'日常'}</span></div></li>`).join('')}</ol>`:empty('时间线等你写下第一笔','健康记录和日常瞬间都会出现在这里。');}
function homeHTML(){const p=pet(),days=Math.max(0,-dayDiff(p.arrival)),count=petRecords().length;return heading('每一天，都是成长。',`和${esc(p.name)}一起，把平凡的日子变成珍贵的回忆。`,button('记一笔','record'))+`<div class="home-grid"><div class="home-left"><section class="pet-hero"><div class="hero-copy"><button class="pet-picker" data-action="switch-pet">${icon('paw')} 我的毛孩子 ${icon('down')}</button><h2>你好呀，${esc(p.name)}。</h2><p>我们已经一起度过<br><strong>${days}</strong> 个有你陪伴的日子。</p><div class="pet-tags"><span class="tag">${esc(p.breed|| (p.type==='cat'?'猫咪':'狗狗'))}</span><span class="tag">${ageText(p)}</span><span class="tag">${esc(p.sex)}</span></div><button class="text-button" data-action="edit-pet">查看宠物档案 ${icon('chevron')}</button></div><div class="hero-image"><img src="${p.image}" alt="${esc(p.name)}的宠物照片"><span class="hero-caption">一起长大，一直陪伴</span></div></section><div class="stats-strip"><div class="stat"><div class="stat-label">${icon('weight')} 最近体重</div><strong>${latestWeight()??'—'}<small>kg</small></strong><p>${weights().length?'已记录 '+weights().length+' 次':'等待第一次记录'}</p></div><div class="stat"><div class="stat-label">${icon('book')} 成长足迹</div><strong>${count}<small>条</small></strong><p>每一条都值得收藏</p></div><div class="stat"><div class="stat-label">${icon('calendar')} 待办事项</div><strong>${pending().length}<small>项</small></strong><p>${pending().length?'别忘了下一次照顾':'今天也安心陪伴'}</p></div></div><section class="panel"><div class="panel-title"><div><h2>体重的变化</h2><p>一点点变化，一点点长大</p></div><button class="text-button" data-action="record-weight">添加记录 ${icon('plus')}</button></div>${chartHTML()}</section><section class="panel"><div class="panel-title"><div><h2>我们的成长时间线</h2><p>健康、生活，以及那些第一次</p></div><a href="#health" class="text-button">全部足迹 ${icon('chevron')}</a></div>${timelineHTML()}</section></div><div class="home-right"><section class="panel"><div class="panel-title"><div><h2>接下来的小事</h2><p>照顾好它，也照顾好你的安心</p></div>${icon('calendar')}</div>${remindersHTML()}</section><section class="panel"><div class="panel-title"><div><h2>记录一个新瞬间</h2><p>不用等到特别的日子</p></div></div><p class="demo-note">称一次体重，记录一次护理，或者只是今天学会了一个新动作。</p><button class="button soft" data-action="record-daily" style="width:100%;margin-top:18px">${icon('camera')} 留住今天的小美好</button></section><section class="panel community-teaser"><img src="assets/walk.jpg" alt="两只狗狗一起在草地上玩耍"><div class="teaser-copy"><h3>快乐，也可以一起长大。</h3><p>发现同城宠友，找个一起散步的伙伴。</p><a href="#nearby" class="text-button">遇见附近的毛孩子 ${icon('chevron')}</a></div></section></div></div>`;}
function healthHTML(){const p=pet(),records=petRecords().filter(r=>healthFilter==='all'||r.type===healthFilter);return heading('照顾它的每一件小事。','把健康放在心上，把记录留在这里。',button('添加记录','record'))+`<div class="health-grid"><section class="panel"><div class="panel-title"><h2>宠物档案</h2><button class="text-button" data-action="edit-pet">编辑档案 ${icon('chevron')}</button></div><div class="pet-profile"><img src="${p.image}" alt="${esc(p.name)}"><div><h2>${esc(p.name)} <span class="small-badge">${ageText(p)}</span></h2><p>${esc(p.breed)} · ${esc(p.sex)}<br>生日 ${esc(p.birthday)} · ${p.type==='cat'?'猫咪':'狗狗'}</p><button class="text-button" data-action="switch-pet">管理我的宠物 ${icon('chevron')}</button></div></div></section><section class="panel"><div class="panel-title"><h2>健康待办</h2><small class="demo-note">日期由你设置</small></div>${remindersHTML()}</section><section class="panel"><div class="panel-title"><h2>体重趋势</h2><button class="text-button" data-action="record-weight">称重记录 ${icon('plus')}</button></div>${chartHTML()}</section><section class="panel"><div class="panel-title"><h2>成长足迹</h2></div>${timelineHTML(4)}</section><section class="panel full"><div class="panel-title"><h2>全部成长记录</h2><button class="text-button" data-action="export">${icon('download')} 导出备份</button></div><div class="tabs" style="margin-bottom:18px">${[['all','全部'],...Object.entries(types).map(([k,v])=>[k,v.label])].map(([k,v])=>`<button class="tab ${healthFilter===k?'active':''}" data-action="health-filter" data-value="${k}">${v}</button>`).join('')}</div>${records.length?`<div class="table-wrap"><table><thead><tr><th>日期</th><th>类型</th><th>记录内容</th><th>备注</th><th>操作</th></tr></thead><tbody>${records.map(r=>`<tr><td>${esc(r.date)}</td><td><span class="small-badge">${types[r.type]?.label}</span></td><td>${esc(recordTitle(r))}</td><td class="note-cell">${esc(r.note||'—')}</td><td><button class="delete-button" data-action="delete-record" data-id="${r.id}">删除</button></td></tr>`).join('')}</tbody></table></div>`:empty('这里还没有记录','点击“添加记录”，开始完善健康档案。')}</section></div>`;}
const friends=[
  {id:'f1',name:'豆豆',owner:'豆豆妈妈',type:'dog',breed:'金毛 · 男孩子',city:'深圳',area:'南山区',image:'assets/dog.jpg',desc:'喜欢草地和接飞盘，想找周末一起遛弯的伙伴。',tags:['周末遛弯','性格友好']},
  {id:'f2',name:'小橘',owner:'小橘的室友',type:'cat',breed:'橘猫 · 女孩子',city:'深圳',area:'福田区',image:'assets/cat.jpg',desc:'新手铲屎官，想交换猫咪日常护理和陪玩经验。',tags:['养猫交流','新手互助']},
  {id:'f3',name:'可乐与饼干',owner:'可乐家',type:'dog',breed:'多宠家庭',city:'深圳',area:'宝安区',image:'assets/walk.jpg',desc:'家里的快乐是双份！一起探索宠物友好的去处。',tags:['多宠家庭','户外散步']},
  {id:'f4',name:'栗子',owner:'栗子同学',type:'cat',breed:'家猫 · 男孩子',city:'上海',area:'徐汇区',image:'assets/cat.jpg',desc:'喜欢晒太阳，也喜欢分享生活里的小发现。',tags:['猫咪日常','摄影记录']},
  {id:'f5',name:'拿铁',owner:'拿铁的朋友',type:'dog',breed:'金毛 · 女孩子',city:'北京',area:'朝阳区',image:'assets/dog.jpg',desc:'每天出门散步，希望找到有相同作息的遛宠搭子。',tags:['日常遛弯','户外散步']},
  {id:'f6',name:'汤圆',owner:'汤圆一家',type:'dog',breed:'多宠家庭',city:'杭州',area:'西湖区',image:'assets/walk.jpg',desc:'喜欢探索绿地，欢迎一起分享周末的散步路线。',tags:['户外散步','路线分享']},
  {id:'f7',name:'芝麻',owner:'芝麻姐姐',type:'cat',breed:'家猫 · 女孩子',city:'广州',area:'天河区',image:'assets/cat.jpg',desc:'把养猫日常记录下来，想认识同城的铲屎官。',tags:['养猫交流','日常记录']},
  {id:'f8',name:'布丁',owner:'布丁爸爸',type:'dog',breed:'金毛 · 男孩子',city:'成都',area:'武侯区',image:'assets/dog.jpg',desc:'周末常在公园散步，爱分享宠物友好场所。',tags:['公园散步','城市探索']}
];
function nearbyHTML(){const list=friends.filter(f=>f.city===state.city&&(nearbyFilter==='all'||f.type===nearbyFilter));return heading('附近，刚好也有人爱它。','从一段散步开始，认识同城的毛孩子和它们的朋友。',button('切换城市','city','secondary','pin'))+`<div class="section-intro">${icon('pin')}<div>正在发现 ${esc(state.city)} 的宠友<small>按城市匹配的示例宠友 · 仅展示区级地域，不获取精确位置</small></div></div><div class="filter-bar"><div class="tabs">${[['all','全部宠友'],['dog','狗狗伙伴'],['cat','猫咪朋友']].map(([k,v])=>`<button class="tab ${nearbyFilter===k?'active':''}" data-action="nearby-filter" data-value="${k}">${v}</button>`).join('')}</div><small class="demo-note">${list.length} 位示例宠友</small></div><div class="nearby-grid">${list.length?list.map(f=>`<article class="friend-card"><div class="friend-image"><img src="${f.image}" alt="${esc(f.name)}的示例宠物照片" loading="lazy"><span class="tag">${esc(f.breed)}</span></div><div class="friend-body"><h3>${esc(f.name)}<small>${esc(f.city)} · ${esc(f.area)}</small></h3><p>${esc(f.desc)}</p><div class="friend-tags">${f.tags.map(t=>`<span>${esc(t)}</span>`).join('')}</div><button class="button soft" data-action="friend" data-id="${f.id}">${icon('community')} 认识一下</button></div></article>`).join(''):empty('这个筛选下暂时没有宠友','试试选择全部宠友，或者切换城市。',button('切换城市','city','secondary','pin'))}</div>`;}
function postHTML(post){return `<article class="post">${post.image?`<img class="post-image" src="${post.image}" alt="${esc(post.title)}" loading="lazy">`:''}<div class="post-content"><div class="post-user"><img class="post-avatar" src="${post.avatar}" alt=""><div><strong>${esc(post.author)}</strong><small>${esc(post.city)} · ${shortDate(post.date)}${post.own?' · 我的发布':' · 示例'}</small></div></div><h3>${esc(post.title)}</h3><p class="post-text">${esc(post.text)}</p><div class="post-topic"># ${esc(post.topic)}</div><div class="post-actions"><button class="${post.liked?'liked':''}" aria-label="${post.liked?'取消点赞':'点赞'} ${esc(post.title)}" aria-pressed="${!!post.liked}" data-action="like" data-id="${post.id}">${icon('like')} ${post.likes}</button><button data-action="comments" data-id="${post.id}">${icon('comment')} ${post.comments.length} 评论</button>${post.own?`<button data-action="delete-post" data-id="${post.id}">删除</button>`:''}</div></div></article>`;}
function communityHTML(){let list=state.posts.filter(p=>communityFilter==='all'||(communityFilter==='local'?p.city===state.city:p.topic===communityFilter));if(postSearch)list=list.filter(p=>(p.title+p.text+p.author+p.topic).toLowerCase().includes(postSearch.toLowerCase()));return heading('把毛茸茸的快乐，分享出去。','记录你的养宠日常，也收集别人的小小幸福。',button('发布日常','post','', 'camera'))+`<div class="filter-bar"><div class="tabs">${[['all','推荐日常'],['local',state.city+'同城'],['今日萌宠','今日萌宠'],['养宠心得','养宠心得']].map(([k,v])=>`<button class="tab ${communityFilter===k?'active':''}" data-action="community-filter" data-value="${k}">${esc(v)}</button>`).join('')}</div><label class="search">${icon('search')}<input id="post-search" aria-label="搜索社区内容" placeholder="搜索日常、经验或宠友" value="${esc(postSearch)}" maxlength="60"></label></div><div class="community-layout"><div class="feed">${list.length?list.map(postHTML).join(''):empty('这里暂时安静了一点','换个关键词，或者分享第一篇日常。',button('发布日常','post','','camera'))}</div><aside class="community-side"><section class="panel"><div class="panel-title"><h2>聊聊这些小事</h2></div>${['今日萌宠','遛宠搭子','养宠心得'].map(t=>`<button class="topic-item" style="width:100%;background:none;color:var(--green);text-align:left" data-action="community-filter" data-value="${t}"><span># ${t}</span><small>${state.posts.filter(p=>p.topic===t).length} 篇</small></button>`).join('')}</section><section class="panel demo-note"><h3>让社区温柔一点</h3><p>分享真实的陪伴，尊重不同的养宠方式。不公开住址和联系方式，遇到健康问题及时咨询兽医。</p></section><section class="panel demo-note"><h3>关于这个体验版</h3><p>这里预置了示例日常。你可以发布、点赞和评论，新增内容保存在当前浏览器。真实用户共享与交流将在后续版本接入。</p></section></aside></div>`;}
function render(){document.querySelector('#main').innerHTML=({home:homeHTML,health:healthHTML,nearby:nearbyHTML,community:communityHTML}[page])();document.querySelector('#main').classList.remove('page-enter');void document.querySelector('#main').offsetWidth;document.querySelector('#main').classList.add('page-enter');document.querySelector('#page-label').textContent=({home:'成长首页',health:'健康档案',nearby:'附近宠友',community:'社区日常'})[page];document.querySelector('#city-label').textContent=state.city;document.querySelectorAll('nav a').forEach(a=>{const active=a.dataset.page===page;a.classList.toggle('active',active);if(active)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current');});}
function route(){page=['home','health','nearby','community'].includes(location.hash.slice(1))?location.hash.slice(1):'home';render();window.scrollTo({top:0,behavior:'instant'});}
let toastTimer;
function toast(message){const el=document.querySelector('#toast');el.textContent=message;el.classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('visible'),3400);}
function modal(title,html){document.querySelector('#dialog-title').textContent=title;document.querySelector('#dialog-body').innerHTML=html;document.querySelector('#dialog').showModal();}
function closeModal(){document.querySelector('#dialog').close();}
function field(label,html,full=false){return `<label class="field ${full?'full':''}"><span>${label}</span>${html}</label>`;}
function formActions(label='保存记录'){return `<div class="form-actions"><button type="button" class="button secondary" data-action="close">取消</button><button type="submit" class="button">${icon('check')} ${label}</button></div>`;}
function recordModal(type='weight',reminder=null){modal('记下这一次成长',`<form id="record-form"><div class="form-grid">${field('记录类型',`<select name="type" id="record-type">${Object.entries(types).map(([k,v])=>`<option value="${k}" ${k===type?'selected':''}>${v.label}</option>`).join('')}</select>`)}${field('记录日期',`<input name="date" type="date" value="${today()}" max="${today()}" required>`)}<div id="type-fields" class="field full"></div>${field('备注 · 可选','<textarea name="note" maxlength="500" placeholder="今天发生了什么？留下一个小小的细节。"></textarea>',true)}</div><p class="form-tip">健康事项日期请按实际护理安排填写，必要时咨询兽医。</p>${formActions()}</form>`);function fill(){const t=document.querySelector('#record-type').value;document.querySelector('#type-fields').innerHTML=t==='weight'?`<label class="field"><span>体重（kg）</span><input name="value" type="number" min="0.01" max="200" step="0.01" placeholder="例如：22.5" required></label>`:`<label class="field"><span>${t==='daily'?'给这个瞬间起个名字':'记录名称'}</span><input name="title" maxlength="60" placeholder="${t==='vaccine'?'例如：疫苗接种':t==='deworm'?'例如：体外驱虫':'例如：第一次去海边'}" value="${esc(reminder?.title||'')}" required></label>${t!=='daily'?`<label class="field" style="margin-top:15px"><span>下一次日期 · 可选</span><input name="nextDate" type="date" min="${dayOffset(1)}"><small>填写后会加入首页健康待办。</small></label>`:''}`;}
  fill();document.querySelector('#record-type').addEventListener('change',fill);document.querySelector('#record-form').addEventListener('submit',e=>{e.preventDefault();const data=new FormData(e.target),date=data.get('date'),t=data.get('type'),nextDate=data.get('nextDate');if(date>today())return toast('记录日期不能晚于今天。');if(nextDate&&nextDate<=date)return toast('下一次日期应晚于本次记录日期。');const r={id:uid(),createdAt:Date.now(),petId:pet().id,type:t,date,note:data.get('note').trim()};if(t==='weight')r.value=Number(data.get('value'));else{r.title=data.get('title').trim();if(!r.title)return toast('请给这条记录起个名字。');if(nextDate)r.nextDate=nextDate;}if(update(s=>{s.records.unshift(r);if(reminder){const old=s.records.find(x=>x.id===reminder.id);if(old)old.reminderDone=true;}})){closeModal();render();toast('已记下这次成长，时间线也更新了。');}});
}
function petModal(isNew=false){const p=isNew?{name:'',type:'dog',breed:'',sex:'男孩子',birthday:dayOffset(-365),arrival:today()}:pet();modal(isNew?'认识新的毛孩子':'宠物档案',`<form id="pet-form"><div class="form-grid">${field('宠物名字',`<input name="name" value="${esc(p.name)}" maxlength="20" required>`)}${field('宠物类型',`<select name="type"><option value="dog" ${p.type==='dog'?'selected':''}>狗狗</option><option value="cat" ${p.type==='cat'?'selected':''}>猫咪</option></select>`)}${field('品种 · 可选',`<input name="breed" value="${esc(p.breed)}" maxlength="30" placeholder="例如：金毛寻回犬">`)}${field('性别',`<select name="sex">${['男孩子','女孩子','暂不确定'].map(v=>`<option ${p.sex===v?'selected':''}>${v}</option>`).join('')}</select>`)}${field('生日',`<input name="birthday" type="date" value="${p.birthday}" max="${today()}" required>`)}${field('来到家的日期',`<input name="arrival" type="date" value="${p.arrival}" max="${today()}" required>`)}</div><p class="form-tip">日期暂不确定时，可先填写估计日期，后续随时修改。</p>${formActions('保存档案')}</form>`);document.querySelector('#pet-form').addEventListener('submit',e=>{e.preventDefault();const d=new FormData(e.target),name=d.get('name').trim();if(!name)return toast('请填写宠物名字。');if(d.get('birthday')>d.get('arrival'))return toast('生日不能晚于来到家的日期。');const updated={...p,name,type:d.get('type'),breed:d.get('breed').trim(),sex:d.get('sex'),birthday:d.get('birthday'),arrival:d.get('arrival'),image:d.get('type')==='cat'?'assets/cat.jpg':'assets/dog.jpg'};if(update(s=>{if(isNew){updated.id=uid();s.pets.push(updated);s.activePet=updated.id;}else s.pets[s.pets.findIndex(x=>x.id===p.id)]=updated;})){closeModal();render();toast('宠物档案已保存。');}});}
function switchPet(){modal('我的毛孩子',state.pets.map(p=>`<button class="pet-option" data-action="select-pet" data-id="${p.id}"><img src="${p.image}" alt=""><span><strong>${esc(p.name)} ${p.id===pet().id?'· 正在记录':''}</strong><small>${esc(p.breed|| (p.type==='cat'?'猫咪':'狗狗'))} · ${ageText(p)}</small></span></button>`).join('')+button('添加一只宠物','new-pet','soft'));}
function cityModal(){modal('选择你的城市',`<form id="city-form">${field('所在城市',`<select name="city">${cityOptions.map(c=>`<option ${state.city===c?'selected':''}>${c}</option>`).join('')}</select>`)}<p class="form-tip">城市用于筛选同城示例宠友与日常，不获取精确位置。</p>${formActions('确认城市')}</form>`);document.querySelector('#city-form').addEventListener('submit',e=>{e.preventDefault();if(update(s=>s.city=new FormData(e.target).get('city'))){closeModal();render();toast(`已切换到${state.city}。`);}});}
async function compressPhoto(file){if(!file)return '';if(!file.type.startsWith('image/'))throw Error('请选择 JPG、PNG 或 WebP 图片。');if(file.size>10*1024*1024)throw Error('图片超过 10MB，请选择小一点的图片。');return new Promise((resolve,reject)=>{const img=new Image(),url=URL.createObjectURL(file);img.onload=()=>{try{const ratio=Math.min(1,1000/Math.max(img.width,img.height));const canvas=document.createElement('canvas');canvas.width=Math.round(img.width*ratio);canvas.height=Math.round(img.height*ratio);canvas.getContext('2d').drawImage(img,0,0,canvas.width,canvas.height);resolve(canvas.toDataURL('image/jpeg',.7));}catch{reject(Error('无法读取图片，请换一张试试。'));}finally{URL.revokeObjectURL(url);}};img.onerror=()=>{URL.revokeObjectURL(url);reject(Error('图片格式无法读取，请使用 JPG 或 PNG。'));};img.src=url;});}
function postModal(){modal('分享今天的毛茸茸',`<form id="post-form"><div class="form-grid">${field('标题','<input name="title" maxlength="60" placeholder="给今天的小美好起个名字" required>',true)}${field('日常内容','<textarea name="text" maxlength="1500" placeholder="想和宠友分享什么？" required></textarea>',true)}${field('话题',`<select name="topic">${['今日萌宠','遛宠搭子','养宠心得'].map(t=>`<option>${t}</option>`).join('')}</select>`)}${field('城市',`<select name="city">${cityOptions.map(c=>`<option ${c===state.city?'selected':''}>${c}</option>`).join('')}</select>`)}${field('照片 · 可选','<input name="photo" type="file" accept="image/jpeg,image/png,image/webp"><small>支持 JPG / PNG / WebP，最大 10MB。</small>',true)}</div><p class="form-tip">体验版发布内容仅保存在当前浏览器，不会分享给其他访问者。</p>${formActions('发布日常')}</form>`);document.querySelector('#post-form').addEventListener('submit',async e=>{e.preventDefault();const data=new FormData(e.target),submit=e.target.querySelector('[type=submit]'),title=data.get('title').trim(),text=data.get('text').trim();if(!title||!text)return toast('请填写标题和日常内容。');submit.disabled=true;submit.textContent='正在保存…';try{const file=data.get('photo');const image=await compressPhoto(file?.size?file:null);const p={id:uid(),author:'我与'+pet().name,pet:pet().name,city:data.get('city'),topic:data.get('topic'),title,text,image,avatar:pet().image,likes:0,liked:false,date:today(),comments:[],own:true};if(update(s=>s.posts.unshift(p))){closeModal();communityFilter='all';postSearch='';location.hash='community';render();toast('日常已发布，留下一个新的小美好。');}}catch(err){toast(err.message);}finally{submit.disabled=false;submit.innerHTML=icon('check')+' 发布日常';}});}
function commentsModal(id){const p=state.posts.find(p=>p.id===id);if(!p)return;modal('聊聊这篇日常',`<div class="comments">${p.comments.length?p.comments.map(c=>`<div class="comment"><strong>${esc(c.author)}</strong><p>${esc(c.text)}</p></div>`).join(''):'<p class="demo-note">还没有评论，留下第一句友好的回应吧。</p>'}</div><form id="comment-form">${field('我的评论','<textarea name="comment" maxlength="400" placeholder="分享你的想法…" required></textarea>')}<p class="form-tip">评论仅保存在当前浏览器。</p>${formActions('发送评论')}</form>`);document.querySelector('#comment-form').addEventListener('submit',e=>{e.preventDefault();const text=new FormData(e.target).get('comment').trim();if(!text)return toast('请填写评论内容。');if(update(s=>s.posts.find(p=>p.id===id).comments.push({author:'我',text}))){closeModal();render();toast('评论已保存。');}});}
function friendModal(id){const f=friends.find(f=>f.id===id);if(!f)return;modal(`认识${f.name}`,`<div class="pet-profile"><img src="${f.image}" alt="${esc(f.name)}"><div><h3>${esc(f.owner)}</h3><p>${esc(f.city)} · ${esc(f.area)}<br>${esc(f.breed)}</p></div></div><p class="profile-details" style="margin-top:20px">${esc(f.desc)}</p><p class="form-tip">这是示例宠友，暂不提供真实私信。你可以发布同城日常，演示寻找伙伴的流程。</p><div class="form-actions"><button class="button secondary" data-action="close">返回</button><button class="button" data-action="invite-post">${icon('camera')} 写一篇找搭子的日常</button></div>`);}
function confirmDelete(kind,id){modal('删除这条记录？',`<p class="demo-note">删除后无法恢复。如果想保留，可以先在健康档案中导出备份。</p><div class="form-actions"><button class="button secondary" data-action="close">保留</button><button class="button" id="confirm-delete">确认删除</button></div>`);document.querySelector('#confirm-delete').addEventListener('click',()=>{if(update(s=>{if(kind==='record')s.records=s.records.filter(r=>r.id!==id);else s.posts=s.posts.filter(p=>p.id!==id);})){closeModal();render();toast('已删除。');}});}
function exportData(){const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`爪爪日记-备份-${today()}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('备份已导出，包含宠物、健康记录与社区内容。');}
document.querySelectorAll('[data-icon]').forEach(el=>el.innerHTML=icon(el.dataset.icon));
document.addEventListener('click',e=>{const el=e.target.closest('[data-action]');if(!el)return;const a=el.dataset.action,id=el.dataset.id,v=el.dataset.value;switch(a){
  case 'record':recordModal();break;case 'record-weight':recordModal('weight');break;case 'record-daily':recordModal('daily');break;case 'edit-pet':petModal();break;case 'switch-pet':switchPet();break;case 'new-pet':closeModal();petModal(true);break;
  case 'select-pet':if(update(s=>s.activePet=id)){closeModal();render();toast(`开始记录${pet().name}的成长。`);}break;
  case 'complete':{const r=state.records.find(x=>x.id===id);if(r)recordModal(r.type,r);break;}
  case 'city':cityModal();break;case 'post':postModal();break;case 'invite-post':closeModal();postModal();break;case 'friend':friendModal(id);break;
  case 'health-filter':healthFilter=v;render();break;case 'nearby-filter':nearbyFilter=v;render();break;case 'community-filter':communityFilter=v;render();break;
  case 'like':if(update(s=>{const p=s.posts.find(p=>p.id===id);p.liked=!p.liked;p.likes+=p.liked?1:-1;}))render();break;
  case 'comments':commentsModal(id);break;case 'delete-record':confirmDelete('record',id);break;case 'delete-post':confirmDelete('post',id);break;case 'export':exportData();break;case 'close':closeModal();break;
}});
document.addEventListener('input',e=>{if(e.target.id==='post-search'){postSearch=e.target.value;const cursor=e.target.selectionStart;render();const input=document.querySelector('#post-search');input.focus();input.setSelectionRange(cursor,cursor);}});
document.querySelector('#city-button').addEventListener('click',cityModal);
document.querySelector('#close-dialog').addEventListener('click',closeModal);
document.querySelector('#dialog').addEventListener('click',e=>{if(e.target===e.currentTarget){const r=e.currentTarget.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)closeModal();}});
document.querySelector('#about-button').addEventListener('click',()=>modal('属于你们的成长手账','<div class="profile-details"><p><strong>爪爪日记</strong> · 养宠成长记录与社区</p><p>记录体重、疫苗、驱虫和日常；整理成长时间线；探索同城宠友。</p><p>当前是前端交互体验版，数据保存在当前浏览器。社区和附近宠友预置的是示例，暂不支持跨设备同步、真实私信或多人共享。</p></div><div class="form-actions">'+button('导出我的数据','export','secondary','download')+'<button class="button" data-action="close">继续记录</button></div>'));
window.addEventListener('hashchange',route);route();
