export const COMMUNITY_TOPICS=Object.freeze(['今日萌宠','遛宠搭子','养宠心得']);
const fail=()=>{throw Object.assign(new Error('Invalid community input'),{code:'INVALID_INPUT'});};
export function communityId(value){if(typeof value!=='string'||!/^[A-Za-z0-9_-]{1,128}$/.test(value))fail();return value;}
const optionalId=value=>value===undefined||value===null||value===''?null:communityId(value);
export function onlyFields(input,fields){if(!input||typeof input!=='object'||Array.isArray(input)||Object.keys(input).some(k=>!fields.includes(k)))fail();}
export function boundedText(value,max,{optional=false}={}){if(typeof value!=='string'||value.trim().length>max||(!optional&&!value.trim())||/[\x00-\x08\x0b\x0c\x0e-\x1f\x7f]/.test(value))fail();return value.trim();}
export function validatePostInput(input){onlyFields(input,['id','title','text','topic','cityId','districtId','imageAssetId']);if(!COMMUNITY_TOPICS.includes(input.topic))fail();const result={title:boundedText(input.title,60),text:boundedText(input.text,1500),topic:input.topic,cityId:optionalId(input.cityId),districtId:optionalId(input.districtId),imageAssetId:optionalId(input.imageAssetId)};if(result.districtId&&!result.cityId)fail();if(input.id!==undefined)result.id=communityId(input.id);return result;}
export function validateListInput(input){onlyFields(input,['scope','cityId','districtId','topic','query','authorId','cursor','limit']);const scope=input.scope??'all';if(!['all','city'].includes(scope))fail();const result={scope};if(scope==='city'){result.cityId=communityId(input.cityId);if(input.districtId)result.districtId=communityId(input.districtId);}if(input.topic!==undefined&&input.topic!==''){if(!COMMUNITY_TOPICS.includes(input.topic))fail();result.topic=input.topic;}if(input.query!==undefined){result.query=boundedText(input.query,80,{optional:true});}if(input.authorId!==undefined)result.authorId=communityId(input.authorId);if(input.limit!==undefined){if(!Number.isInteger(input.limit)||input.limit<1||input.limit>50)fail();result.limit=input.limit;}if(input.cursor!==undefined)result.cursor=input.cursor;return result;}
export function validateCommentInput(input){onlyFields(input,['postId','text']);return{postId:communityId(input.postId),text:boundedText(input.text,400)};}
export function publicPost(post){return{id:post.id,authorId:post.authorId,title:post.title,text:post.text,topic:post.topic,cityId:post.cityId??null,cityName:post.cityName??null,districtId:post.districtId??null,districtName:post.districtName??null,imageAssetId:post.imageAssetId??null,likeCount:post.likeCount,commentCount:post.commentCount,revision:post.revision,createdAt:post.createdAt,updatedAt:post.updatedAt};}
export function publicComment(comment){return{id:comment.id,postId:comment.postId,authorId:comment.authorId,text:comment.text,createdAt:comment.createdAt};}
