import {toRecordInputs,validatePlanDraft} from '../domain/ai-drafts.js';
import {createAiContext} from '../ai/context.js';
import {stage3Text as t,escapeStage3 as esc,stage3Error,refreshStage3Copy} from '../ui/stage3-copy.js';
export function createDraftSession({repository,getSnapshot,request,getScope,purpose='record'}={}){
 let scope=null,baseRevision,operationId,today,parsedPurpose='record';
 const same=()=>!getScope||['repository','generation','petId','workspaceId','mode','ownerId'].every(k=>scope[k]===getScope()[k]);
 return {async parse(text,petId,uiLocale){
   scope=getScope?{...getScope()}:{};baseRevision=repository.getRevision?.();operationId=crypto.randomUUID();parsedPurpose=typeof purpose==='function'?purpose():purpose;
   const result=await request('ai.records.parse',{text,petId,uiLocale,purpose:parsedPurpose,context:createAiContext(getSnapshot(),petId)});
   today=result.today??new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Shanghai'}).format(new Date());return result;
 },async confirm(drafts,selectedIds){
   if(!same())throw Object.assign(new Error('WORKSPACE_CHANGED'),{code:'WORKSPACE_CHANGED'});
   if(parsedPurpose==='plan'){
     if(!Array.isArray(selectedIds)||!selectedIds.length||selectedIds.length>5||new Set(selectedIds).size!==selectedIds.length)throw new Error('草稿选择无效');
     const checked=selectedIds.map(id=>{const d=validatePlanDraft(drafts.find(x=>x.draftId===id),{pets:getSnapshot().pets});if(d.missingFields.length)throw new Error('请补充计划草稿缺少的字段');return d;});
     const reminders=[];for(const d of checked){const {draftId,missingFields,sourceText,type,...input}=d;reminders.push(await repository.saveReminder({...input,recordType:type},{baseRevision:repository.getRevision?.(),operationId:operationId+':'+draftId}));}return {records:[],reminders};
   }
   const inputs=toRecordInputs(drafts,selectedIds,{pets:getSnapshot().pets,today});
   return repository.saveRecordBatch(inputs,{baseRevision,operationId});
 }};
}
export function createAiEntry({request,getRepository,getSnapshot,getScope,getLocale,openModal,onSaved,getTypeEntries=null,enhanceAll=null}={}){
 return {open({host=null,purpose='record',beforeSave=null}={}){
   if(!getScope().petId)return;
   const repo=getRepository(),draftSession=createDraftSession({repository:repo,getSnapshot,getScope,request,purpose});let drafts=[],busy=false,plan=false;
   const label=(key,input)=>`<label class="field"><span data-s3-key="${key}">${esc(t(key))}</span>${input}</label>`;
   const html=`<form id="ai-entry-form"><div class="record-mode-tabs"><button type="button" class="button secondary" data-action="record" data-s3-key="manual">${esc(t('manual'))}</button><span data-s3-key="ai">${esc(t('ai'))}</span></div><p class="demo-note" id="ai-current-pet">${esc(t('currentPet',{name:getSnapshot().pets.find(p=>p.id===getScope().petId)?.name??''}))}</p><p class="form-tip" data-s3-key="consent">${esc(t('consent'))}</p>${label('input',`<textarea id="ai-text" name="aiText" maxlength="1000" rows="4" required placeholder="${esc(t('example'))}"></textarea>`)}<p class="demo-note" id="ai-quota" role="status">${esc(t('quotaLoading'))}</p><button type="button" class="button" id="ai-parse" data-s3-key="parse">${esc(t('parse'))}</button><section id="ai-drafts" aria-live="polite"></section><p class="form-error" role="alert" hidden></p><div class="form-actions"><button type="button" class="button secondary" data-action="close" data-s3-key="cancel">${esc(t('cancel'))}</button><button type="submit" class="button" id="ai-confirm" data-s3-key="confirm" hidden>${esc(t('confirm'))}</button></div></form>`;
   if(host){host.innerHTML=html;host.querySelector('.record-mode-tabs')?.remove();}else if(!openModal(t('aiTitle'),html))return;
   const form=document.querySelector('#ai-entry-form'),parse=form.querySelector('#ai-parse'),error=form.querySelector('.form-error'),out=form.querySelector('#ai-drafts'),confirm=form.querySelector('#ai-confirm');
   form.__pawLocaleRefresh=()=>{refreshStage3Copy(form);for(const option of form.querySelectorAll('[name=type] option'))option.textContent=getTypeEntries?(getTypeEntries().find(e=>e.id===option.value)?.name??(getLocale()==='en'?'Choose a type':'请选择类型')):t(option.value);if(!host)document.querySelector('#dialog-title').textContent=t('aiTitle');form.querySelector('#ai-current-pet').textContent=t('currentPet',{name:getSnapshot().pets.find(p=>p.id===getScope().petId)?.name??''});};
   const current=()=>form.isConnected&&form.closest('dialog')?.open;
   const report=e=>{error.hidden=false;error.textContent=stage3Error(e);};
   request('ai.quota',{}).then(q=>{if(current())form.querySelector('#ai-quota').textContent=t('quota',{count:q.remaining??0});}).catch(e=>{if(current())form.querySelector('#ai-quota').textContent=stage3Error(e);});
   parse.addEventListener('click',async()=>{
     const text=form.querySelector('#ai-text').value.trim();if(!text){form.querySelector('#ai-text').focus();return;}if(busy)return;busy=true;parse.disabled=true;parse.textContent=t('loading');error.hidden=true;
     try{plan=(typeof purpose==='function'?purpose():purpose)==='plan';const result=await draftSession.parse(text,getScope().petId,getLocale());if(!current())return;drafts=result.drafts;form.querySelector('#ai-quota').textContent=t('quota',{count:result.quota?.remaining??0});
       out.innerHTML=`<h3 data-s3-key="drafts">${esc(t('drafts'))}</h3>`+drafts.map((d,i)=>`<fieldset class="ai-draft" data-draft-index="${i}"><legend><label><input type="checkbox" name="selected" value="${esc(d.draftId)}" checked> <span data-s3-key="select">${esc(t('select'))}</span></label></legend><p class="demo-note"><span data-s3-key="source">${esc(t('source'))}</span>：${esc(d.sourceText||text)}</p>${d.missingFields?.length?`<p class="form-tip" data-s3-key="missing">${esc(t('missing'))}</p>`:''}<div class="form-grid">${label('pet',`<select name="petId" required><option value="" data-s3-key="choosePet">${esc(t('choosePet'))}</option>${getSnapshot().pets.filter(p=>p.deletedAt===null).map(p=>`<option value="${esc(p.id)}" ${p.id===d.petId?'selected':''}>${esc(p.name)}</option>`).join('')}</select>`)}${label('type',`<select name="type">${['weight','vaccine','deworm','daily','other'].map(k=>`<option value="${k}" ${k===d.type?'selected':''}>${esc(t(k))}</option>`).join('')}</select>`)}${label('date',`<input type="date" name="occurredDate" value="${esc(d.occurredDate??'')}" required>`)}${label('value',`<input type="number" name="value" min="0.01" max="200" step="0.01" value="${d.value??''}">`)}${label('typeLabel',`<input name="typeLabel" maxlength="20" value="${esc(d.typeLabel??'')}">`)}${label('title',`<input name="title" maxlength="60" value="${esc(d.title??'')}" required>`)}${label('nextDate',`<input type="date" name="nextDate" value="${esc(d.nextDate??'')}">`)}${d.missingFields?.includes('nextDate')?`<label class="ai-reminder-choice"><input type="checkbox" name="skipNextDate"> <span data-s3-key="skipNextDate">${esc(t('skipNextDate'))}</span></label>`:''}${label('note',`<textarea name="note" maxlength="500">${esc(d.note??'')}</textarea>`)}</div></fieldset>`).join('');
       if(plan)for(const row of out.querySelectorAll('fieldset')){const d=drafts[Number(row.dataset.draftIndex)],date=row.querySelector('[name=occurredDate]');date.name='dueDate';date.value=d.dueDate??'';date.closest('label').querySelector('span').textContent=getLocale()==='en'?'Planned date':'计划日期';date.closest('label').querySelector('span').removeAttribute('data-s3-key');row.querySelector('[name=value]').closest('label').hidden=true;row.querySelector('[name=nextDate]').closest('label').hidden=true;}
       if(getTypeEntries)for(const row of out.querySelectorAll('fieldset')){const d=drafts[Number(row.dataset.draftIndex)],select=row.querySelector('[name=type]'),entries=getTypeEntries();select.innerHTML='<option value="">'+(getLocale()==='en'?'Choose a type':'请选择类型')+'</option>'+entries.map(e=>`<option value="${esc(e.id)}" data-icon="${esc(e.iconKey)}">${esc(e.name)}</option>`).join('');select.value=d.customTypeId??d.type;}
       confirm.hidden=false;parse.hidden=true;form.querySelector('#ai-text').readOnly=true;syncDraftFields();enhanceAll?.();
     }catch(e){if(current())report(e);}finally{busy=false;parse.disabled=false;parse.textContent=t('parse');if(drafts.length&&current())syncDraftFields();}
   });
   function syncDraftFields(){confirm.disabled=busy||!out.querySelector('[name=selected]:checked');for(const row of out.querySelectorAll('fieldset')){const checked=row.querySelector('[name=selected]').checked,value=row.querySelector('[name=type]').value,entry=getTypeEntries?.().find(e=>e.id===value),type=entry?.type??value;for(const field of row.querySelectorAll('input,select,textarea'))if(field.name!=='selected')field.disabled=!checked;row.querySelector('[name=value]').closest('label').hidden=plan||type!=='weight';row.querySelector('[name=value]').required=!plan&&checked&&type==='weight';row.querySelector('[name=typeLabel]').closest('label').hidden=!!getTypeEntries||type!=='other';row.querySelector('[name=typeLabel]').required=!getTypeEntries&&checked&&type==='other';const skip=row.querySelector('[name=skipNextDate]')?.checked??false;row.querySelector('[name=nextDate]').required=!plan&&checked&&drafts[Number(row.dataset.draftIndex)].missingFields?.includes('nextDate')&&!skip;row.querySelector('[name=nextDate]').disabled=plan||!checked||skip;}}
   out.addEventListener('change',syncDraftFields);
   form.addEventListener('submit',async event=>{event.preventDefault();if(busy||!drafts.length)return;busy=true;form.setAttribute('data-ai-saving','');for(const control of form.querySelectorAll('button,input,select,textarea'))control.disabled=true;confirm.textContent=t('saving');error.hidden=true;
     try{await beforeSave?.();const edited=drafts.map((d,i)=>{const row=out.querySelector(`[data-draft-index="${i}"]`),value=name=>row.querySelector(`[name=${name}]`)?.value??'';const entry=getTypeEntries?.().find(e=>e.id===value('type')),type=entry?.type??(getTypeEntries?null:value('type'));return {...d,petId:value('petId')||null,type,...(entry&&!entry.builtin?{customTypeId:entry.id,iconKey:entry.iconKey}:{}),typeLabel:type==='other'?(entry?.name??value('typeLabel')):undefined,...(plan?{dueDate:value('dueDate')||null}:{occurredDate:value('occurredDate')||null}),value:!plan&&type==='weight'?Number(value('value')):null,unit:!plan&&type==='weight'?'kg':null,title:value('title'),note:value('note'),nextDate:row.querySelector('[name=skipNextDate]')?.checked?null:value('nextDate')||null,missingFields:!plan&&d.missingFields?.includes('nextDate')?['nextDate']:[],skipNextDate:row.querySelector('[name=skipNextDate]')?.checked===true};});
       const selected=[...out.querySelectorAll('[name=selected]:checked')].map(el=>el.value);const result=await draftSession.confirm(edited,selected);if(current())await onSaved(result);
     }catch(e){if(current())report(e);}finally{busy=false;form.removeAttribute('data-ai-saving');if(current()){for(const control of form.querySelectorAll('button,input,select,textarea'))control.disabled=false;syncDraftFields();confirm.disabled=!out.querySelector('[name=selected]:checked');confirm.textContent=t('confirm');}}
   });if(!host){const title=document.querySelector('#dialog-title');if(title){title.tabIndex=-1;title.focus();}}
 }};
}
