import {COMMUNITY_TOPICS,validatePostInput,validateCommentInput} from '../domain/community.js';
import {createDraftHandoff} from './community-draft-handoff.js';
const failure=code=>Object.assign(new Error(code),{code});
const clone=value=>structuredClone(value);
const unique=items=>[...new Map(items.map(item=>[item.post?.id??item.comment?.id,item])).values()];
const sessionValue=session=>({userId:session?.userId??session?.principal?.userId??null,generation:session?.generation??0});
const same=(a,b)=>a.userId===b.userId&&a.generation===b.generation;
const initialPost=()=>({title:'',text:'',topic:'今日萌宠',cityId:null,districtId:null,imageAssetId:null});
const postFields=['id','title','text','topic','cityId','districtId','imageAssetId'];
// This fixed-environment app keeps exact references by owner across repository rotation.
// Never serialize them or issue cleanup under a different owner.
const imageReservations=new Map();
export function createCommunityController({repository,getSession=()=>({userId:null,generation:0}),uploadImage,onState=()=>{},idFactory=()=>crypto.randomUUID(),initialAuthorId}={}){
 if(typeof repository?.request!=='function')throw failure('UNAVAILABLE');
 let disposed=false,bound=sessionValue(getSession()),listTurn=0,detailTurn=0;
 let state={filters:{scope:'all',topic:'',query:'',...(initialAuthorId?{authorId:initialAuthorId}:{})},items:[],nextCursor:null,status:'idle',error:null,editor:null,detail:null};
 const likes=new Map(),confirmedLikes=new Map(),operations=new Map();
 const assets=imageReservations;
 const assetKey=(ownerId,assetId)=>ownerId+'\0'+assetId;
 const writing=()=>!!state.editor?.busy||!!state.detail?.busy;
 const requireIdle=()=>{if(writing())throw failure('BUSY');};
 function retireImage(editor){if(!editor?.uploadedAsset)return;const row=assets.get(assetKey(editor.scope.userId,editor.uploadedAsset));if(row)row.pending=true;editor.uploadedAsset=null;queueMicrotask(()=>controller.flushImageCleanup());}
 const notify=kind=>{if(!disposed)onState(getState(),kind);};
 function synchronize(){const next=sessionValue(getSession());if(!same(bound,next)){retireImage(state.editor);bound=next;listTurn++;detailTurn++;state={...state,items:[],nextCursor:null,status:'idle',error:null,editor:null,detail:null};likes.clear();confirmedLikes.clear();operations.clear();notify('identity');}}
 function getState(){return {...clone(state),cleanupPending:[...assets.values()].filter(a=>a.ownerId===bound.userId&&a.pending).map(a=>a.assetId)};}
 const scope=()=>{synchronize();return {...bound};};
 function valid(captured){if(disposed)throw failure('IDENTITY_CHANGED');if(!same(captured,sessionValue(getSession()))){synchronize();throw failure('IDENTITY_CHANGED');}}
 function signed(){const captured=scope();if(!captured.userId)throw failure('UNAUTHENTICATED');return captured;}
 const keyFor=(kind,payload)=>{const signature=JSON.stringify([kind,payload]),old=operations.get(kind);if(old?.signature===signature)return old.id;const id=idFactory();operations.set(kind,{signature,id});return id;};
 const locate=id=>state.items.find(v=>v.post.id===id)??(state.detail?.item?.post.id===id?state.detail.item:null);
 function applyItem(item){const f=state.filters,p=item.post,matches=(f.scope!=='city'||p.cityId===f.cityId&&(!f.districtId||p.districtId===f.districtId))&&(!f.topic||p.topic===f.topic)&&(!f.authorId||(p.authorId??item.identity.authorId)===f.authorId)&&(!f.query||(p.title+'\n'+p.text).toLowerCase().includes(f.query.toLowerCase()));const previous=state.items.findIndex(v=>v.post.id===p.id);if(!matches)state.items=state.items.filter(v=>v.post.id!==p.id);else if(previous>=0)state.items=state.items.map(v=>v.post.id===p.id?item:v);else state.items=[item,...state.items];if(state.detail?.item?.post.id===p.id)state.detail.item=item;}
 const controller={
  getState(){synchronize();return getState();},
  setFilters(next){scope();state.filters={...state.filters,...next};if(state.filters.scope==='all'){delete state.filters.cityId;delete state.filters.districtId;}state.items=[];state.nextCursor=null;state.error=null;listTurn++;notify('filters');},
  async setBrowseRegion(region={}){scope();if(state.filters.scope!=='city')return;this.setFilters({cityId:region.cityId??undefined,districtId:region.districtId??undefined});if(region.cityId)return this.load();},
  async load({more=false}={}){const captured=scope(),turn=++listTurn;if(more&&!state.nextCursor)return;const filters={...state.filters,limit:20};if(more)filters.cursor=state.nextCursor;state.status='loading';state.error=null;notify('list');try{const result=await repository.request('community.list',filters);valid(captured);if(turn!==listTurn)return;state.items=unique(more?[...state.items,...result.items]:result.items);state.nextCursor=result.nextCursor??null;state.status='ready';notify('list');}catch(error){if(turn!==listTurn)return;try{valid(captured);}catch(boundary){throw boundary;}state.status='error';state.error=error.code??'UNAVAILABLE';notify('list');throw error;}},
  openDraft(draft={}){const captured=scope();requireIdle();if(state.editor?.uploadedAsset!==draft.imageAssetId)retireImage(state.editor);const value={...initialPost(),...Object.fromEntries(Object.entries(draft).filter(([key])=>postFields.includes(key)))};const reservation=assets.get(assetKey(captured.userId,value.imageAssetId));state.editor={draft:value,baseRevision:draft.baseRevision??(draft.id?draft.revision??0:0),operationId:draft.operationId??null,file:draft.imageFile??null,uploadedAsset:reservation&&!reservation.pending?value.imageAssetId:null,dirty:!!value.title||!!value.text||!!draft.imageFile,busy:false,error:null,review:null,scope:captured};notify('editor-open');},
  editPost(item){if(!item?.isOwn)throw failure('FORBIDDEN');this.openDraft({...item.post,baseRevision:item.post.revision});state.editor.dirty=false;},
  setDraft(name,value){scope();const editor=state.editor;if(!editor||editor.busy||!postFields.includes(name))return;if(editor.draft[name]!==value){editor.draft[name]=value;editor.operationId=null;editor.review=null;editor.dirty=true;notify('draft-input');}},
  setImageFile(file){scope();const editor=state.editor;if(!editor||editor.busy)return;if(editor.uploadedAsset)editor.draft.imageAssetId=null;retireImage(editor);editor.file=file;editor.operationId=null;editor.dirty=true;notify('draft-file');},
  removeImage(){scope();const editor=state.editor;if(!editor||editor.busy)return;retireImage(editor);editor.file=null;editor.draft.imageAssetId=null;editor.operationId=null;editor.dirty=true;notify('draft-file');},
  getDraftHandoff(){scope();const editor=state.editor;if(editor){editor.operationId??=idFactory();return {...clone(editor.draft),operationId:editor.operationId,baseRevision:editor.baseRevision,...(editor.file?{imageFile:editor.file}:{})};}const detail=state.detail;if(detail?.item&&detail.commentText)return {kind:'comment',postId:detail.item.post.id,text:detail.commentText,operationId:detail.commentOperationId??=idFactory()};return null;},
  cancelDraft(){scope();const editor=state.editor;if(!editor||editor.busy)return false;retireImage(editor);state.editor=null;notify('editor-close');queueMicrotask(()=>controller.flushImageCleanup());return true;},
  async flushImageCleanup(){const captured=scope();if(disposed||!captured.userId)return;for(const row of assets.values()){if(!row.pending||row.ownerId!==captured.userId||row.busy)continue;if(disposed||!same(captured,sessionValue(getSession())))return;row.busy=true;try{const result=await repository.request('community.media.remove',{assetId:row.assetId},{operationId:row.operationId});if(result?.removed!==true)throw failure('UNAVAILABLE');valid(captured);assets.delete(assetKey(row.ownerId,row.assetId));}catch{ /* Keep the exact owner/reference/key for a later retry. */ }finally{row.busy=false;notify('cleanup');}}},
  async saveDraft(){const captured=signed();requireIdle();const editor=state.editor;if(!editor)throw failure('INVALID_INPUT');if(editor.busy)throw failure('BUSY');if(!same(editor.scope,captured))throw failure('IDENTITY_CHANGED');editor.busy=true;editor.error=null;notify('editor-saving');try{if(editor.file){if(!editor.uploadedAsset){if(!uploadImage)throw failure('UNAVAILABLE');const asset=await uploadImage(editor.file,'post');editor.uploadedAsset=asset.assetId??asset;const key=assetKey(captured.userId,editor.uploadedAsset);if(!assets.has(key))assets.set(key,{assetId:editor.uploadedAsset,ownerId:captured.userId,operationId:idFactory(),pending:false,busy:false});try{valid(captured);}catch(boundary){retireImage(editor);throw boundary;}}editor.draft.imageAssetId=editor.uploadedAsset;}const payload=validatePostInput(editor.draft);editor.operationId??=idFactory();const result=await repository.request('community.save',payload,{operationId:editor.operationId,baseRevision:editor.baseRevision});valid(captured);if(state.editor!==editor)throw failure('IDENTITY_CHANGED');applyItem(result);if(editor.uploadedAsset)assets.delete(assetKey(captured.userId,editor.uploadedAsset));state.editor=null;notify('editor-saved');return result;}catch(error){try{valid(captured);}catch(boundary){throw boundary;}editor.error=error.code??'UNAVAILABLE';notify('editor-error');throw error;}finally{editor.busy=false;notify('saving-end');}},
  async reviewLatestDraft(){const captured=signed(),editor=state.editor;if(!editor?.draft.id)throw failure('INVALID_INPUT');const result=await repository.request('community.get',{id:editor.draft.id});valid(captured);editor.review=result.post;notify('editor-review');return result.post;},
  acceptDraftRevision(){scope();const editor=state.editor;if(!editor?.review)throw failure('INVALID_INPUT');editor.baseRevision=editor.review.revision;editor.operationId=null;editor.error=null;editor.review=null;notify('editor-review');},
  async openPost(id){const captured=scope();requireIdle();const turn=++detailTurn,likeSequence=confirmedLikes.get(id)?.sequence??0;state.detail={id,item:null,comments:[],nextCursor:null,commentText:'',commentOperationId:null,busy:false,error:null,status:'loading'};notify('detail-open');try{const [item,comments]=await Promise.all([repository.request('community.get',{id}),repository.request('comments.list',{postId:id,limit:20})]);valid(captured);if(turn!==detailTurn)return;const confirmed=confirmedLikes.get(id);if(confirmed&&confirmed.sequence>likeSequence){item.liked=confirmed.liked;item.post.likeCount=confirmed.likeCount;}Object.assign(state.detail,{item,comments:comments.items,nextCursor:comments.nextCursor,status:'ready'});const feedItem=state.items.find(row=>row.post.id===item.post.id);if(feedItem){feedItem.liked=item.liked;feedItem.post.likeCount=item.post.likeCount;}notify('detail');notify('like');return item;}catch(error){valid(captured);if(turn!==detailTurn)return;state.detail.status='error';state.detail.error=error.code??'UNAVAILABLE';notify('detail');throw error;}},
  closePost(){scope();if(state.detail?.busy)return false;detailTurn++;state.detail=null;notify('detail-close');return true;},
  setCommentText(text){scope();if(state.detail&&!state.detail.busy){state.detail.commentText=text;state.detail.commentOperationId=null;notify('comment-input');}},
  restoreCommentOperation(operationId){if(state.detail)state.detail.commentOperationId=operationId;},
  async loadComments(){const captured=scope(),detail=state.detail;if(!detail?.nextCursor)return;try{const result=await repository.request('comments.list',{postId:detail.id,cursor:detail.nextCursor,limit:20});valid(captured);if(state.detail!==detail)return;detail.comments=unique([...detail.comments,...result.items]);detail.nextCursor=result.nextCursor;detail.error=null;notify('detail');}catch(error){valid(captured);if(state.detail!==detail)return;detail.error=error.code??'UNAVAILABLE';notify('detail');throw error;}},
  async saveComment(){const captured=signed();requireIdle();const detail=state.detail;if(!detail?.item)throw failure('INVALID_INPUT');if(detail.busy)throw failure('BUSY');detail.busy=true;detail.error=null;detail.commentOperationId??=idFactory();notify('comment-saving');try{const input=validateCommentInput({postId:detail.item.post.id,text:detail.commentText}),result=await repository.request('comments.save',input,{operationId:detail.commentOperationId});valid(captured);if(state.detail!==detail)throw failure('IDENTITY_CHANGED');detail.comments=unique([...detail.comments,result]);detail.commentText='';detail.commentOperationId=null;detail.item.post.commentCount++;notify('comment-saved');return result;}catch(error){valid(captured);detail.error=error.code??'UNAVAILABLE';notify('comment-error');throw error;}finally{detail.busy=false;notify('saving-end');}},
  getLikeState(postId){synchronize();const item=(state.detail?.item?.post.id===postId?state.detail.item:null)??locate(postId),entry=likes.get(postId),liked=item?.liked===true,count=item?.post.likeCount??0;return {liked:entry?.busy?entry.liked:liked,likeCount:entry?.busy?Math.max(0,count+Number(entry.liked)-Number(liked)):count,busy:entry?.busy===true,error:entry?.error??null};},
  async setLiked(postId,liked){const captured=signed();if(likes.get(postId)?.busy)throw failure('BUSY');const prior=likes.get(postId),entry=prior?.liked===liked?prior:{liked,operationId:idFactory()};entry.busy=true;entry.error=null;likes.set(postId,entry);notify('like');try{const result=await repository.request('likes.set',{postId,liked},{operationId:entry.operationId});valid(captured);confirmedLikes.set(postId,{sequence:(confirmedLikes.get(postId)?.sequence??0)+1,liked:result.liked,likeCount:result.likeCount});for(const item of [state.items.find(v=>v.post.id===postId),state.detail?.item?.post.id===postId?state.detail.item:null])if(item){item.liked=result.liked;item.post.likeCount=result.likeCount;}likes.delete(postId);notify('like');return result;}catch(error){valid(captured);if(likes.get(postId)===entry)entry.error=error.code??'UNAVAILABLE';throw error;}finally{entry.busy=false;if(!disposed&&same(captured,sessionValue(getSession())))notify('like');}},
  isLikeBusy:postId=>likes.get(postId)?.busy===true,
  async deletePost(id){const captured=signed();requireIdle();const item=locate(id);if(!item?.isOwn)throw failure('FORBIDDEN');const result=await repository.request('community.delete',{id},{operationId:keyFor('delete:'+id,{revision:item.post.revision}),baseRevision:item.post.revision});valid(captured);state.items=state.items.filter(v=>v.post.id!==id);if(state.detail?.id===id)this.closePost();notify('list');return result;},
  async deleteComment(id){const captured=signed();requireIdle();const detail=state.detail,comment=detail?.comments.find(v=>v.comment.id===id);if(!comment?.isOwn)throw failure('FORBIDDEN');const result=await repository.request('comments.delete',{id},{operationId:keyFor('delete-comment:'+id,{id})});valid(captured);if(state.detail===detail){detail.comments=detail.comments.filter(v=>v.comment.id!==id);detail.item.post.commentCount=Math.max(0,detail.item.post.commentCount-1);notify('detail');}return result;},
  async hidePost(postId){const captured=signed();requireIdle();const result=await repository.request('community.hide',{postId,hidden:true},{operationId:keyFor('hide:'+postId,{postId})});valid(captured);state.items=state.items.filter(v=>v.post.id!==postId);if(state.detail?.id===postId)this.closePost();notify('list');return result;},
  async reportPost(postId,reason,note=''){const captured=signed(),payload={postId,reason,note},result=await repository.request('community.report',payload,{operationId:keyFor('report:'+postId,payload)});valid(captured);return result;},
  hasUnsavedChanges:()=>!!state.editor?.dirty||!!state.detail?.commentText,
  isSaving:()=>!!state.editor?.busy||!!state.detail?.busy||[...likes.values()].some(v=>v.busy),
  destroy({preserveImages=false}={}){if(!preserveImages)retireImage(state.editor);disposed=true;listTurn++;detailTurn++;state.editor=null;state.detail=null;likes.clear();confirmedLikes.clear();operations.clear();},
 };
 queueMicrotask(()=>controller.flushImageCleanup());
 return controller;
}

const escape=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function mountCommunity({container,repository,getSession=()=>({userId:null,generation:0}),getLocale=()=> 'zh-CN',onLocaleChange,onLogin,onProfile,onViewAuthorPosts,uploadImage,resolveImage,mountRegionPicker,onError,onChanged=()=>{},initialAuthorId,initialDraft,getBrowseRegion=()=>({}),onBrowseRegion,draftHandoff=createDraftHandoff()}={}){
 if(!container)throw failure('INVALID_INPUT');const doc=container.ownerDocument;
 const en=()=>getLocale()==='en',t=(zh,english)=>en()?english:zh;
 const topicText=topic=>en()?({'今日萌宠':'Daily pets','遛宠搭子':'Walking partners','养宠心得':'Pet care tips'}[topic]??topic):topic;
 const errorText=code=>({UNAUTHENTICATED:t('请先登录，输入已保留。','Sign in to continue. Your input is kept.'),PROFILE_REQUIRED:t('先设置公开昵称，再返回同一篇草稿。','Choose your public nickname, then return to this draft.'),CONFLICT:t('这篇内容已有更新。请核对最新版本，输入已保留。','This post has changed. Review the latest version; your input is kept.'),INVALID_INPUT:t('请检查标题、正文和所选地区。','Check the title, text and selected region.'),NOT_FOUND:t('这篇内容已移除或暂时不可见。','This post has been removed or is unavailable.'),UNAVAILABLE:t('暂时无法完成，请重试。输入已保留。','Could not complete this action. Retry; your input is kept.'),TIMEOUT:t('等待超时，请重试。输入已保留。','The request timed out. Retry; your input is kept.'),BUSY:t('正在处理，请稍候。','Please wait for the current action.'),IDENTITY_CHANGED:t('账号已切换，请在当前账号重新操作。','Your account changed. Continue in the current account.')}[code]??t('未能完成，请稍后重试。','Could not complete this action. Try again.'));
 const uid=crypto.randomUUID().slice(0,8);
 let browseSelection=null,preserveImagesForHandoff=false,checkingProfile=false,pendingEntryDraft=initialDraft?.kind==='comment'?null:initialDraft?{draft:initialDraft,scope:sessionValue(getSession())}:null;
 let destroyed=false,editorDialog=null,detailDialog=null,reportDialog=null,confirmDialog=null,editorRegion=null,browseRegion=null,previewUrl=null,editorOrigin=null,detailOrigin=null,reportPostId=null;
 const imageScopes={feed:{turn:0,releases:[]},detail:{turn:0,releases:[]}};
 const model=createCommunityController({repository,getSession,uploadImage,initialAuthorId,onState:changed});
 const dateText=value=>{const date=new Date(value);return Number.isFinite(date.getTime())?date.toLocaleDateString(en()?'en-GB':'zh-CN',{timeZone:'Asia/Shanghai'}):'';};
 const button=(label,className='button secondary')=>{const b=doc.createElement('button');b.type='button';b.className=className;b.textContent=label;return b;};
 function notify(){onChanged();}
 function reportError(error){if(destroyed||error?.code==='IDENTITY_CHANGED')return;onError?.(error);const status=container.querySelector('[data-community-notice]');if(status){status.textContent=errorText(error.code);status.hidden=false;}}
 function completeNotice(message){const node=container.querySelector('[data-community-notice]');if(node){node.textContent=message;node.hidden=false;}}
 function handoff(kind){const draft=model.getDraftHandoff(),session=sessionValue(getSession());const intent=kind==='login'?'login':'profile';let id=null;if(draft){id=draftHandoff.stage({draft,ownerId:session.userId,intent});preserveImagesForHandoff=true;}(kind==='login'?onLogin:onProfile)?.({...(id?{handoffId:id}:{}),returnTo:'community'});}
 function actionFailed(error){if(error?.code==='UNAUTHENTICATED'){handoff('login');return;}if(error?.code==='PROFILE_REQUIRED'){handoff('profile');return;}reportError(error);}
 const attempt=task=>Promise.resolve().then(task).catch(actionFailed);
 function releaseImages(scope){for(const group of scope?[imageScopes[scope]]:Object.values(imageScopes)){group.turn++;for(const release of group.releases.splice(0))release?.();}}
 function image(element,assetId,reference,scope='feed'){if(!assetId||!resolveImage)return;const group=imageScopes[scope],turn=group.turn,captured=sessionValue(getSession());let active=true;const load=()=>{if(!active)return;Promise.resolve(resolveImage(assetId,reference)).then(result=>{if(destroyed||!active||turn!==group.turn||!same(captured,sessionValue(getSession()))||!element.isConnected)return;const dataUrl=result?.dataUrl??(typeof result==='string'?result:null);if(typeof dataUrl!=='string'||!dataUrl.startsWith('data:image/'))return;element.src=dataUrl;element.hidden=false;if(element.parentElement?.classList.contains('public-avatar'))element.parentElement.replaceChildren(element);}).catch(()=>{if(active&&element.isConnected)element.hidden=true;});};if(typeof IntersectionObserver==='undefined'){load();group.releases.push(()=>active=false);return;}const observer=new IntersectionObserver(entries=>{if(entries.some(entry=>entry.isIntersecting)){observer.disconnect();load();}},{rootMargin:'100px'});/* A hidden image has no intersection box; observe its visible avatar/card instead. */observer.observe(element.parentElement??element);group.releases.push(()=>{active=false;observer.disconnect();});}
 function identityNode(identity,reference,scope='feed'){const row=doc.createElement('div');row.className='post-user public-identity';const avatar=doc.createElement('span');avatar.className='public-avatar';avatar.textContent=(identity?.nickname??'').slice(0,1);if(identity?.avatarAssetId){const img=doc.createElement('img');img.alt='';img.hidden=true;avatar.append(img);image(img,identity.avatarAssetId,reference,scope);}const author=button(identity?.nickname??t('宠友','Pet friend'),'text-button community-author');author.onclick=()=>{if(model.isSaving())return;if(onViewAuthorPosts)onViewAuthorPosts(identity.authorId);else openAuthorPosts(identity.authorId);};row.append(avatar,author);return row;}
 function postActions(item,{detail=false}={}){const actions=doc.createElement('div');actions.className='post-actions';const state=model.getLikeState(item.post.id),like=button((state.liked?t('已点赞','Liked'):t('点赞','Like'))+' '+state.likeCount,'text-button'+(state.liked?' liked':''));like.dataset.likePost=item.post.id;like.setAttribute('aria-pressed',String(state.liked));like.setAttribute('aria-disabled',String(state.busy));like.onclick=()=>{if(!model.isLikeBusy(item.post.id))attempt(()=>model.setLiked(item.post.id,!model.getLikeState(item.post.id).liked));};actions.append(like);const likeError=doc.createElement('span');likeError.dataset.likeError=item.post.id;likeError.className='form-error';likeError.setAttribute('role','alert');likeError.hidden=!state.error;likeError.textContent=state.error?errorText(state.error):'';actions.append(likeError);
  if(!detail){const view=button(t('查看详情','View details'),'text-button');view.onclick=()=>attempt(()=>model.openPost(item.post.id));actions.append(view);}
  if(item.isOwn){const edit=button(t('编辑','Edit'),'text-button');edit.dataset.communityConflictAction='edit';edit.disabled=!!model.getState().detail?.busy||!!model.getState().editor?.busy;edit.onclick=()=>{const start=()=>{if(detail&&!model.closePost())return;editorOrigin=edit;model.editPost(item);};if(detail&&model.getState().detail?.commentText)askConfirm(t('放弃未发送的评论？','Discard this comment?'),t('未发送的评论会丢失。','Your unsent comment will be lost.'),start);else start();};const remove=button(t('删除','Delete'),'text-button danger-text');remove.dataset.communityConflictAction='delete';remove.disabled=edit.disabled;remove.onclick=()=>askConfirm(t('删除这篇帖子？','Delete this post?'),t('删除后，帖子和评论不再公开显示。','The post and its comments will no longer be public.'),()=>attempt(()=>model.deletePost(item.post.id)));actions.append(edit,remove);}
  const report=button(t('举报','Report'),'text-button');report.onclick=()=>{if(!sessionValue(getSession()).userId){onLogin?.({returnTo:'community'});return;}openReport(item.post.id);};const hide=button(t('不想看这篇','Hide this post'),'text-button');hide.dataset.communityConflictAction='hide';hide.disabled=!!model.getState().detail?.busy||!!model.getState().editor?.busy;hide.onclick=()=>attempt(()=>model.hidePost(item.post.id));actions.append(report,hide);return actions;
 }
 function postCard(item){const article=doc.createElement('article');article.className='post community-card';article.dataset.communityPost=item.post.id;const content=doc.createElement('div');content.className='post-content';content.append(identityNode(item.identity,{kind:'post',id:item.post.id}));const heading=doc.createElement('h2');heading.textContent=item.post.title;const body=doc.createElement('p');body.className='post-text community-article-text';body.textContent=item.post.text;const meta=doc.createElement('p');meta.className='post-topic';meta.textContent=[topicText(item.post.topic),item.post.cityName,dateText(item.post.createdAt)].filter(Boolean).join(' · ');content.append(heading,body,meta,postActions(item));if(item.post.imageAssetId){const img=doc.createElement('img');img.className='post-image';img.alt=t('作者主动公开的帖子图片','Post image made public by its author');img.hidden=true;article.append(img);image(img,item.post.imageAssetId,{kind:'post',id:item.post.id});}article.append(content);return article;}
 function renderShell(){browseRegion?.destroy?.();container.innerHTML=`<section class="community-public"><div class="page-heading community-toolbar"><div><h1>${t('社区','Community')}</h1><p>${t('分享日常，也向宠友提问。','Share daily moments and ask other pet owners.')}</p></div><button class="button" type="button" data-community-write>${t('写一篇','Write a post')}</button></div><div class="filter-bar community-filters"><div class="tabs" role="tablist" aria-label="${t('社区范围','Community scope')}"><button class="tab" type="button" role="tab" data-community-scope="all">${t('全部','All')}</button><button class="tab" type="button" role="tab" data-community-scope="city">${t('同城','Same city')}</button></div><label class="field"><span>${t('话题','Topic')}</span><select data-community-topic><option value="">${t('全部话题','All topics')}</option>${COMMUNITY_TOPICS.map(topic=>`<option value="${escape(topic)}">${topicText(topic)}</option>`).join('')}</select></label><form class="community-search" data-community-search><label class="field"><span>${t('搜索帖子','Search posts')}</span><input type="search" name="query" maxlength="80" placeholder="${t('标题或正文关键词','Title or text keywords')}"></label><button type="submit" class="button secondary">${t('搜索','Search')}</button></form></div><div data-community-browse-region hidden></div><div data-community-author-filter hidden><span>${t('正在查看这位宠友的帖子','Posts from this author')}</span><button class="text-button" type="button" data-community-clear-author>${t('查看所有宠友','Show all authors')}</button></div><p class="community-status" data-community-status role="status"></p><p class="form-tip" data-community-notice role="status" hidden></p><div class="feed community-feed" data-community-feed aria-label="${t('公开帖子','Public posts')}"></div><button type="button" class="button secondary" data-community-more hidden>${t('更多帖子','More posts')}</button></section>`;
  const filters=model.getState().filters;container.querySelector('[data-community-topic]').value=filters.topic??'';container.querySelector('[name="query"]').value=filters.query??'';container.querySelector('[data-community-write]').onclick=()=>openDraft();container.querySelector('[data-community-more]').onclick=()=>attempt(()=>model.load({more:true}));container.querySelector('[data-community-search]').onsubmit=event=>{event.preventDefault();model.setFilters({query:event.target.elements.query.value.trim()});attempt(()=>model.load());};container.querySelector('[data-community-topic]').onchange=event=>{model.setFilters({topic:event.target.value});attempt(()=>model.load());};const scopeTabs=[...container.querySelectorAll('[data-community-scope]')];scopeTabs.forEach((tab,index)=>{tab.onclick=()=>selectScope(tab.dataset.communityScope);tab.onkeydown=event=>{if(!['ArrowLeft','ArrowRight','Home','End'].includes(event.key))return;event.preventDefault();const next=event.key==='Home'?0:event.key==='End'?scopeTabs.length-1:(index+(event.key==='ArrowRight'?1:-1)+scopeTabs.length)%scopeTabs.length;scopeTabs[next].focus();selectScope(scopeTabs[next].dataset.communityScope);};});container.querySelector('[data-community-clear-author]').onclick=()=>{model.setFilters({authorId:undefined});attempt(()=>model.load());};renderBrowseRegion();renderList();
 }
 function renderBrowseRegion(){const state=model.getState(),host=container.querySelector('[data-community-browse-region]');if(!host)return;host.hidden=state.filters.scope!=='city';if(host.hidden){browseRegion?.destroy?.();browseRegion=null;return;}if(mountRegionPicker&&!browseRegion)browseRegion=mountRegionPicker({container:host,repository,initialValue:browseSelection??getBrowseRegion()??{},getLocale,getGeneration:()=>sessionValue(getSession()).generation,onChange:region=>{browseSelection={...region};onBrowseRegion?.(region);model.setFilters({cityId:region.cityId??undefined,districtId:region.districtId??undefined});if(region.cityId)attempt(()=>model.load());else renderList();},onError:reportError});else if(!mountRegionPicker&&!host.firstChild){const note=doc.createElement('p');note.className='form-tip';note.textContent=t('请从页首选择浏览城市。','Choose a browsing city at the top of the page.');host.append(note);}}
 function selectScope(scope){const region=browseSelection??getBrowseRegion()??{};model.setFilters({scope,...(scope==='city'?{cityId:region.cityId??undefined,districtId:region.districtId??undefined}:{})});renderBrowseRegion();if(scope!=='city'||region.cityId)attempt(()=>model.load());}
 function renderList(){if(destroyed)return;const state=model.getState(),feed=container.querySelector('[data-community-feed]'),status=container.querySelector('[data-community-status]');if(!feed)return;releaseImages('feed');feed.replaceChildren(...state.items.map(postCard));for(const tab of container.querySelectorAll('[data-community-scope]')){const selected=tab.dataset.communityScope===state.filters.scope;tab.classList.toggle('active',selected);tab.setAttribute('aria-selected',String(selected));tab.tabIndex=selected?0:-1;}container.querySelector('[data-community-author-filter]').hidden=!state.filters.authorId;const more=container.querySelector('[data-community-more]');more.hidden=!state.nextCursor;more.disabled=state.status==='loading';feed.setAttribute('aria-busy',String(state.status==='loading'));
  if(state.status==='loading')status.textContent=t('正在读取公开帖子…','Loading public posts…');else if(state.status==='error'){status.textContent=errorText(state.error);const retry=button(t('重新读取','Retry loading'));retry.onclick=()=>attempt(()=>model.load());status.append(' ',retry);}else if(state.filters.scope==='city'&&!state.filters.cityId)status.textContent=t('选择城市后，查看同城的公开帖子。','Choose a city to view local public posts.');else if(!state.items.length)status.textContent=state.nextCursor?t('这一页没有可显示的帖子。可以继续加载，或调整筛选。','No visible posts on this page. Load more or change filters.'):t('暂时没有符合筛选的公开帖子，可以调整筛选或写下第一篇。','No public posts match these filters. Change filters or write the first post.');else status.textContent='';
 }
 function createDialog(className,title,closeLabel){const dialog=doc.createElement('dialog');dialog.className=className;const titleId='community-'+className+'-'+uid;dialog.setAttribute('aria-labelledby',titleId);dialog.innerHTML=`<div class="dialog-head"><h2 id="${titleId}" tabindex="-1">${title}</h2><button type="button" class="button secondary" data-dialog-close>${closeLabel}</button></div><div data-dialog-body></div>`;if(onLocaleChange&&className!=='discard-dialog'){const label=doc.createElement('label');label.className='dialog-locale-picker';const name=doc.createElement('span');name.className='sr-only';name.textContent='语言 / Language';const select=doc.createElement('select');select.dataset.communityDialogLocale='';select.setAttribute('aria-label','语言 / Language');for(const [value,text]of [['zh-CN','中文'],['en','English']]){const option=doc.createElement('option');option.value=value;option.textContent=text;select.append(option);}select.value=getLocale();select.onchange=()=>onLocaleChange(select.value);label.append(name,select);dialog.querySelector('.dialog-head').insertBefore(label,dialog.querySelector('[data-dialog-close]'));}doc.body.append(dialog);return dialog;}
 function showDialog(dialog){if(!dialog.open){dialog.showModal();dialog.querySelector('h2')?.focus({preventScroll:true});}}
 function closeEditor(){if(model.isSaving())return;const finish=()=>{model.cancelDraft();draftHandoff.clear();editorDialog?.close();if(editorOrigin?.isConnected)editorOrigin.focus({preventScroll:true});};if(model.getState().editor?.dirty)askConfirm(t('放弃这篇草稿？','Discard this draft?'),t('未发布的输入会丢失。','Your unpublished input will be lost.'),finish);else finish();}
 function closeDetail(){if(model.getState().detail?.busy)return;const finish=()=>{model.closePost();if(detailOrigin?.isConnected)detailOrigin.focus({preventScroll:true});};if(model.getState().detail?.commentText)askConfirm(t('放弃未发送的评论？','Discard this comment?'),t('未发送的评论会丢失。','Your unsent comment will be lost.'),finish);else finish();}
 function askConfirm(title,description,onConfirm){if(confirmDialog?.open)return;if(!confirmDialog){confirmDialog=createDialog('discard-dialog',title,t('继续编辑','Keep editing'));confirmDialog.setAttribute('role','alertdialog');}const body=confirmDialog.querySelector('[data-dialog-body]');body.replaceChildren();confirmDialog.querySelector('h2').textContent=title;const p=doc.createElement('p');p.textContent=description;const actions=doc.createElement('div');actions.className='discard-actions';const keep=button(t('继续编辑','Keep editing'),'button'),confirm=button(t('确认','Confirm'),'button secondary danger-text');keep.onclick=()=>confirmDialog.close();confirm.onclick=()=>{confirmDialog.close();onConfirm();};confirmDialog.querySelector('[data-dialog-close]').hidden=true;actions.append(keep,confirm);body.append(p,actions);showDialog(confirmDialog);keep.focus();}
 function renderEditor(){const editor=model.getState().editor;if(!editor){if(editorDialog?.open)editorDialog.close();editorRegion?.destroy?.();editorRegion=null;return;}if(!editorDialog){editorDialog=createDialog('community-editor-dialog',t('写一篇公开帖子','Write a public post'),t('关闭编辑器','Close editor'));editorDialog.dataset.communityEditor='';editorDialog.querySelector('[data-dialog-close]').onclick=closeEditor;editorDialog.addEventListener('cancel',event=>{event.preventDefault();closeEditor();});}
  const body=editorDialog.querySelector('[data-dialog-body]');editorRegion?.destroy?.();const draft=editor.draft;editorDialog.querySelector('h2').textContent=draft.id?t('编辑公开帖子','Edit public post'):t('写一篇公开帖子','Write a public post');editorDialog.querySelector('[data-dialog-close]').textContent=t('关闭编辑器','Close editor');body.innerHTML=`<form data-community-editor-form><div class="form-grid"><label class="field full"><span>${t('标题','Title')}</span><input name="title" maxlength="60" required value="${escape(draft.title)}"></label><label class="field full"><span>${t('正文','Post text')}</span><textarea name="text" maxlength="1500" required rows="6">${escape(draft.text)}</textarea></label><label class="field full"><span>${t('话题','Topic')}</span><select name="topic">${COMMUNITY_TOPICS.map(topic=>`<option value="${escape(topic)}">${topicText(topic)}</option>`).join('')}</select></label><div class="field full" data-community-editor-region></div><label class="field full"><span>${t('一张公开图片 · 可选','One public image · optional')}</span><input name="image" type="file" accept="image/jpeg,image/png,image/webp"><small>${t('原图最多10MiB。选择的图片会和帖子一起公开。','Source images up to 10MiB. The selected image will be public with this post.')}</small></label><div class="field full" data-community-image-preview></div></div><p class="form-tip">${t('确认发布后，昵称、头像和这篇内容会向所有访问者显示。','Publishing makes your nickname, avatar and this post visible to all visitors.')}</p><p data-community-editor-error class="form-error" role="alert" tabindex="-1" hidden></p><div data-community-editor-review></div><div class="form-actions"><button type="button" class="button secondary" data-community-cancel>${t('取消','Cancel')}</button><button class="button" type="submit">${draft.id?t('保存修改','Save changes'):t('确认发布','Publish post')}</button></div></form>`;const form=body.querySelector('form');form.elements.topic.value=draft.topic;form.addEventListener('input',event=>{if(['title','text','topic'].includes(event.target.name))model.setDraft(event.target.name,event.target.value);});form.elements.topic.onchange=event=>model.setDraft('topic',event.target.value);form.elements.image.onchange=event=>model.setImageFile(event.target.files?.[0]??null);form.onsubmit=event=>{event.preventDefault();attempt(()=>model.saveDraft());};body.querySelector('[data-community-cancel]').onclick=closeEditor;
  if(mountRegionPicker)editorRegion=mountRegionPicker({container:body.querySelector('[data-community-editor-region]'),repository,initialValue:{cityId:draft.cityId,districtId:draft.districtId},getLocale,getGeneration:()=>sessionValue(getSession()).generation,onChange:region=>{model.setDraft('cityId',region.cityId);model.setDraft('districtId',region.districtId);},onError:reportError});else body.querySelector('[data-community-editor-region]').textContent=draft.cityId?t('帖子城市：','Post city: ')+draft.cityId:t('未选城市，帖子会进入全部。','No city selected; the post will appear under All.');renderPreview();updateEditorState();showDialog(editorDialog);
 }
 function renderPreview(){const editor=model.getState().editor,host=editorDialog?.querySelector('[data-community-image-preview]');if(!host||!editor)return;host.replaceChildren();if(previewUrl){URL.revokeObjectURL(previewUrl);previewUrl=null;}if(editor.file){previewUrl=URL.createObjectURL(editor.file);const img=doc.createElement('img');img.className='photo-preview';img.alt=t('待发布图片预览','Image preview before publishing');img.src=previewUrl;host.append(img);}else if(editor.draft.imageAssetId){const p=doc.createElement('p');p.textContent=t('已保留这篇帖子原有的图片。','The existing post image is retained.');host.append(p);}if(editor.file||editor.draft.imageAssetId){const remove=button(t('移除图片','Remove image'),'text-button');remove.onclick=()=>{model.removeImage();const input=editorDialog?.querySelector('[name="image"]');if(input)input.value='';};host.append(remove);}}
 function updateEditorState(){const editor=model.getState().editor,form=editorDialog?.querySelector('form');if(!editor||!form)return;for(const control of form.elements)control.disabled=editor.busy;editorDialog.querySelector('[data-dialog-close]').disabled=editor.busy;const submit=form.querySelector('[type="submit"]');submit.textContent=editor.busy?t('正在保存…','Saving…'):editor.draft.id?t('保存修改','Save changes'):t('确认发布','Publish post');const alert=form.querySelector('[data-community-editor-error]');alert.hidden=!editor.error;alert.textContent=editor.error?errorText(editor.error):'';
  const review=editorDialog.querySelector('[data-community-editor-review]');review.replaceChildren();if(editor.error==='CONFLICT'&&!editor.review){const reload=button(t('核对最新帖子','Review latest post'));reload.onclick=()=>attempt(()=>model.reviewLatestDraft());review.append(reload);}if(editor.review){const title=doc.createElement('p'),body=doc.createElement('p');title.textContent=t('云端最新标题：','Latest title: ')+editor.review.title;body.textContent=editor.review.text;body.className='community-article-text';const keep=button(t('保留我的输入，使用最新版本再提交','Keep my input and use the latest revision'));keep.onclick=()=>model.acceptDraftRevision();review.append(title,body,keep);}}
 function renderDetail(){releaseImages('detail');const detail=model.getState().detail;if(!detail){if(detailDialog?.open)detailDialog.close();return;}if(!detailDialog){detailOrigin=doc.activeElement;detailDialog=createDialog('community-detail-dialog',t('帖子详情','Post details'),t('关闭详情','Close details'));detailDialog.dataset.communityDetail='';detailDialog.querySelector('[data-dialog-close]').onclick=closeDetail;detailDialog.addEventListener('cancel',event=>{event.preventDefault();closeDetail();});}detailDialog.querySelector('h2').textContent=t('帖子详情','Post details');detailDialog.querySelector('[data-dialog-close]').textContent=t('关闭详情','Close details');const body=detailDialog.querySelector('[data-dialog-body]');body.className='community-detail-layout';detailDialog.classList.remove('has-post-image');body.replaceChildren();if(detail.status==='loading'){const loading=doc.createElement('p');loading.setAttribute('role','status');loading.textContent=t('正在读取帖子与评论…','Loading the post and comments…');body.append(loading);showDialog(detailDialog);return;}if(detail.status==='error'){const p=doc.createElement('p');p.setAttribute('role','alert');p.textContent=errorText(detail.error);body.append(p);if(detail.error!=='NOT_FOUND'){const retry=button(t('重新读取帖子','Reload post'));retry.onclick=()=>attempt(()=>model.openPost(detail.id));body.append(retry);}showDialog(detailDialog);return;}
  const item=detail.item,content=doc.createElement('div'),article=doc.createElement('article');content.className='community-detail-content';detailDialog.classList.toggle('has-post-image',!!item.post.imageAssetId);body.append(content);article.append(identityNode(item.identity,{kind:'post',id:item.post.id},'detail'));const heading=doc.createElement('h3'),text=doc.createElement('p');heading.textContent=item.post.title;text.textContent=item.post.text;text.className='post-text community-article-text';article.append(heading,text);if(item.post.imageAssetId){const img=doc.createElement('img');img.className='photo-preview';img.alt=t('作者公开的帖子图片','Public post image');img.hidden=true;const media=doc.createElement('div');media.className='community-detail-media';media.append(img);body.prepend(media);image(img,item.post.imageAssetId,{kind:'post',id:item.post.id},'detail');}article.append(postActions(item,{detail:true}));content.append(article);const commentTitle=doc.createElement('h3');commentTitle.textContent=t('评论','Comments');const commentList=doc.createElement('div');commentList.className='comments';for(const row of detail.comments){const node=doc.createElement('article');node.className='comment';node.append(identityNode(row.identity,{kind:'comment',id:row.comment.id},'detail'));const p=doc.createElement('p');p.textContent=row.comment.text;node.append(p);if(row.isOwn){const remove=button(t('删除评论','Delete comment'),'text-button danger-text');remove.dataset.communityConflictAction='comment-delete';remove.disabled=detail.busy;remove.onclick=()=>askConfirm(t('删除这条评论？','Delete this comment?'),t('删除后不再公开显示。','It will no longer be public.'),()=>attempt(()=>model.deleteComment(row.comment.id)));node.append(remove);}commentList.append(node);}if(!detail.comments.length){const p=doc.createElement('p');p.className='form-tip';p.textContent=t('还没有评论。分享你的经验，或友好提问。','No comments yet. Share your experience or ask a friendly question.');commentList.append(p);}content.append(commentTitle,commentList);if(detail.nextCursor){const more=button(t('更多评论','More comments'));more.onclick=()=>attempt(()=>model.loadComments());content.append(more);}
  const form=doc.createElement('form');form.dataset.communityCommentForm='';form.innerHTML=`<label class="field"><span>${t('你的评论','Your comment')}</span><textarea name="comment" maxlength="400" required rows="3"></textarea></label><p data-community-comment-error role="alert" class="form-error" hidden></p><div class="form-actions"><button class="button" type="submit">${t('发表评论','Post comment')}</button></div>`;form.elements.comment.value=detail.commentText;form.elements.comment.oninput=event=>model.setCommentText(event.target.value);form.onsubmit=event=>{event.preventDefault();attempt(()=>model.saveComment());};content.append(form);updateCommentState();showDialog(detailDialog);
 }
 function updateCommentState(){const detail=model.getState().detail,form=detailDialog?.querySelector('[data-community-comment-form]');if(!detail||!form)return;for(const control of form.elements)control.disabled=detail.busy;detailDialog.querySelector('[data-dialog-close]').disabled=detail.busy;for(const control of detailDialog.querySelectorAll('[data-community-conflict-action],.community-author,[data-like-post]'))control.disabled=detail.busy;form.querySelector('[type="submit"]').textContent=detail.busy?t('正在发送…','Sending…'):t('发表评论','Post comment');const alert=form.querySelector('[data-community-comment-error]');alert.hidden=!detail.error;alert.textContent=detail.error?errorText(detail.error):'';}
 function openReport(postId){reportPostId=postId;if(!reportDialog){reportDialog=createDialog('community-report-dialog',t('举报帖子','Report post'),t('关闭举报','Close report'));reportDialog.querySelector('[data-dialog-close]').onclick=()=>reportDialog.close();}reportDialog.querySelector('h2').textContent=t('举报帖子','Report post');reportDialog.querySelector('[data-dialog-close]').textContent=t('关闭举报','Close report');reportDialog.querySelector('[data-dialog-body]').innerHTML=`<form data-community-report-form><label class="field"><span>${t('举报原因','Reason')}</span><select name="reason" required><option value="">${t('请选择原因','Choose a reason')}</option>${['广告骚扰','不当内容','隐私问题','其他'].map(reason=>`<option value="${reason}">${en()?({'广告骚扰':'Spam or harassment','不当内容':'Inappropriate content','隐私问题':'Privacy concern','其他':'Other'}[reason]):reason}</option>`).join('')}</select></label><label class="field"><span>${t('补充说明 · 可选','Additional details · optional')}</span><textarea name="note" maxlength="200"></textarea></label><p class="form-tip">${t('提交后等待维护者处理，不会自动删除帖子。','A maintainer will review your report. It does not automatically remove the post.')}</p><p data-report-error role="alert" hidden></p><div class="form-actions"><button class="button" type="submit">${t('提交举报','Submit report')}</button></div></form>`;const form=reportDialog.querySelector('form');form.onsubmit=async event=>{event.preventDefault();const submit=form.querySelector('[type="submit"]');submit.disabled=true;try{await model.reportPost(reportPostId,form.elements.reason.value,form.elements.note.value);if(destroyed)return;reportDialog.close();completeNotice(t('已提交，等待处理。','Submitted and awaiting review.'));}catch(error){form.querySelector('[data-report-error]').hidden=false;form.querySelector('[data-report-error]').textContent=errorText(error.code);actionFailed(error);}finally{submit.disabled=false;}};showDialog(reportDialog);}
 function updateLikes(){for(const root of [container,detailDialog].filter(Boolean)){for(const like of root.querySelectorAll('[data-like-post]')){const state=model.getLikeState(like.dataset.likePost);like.textContent=(state.liked?t('已点赞','Liked'):t('点赞','Like'))+' '+state.likeCount;like.classList.toggle('liked',state.liked);like.setAttribute('aria-pressed',String(state.liked));like.setAttribute('aria-busy',String(state.busy));/* aria-disabled keeps the activating button focused while blocking duplicate writes. */like.setAttribute('aria-disabled',String(state.busy));const error=like.parentElement.querySelector('[data-like-error]');if(error){error.hidden=!state.error;error.textContent=state.error?errorText(state.error):'';}}}}
 function changed(state,kind){if(destroyed)return;notify();if(kind==='cleanup'){if(state.cleanupPending.length){const notice=container.querySelector('[data-community-notice]');if(notice){notice.hidden=false;notice.textContent=t('图片已移除，后台清理尚未完成。','The image was removed; cleanup is still pending.');const retry=button(t('重试图片清理','Retry image cleanup'),'text-button');retry.onclick=()=>attempt(()=>model.flushImageCleanup());notice.append(' ',retry);}}return;}if(kind==='draft-input'||kind==='comment-input')return;if(kind==='draft-file'){renderPreview();return;}if(kind==='editor-open')renderEditor();else if(['editor-saving','editor-error','editor-review','saving-end'].includes(kind))updateEditorState();else if(['editor-close','editor-saved'].includes(kind)){renderEditor();renderList();if(kind==='editor-saved')completeNotice(t('已发布到公开社区。','Published to the public community.'));}else if(kind==='detail-open'||kind==='detail'||kind==='comment-saved')renderDetail();else if(kind==='detail-close')renderDetail();else if(kind==='comment-saving'||kind==='comment-error')updateCommentState();else if(kind==='identity'){renderEditor();renderDetail();renderList();}else if(kind==='like')updateLikes();else renderList();if(kind==='saving-end')updateCommentState();}
 async function openDraft(draft={}){
  if(model.isSaving()){reportError(failure('BUSY'));return false;}if(checkingProfile)return false;
  const captured=sessionValue(getSession());if(pendingEntryDraft&&!same(pendingEntryDraft.scope,captured))pendingEntryDraft=null;
  if(Object.keys(draft).length)pendingEntryDraft={draft,scope:captured};
  const region=browseSelection??getBrowseRegion()??{},value={cityId:region.cityId??null,districtId:region.districtId??null,...(pendingEntryDraft?.draft??draft)};
  if(captured.userId){
   checkingProfile=true;const write=container.querySelector('[data-community-write]');if(write)write.disabled=true;
   completeNotice(t('正在检查发帖昵称…','Checking your public nickname…'));
   try{
    const profile=await repository.request('profiles.getOwn',{});
    if(destroyed||!same(captured,sessionValue(getSession())))return false;
    if(!profile?.nickname?.trim()){
     const handoffId=draftHandoff.stage({draft:value,ownerId:captured.userId,intent:'profile'});preserveImagesForHandoff=true;
     completeNotice(t('发帖前请先保存公开昵称，保存后继续写帖。','Save a public nickname first, then continue writing.'));
     if(onProfile){pendingEntryDraft=null;onProfile({handoffId,returnTo:'community',requireNickname:true});}return false;
    }
    const notice=container.querySelector('[data-community-notice]');if(notice)notice.hidden=true;
   }catch(error){if(!destroyed&&same(captured,sessionValue(getSession())))actionFailed(error);return false;}
   finally{checkingProfile=false;const currentWrite=container.querySelector('[data-community-write]');if(currentWrite)currentWrite.disabled=false;}
  }
  if(destroyed||!same(captured,sessionValue(getSession())))return false;
  if(model.isSaving()){reportError(failure('BUSY'));return false;}
  const start=()=>{editorOrigin=doc.activeElement;model.openDraft(value);pendingEntryDraft=null;};
  if(model.hasUnsavedChanges()&&model.getState().editor)askConfirm(t('替换当前草稿？','Replace this draft?'),t('当前未发布的输入会丢失。','The current unpublished input will be lost.'),start);else start();
 }
 function openAuthorPosts(authorId){if(model.isSaving()){reportError(failure('BUSY'));return false;}const start=()=>{if(model.getState().detail)model.closePost();model.setFilters({authorId});attempt(()=>model.load());};if(model.getState().detail?.commentText)askConfirm(t('放弃未发送的评论？','Discard this comment?'),t('未发送的评论会丢失。','Your unsent comment will be lost.'),start);else start();}
 renderShell();attempt(()=>model.load());
 if(initialDraft?.kind==='comment'){attempt(async()=>{await model.openPost(initialDraft.postId);model.setCommentText(initialDraft.text??'');model.restoreCommentOperation(initialDraft.operationId);renderDetail();});}else if(initialDraft)openDraft(initialDraft);
 return {destroy(){destroyed=true;model.destroy({preserveImages:preserveImagesForHandoff});releaseImages();editorRegion?.destroy?.();browseRegion?.destroy?.();if(previewUrl)URL.revokeObjectURL(previewUrl);for(const dialog of [editorDialog,detailDialog,reportDialog,confirmDialog]){if(dialog?.open)dialog.close();dialog?.remove();}container.replaceChildren();},hasUnsavedChanges:model.hasUnsavedChanges,isSaving:model.isSaving,refreshLocale(){for(const dialog of [editorDialog,detailDialog,reportDialog]){const select=dialog?.querySelector('[data-community-dialog-locale]');if(select)select.value=getLocale();}const pendingQuery=container.querySelector('[name="query"]')?.value,reportValues=reportDialog?.open?{reason:reportDialog.querySelector('[name="reason"]').value,note:reportDialog.querySelector('[name="note"]').value}:null;renderShell();if(pendingQuery!==undefined)container.querySelector('[name="query"]').value=pendingQuery;if(model.getState().editor)renderEditor();if(model.getState().detail)renderDetail();if(reportValues){openReport(reportPostId);reportDialog.querySelector('[name="reason"]').value=reportValues.reason;reportDialog.querySelector('[name="note"]').value=reportValues.note;}},openDraft,openAuthorPosts,setBrowseRegion(region={}){browseSelection={...region};browseRegion?.destroy?.();browseRegion=null;renderBrowseRegion();return model.setBrowseRegion(region);},refresh:()=>model.load(),getState:model.getState};
}
