const fields=['nickname','avatarAssetId','bio','cityId','districtId','petTypes','purposes','discoverable'];
const empty=()=>({nickname:'',avatarAssetId:null,bio:'',cityId:null,districtId:null,petTypes:[],purposes:[],discoverable:false});
const copy=value=>structuredClone(value);
const same=(a,b)=>a?.userId===b?.userId&&a?.generation===b?.generation;
const boundary=()=>Object.assign(new Error('Account changed'),{code:'WORKSPACE_CHANGED'});
export function createHiddenPostsController({repository,getSession,onState=()=>{},idFactory=()=>crypto.randomUUID()}={}){
 let disposed=false,bound={...getSession()},turn=0,state={items:[],nextCursor:null,status:'idle',error:null,errors:{}};
 const busy=new Set(),keys=new Map();
 const current=()=>({...getSession()});
 const snapshot=()=>({...copy(state),busyIds:[...busy]});
 const notify=()=>{if(!disposed)onState(snapshot());};
 function synchronize(){const next=current();if(!same(bound,next)){bound=next;turn++;state={items:[],nextCursor:null,status:'idle',error:null,errors:{}};busy.clear();keys.clear();notify();}}
 function capture(){synchronize();if(disposed)throw boundary();if(!bound.userId)throw Object.assign(Error('Sign in required'),{code:'UNAUTHENTICATED'});return {...bound};}
 function valid(origin){if(disposed||!same(origin,current())){synchronize();throw boundary();}}
 return {
  getState(){synchronize();return snapshot();},isBusy:()=>busy.size>0,
  async load({more=false}={}){const origin=capture();if(busy.size||state.status==='loading')throw Object.assign(Error('Request pending'),{code:'BUSY'});if(more&&!state.nextCursor)return;const serial=++turn;state.status='loading';state.error=null;notify();try{const reply=await repository.request('community.hidden.list',{limit:20,...(more?{cursor:state.nextCursor}:{})});valid(origin);if(serial!==turn)return;state.items=[...new Map((more?[...state.items,...reply.items]:reply.items).map(row=>[row.postId,row])).values()];state.nextCursor=reply.nextCursor??null;state.status='ready';notify();}catch(error){valid(origin);if(serial!==turn)return;state.error=error.code??'UNAVAILABLE';state.status='error';notify();throw error;}},
  async restore(postId){const origin=capture();if(busy.has(postId)||state.status==='loading')throw Object.assign(Error('Restore pending'),{code:'BUSY'});if(!state.items.some(row=>row.postId===postId))throw Object.assign(Error('Hidden post unavailable'),{code:'NOT_FOUND'});busy.add(postId);delete state.errors[postId];if(!keys.has(postId))keys.set(postId,idFactory());notify();try{const result=await repository.request('community.hide',{postId,hidden:false},{operationId:keys.get(postId)});valid(origin);if(result.postId!==postId||result.hidden!==false)throw Object.assign(Error('Unexpected restore result'),{code:'UNAVAILABLE'});state.items=state.items.filter(row=>row.postId!==postId);keys.delete(postId);notify();return result;}catch(error){valid(origin);state.errors[postId]=error.code??'UNAVAILABLE';notify();throw error;}finally{busy.delete(postId);notify();}},
  destroy(){disposed=true;turn++;state.items=[];busy.clear();keys.clear();},
 };
}
export function createProfileEditor({repository,getSession}={}){
 let value=empty(),original=JSON.stringify(value),account={},revision=0,operationId=null,busy=false,bound=null,pendingLatest=null;
 const scope=()=>({...getSession()});
 const check=s=>{if(!same(s,scope()))throw boundary();};
 const payload=()=>Object.fromEntries(fields.map(key=>[key,copy(value[key])]));
 return {
  async load(){const s=scope();bound=s;const [profile,info]=await Promise.all([repository.request('profiles.getOwn',{}),repository.request('auth.getOwn',{})]);check(s);value={...empty(),...(profile??{})};revision=profile?.revision??0;account=info??{};original=JSON.stringify(payload());operationId=null;return copy(value);},
  set(key,next){if(!fields.includes(key))return;if(JSON.stringify(value[key])!==JSON.stringify(next)){value[key]=copy(next);operationId=null;}},
  setRegion(region){this.set('cityId',region.cityId);this.set('districtId',region.districtId);value.cityName=region.cityName??null;value.districtName=region.districtName??null;},
  values:()=>copy(value),account:()=>copy(account),isDirty:()=>JSON.stringify(payload())!==original,isBusy:()=>busy,
  preview(){const p={nickname:value.nickname,avatarAssetId:value.avatarAssetId};if(value.discoverable)Object.assign(p,{bio:value.bio,cityId:value.cityId,districtId:value.districtId,cityName:value.cityName??null,districtName:value.districtName??null,petTypes:copy(value.petTypes),purposes:copy(value.purposes)});return p;},
  async reviewLatest(){const s=scope();if(bound&&!same(bound,s))throw boundary();const latest=await repository.request('profiles.getOwn',{});check(s);if(!latest||!Number.isInteger(latest.revision))throw Object.assign(new Error('Profile unavailable'),{code:'UNAVAILABLE'});pendingLatest={profile:copy(latest),scope:s};return{latest:copy(latest),edited:payload()};},
  acceptLatestRevision(){if(!pendingLatest)throw Object.assign(new Error('Review required'),{code:'INVALID_INPUT'});check(pendingLatest.scope);const old=JSON.parse(original),changes=Object.fromEntries(fields.filter(key=>JSON.stringify(value[key])!==JSON.stringify(old[key])).map(key=>[key,copy(value[key])]));value={...empty(),...pendingLatest.profile};revision=value.revision;original=JSON.stringify(payload());value={...value,...changes};pendingLatest=null;operationId=null;},
  async save(){if(busy)throw Object.assign(new Error('Save pending'),{code:'BUSY'});const s=scope();if(bound&&!same(bound,s))throw boundary();busy=true;operationId??=globalThis.crypto.randomUUID();const input=payload();try{const saved=await repository.request('profiles.saveOwn',input,{baseRevision:revision,operationId});check(s);value={...value,...saved};revision=saved?.revision??revision+1;original=JSON.stringify(payload());operationId=null;return copy(value);}finally{busy=false;}},
  destroy(){value=empty();account={};bound=null;original=JSON.stringify(value);operationId=null;}
 };
}
export function createProfileSaveFlow({editor,getSession,uploadImage}={}){
 let saving=false,disposed=false,fileRef=null,cachedAsset=null;
 return {isSaving:()=>saving,async save({file=null,removeImage=false}={}){if(saving)throw Object.assign(new Error('Save pending'),{code:'BUSY'});if(disposed)throw boundary();const s={...getSession()};saving=true;const valid=()=>{if(disposed||!same(s,getSession()))throw boundary();};try{if(file){if(fileRef!==file){fileRef=file;cachedAsset=null;}if(!cachedAsset){if(!uploadImage)throw Object.assign(new Error('Image unavailable'),{code:'UNAVAILABLE'});cachedAsset=await uploadImage(file,'avatar');}valid();editor.set('avatarAssetId',cachedAsset.assetId??cachedAsset);}else if(removeImage)editor.set('avatarAssetId',null);valid();const profile=await editor.save();valid();fileRef=null;cachedAsset=null;return profile;}finally{saving=false;}},destroy(){disposed=true;fileRef=null;cachedAsset=null;}};
}
const escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function mountProfile({container,repository,getSession,onLogin,onSaved,onError,getLocale=()=> 'zh-CN',mountRegionPicker,uploadImage,resolveImage,onChanged=()=>{}}={}){
 const en=()=>getLocale()==='en',t=(zh,eng)=>en()?eng:zh;
 let destroyed=false,pendingFile=null,pendingAsset=null,previewUrl=null,regionControl=null,removeImage=false,requestSequence=0,phase='loading',localeRefreshPending=false;
 const editor=createProfileEditor({repository,getSession});
 const saveFlow=createProfileSaveFlow({editor,getSession,uploadImage});
 const hiddenPosts=createHiddenPostsController({repository,getSession,onState:()=>{renderHidden();onChanged();}});
 const release=()=>{if(previewUrl){URL.revokeObjectURL(previewUrl);previewUrl=null;}};
 function showError(error){if(destroyed)return;const alert=container.querySelector('[data-profile-error]');if(alert){alert.hidden=false;alert.textContent=t('保存未成功，请检查输入或重试：','Could not save. Check the fields or retry: ')+(error.code??error.message);alert.focus();if(error.code==='CONFLICT'){const button=document.createElement('button');button.type='button';button.className='button secondary';button.textContent=t('核对最新资料','Review latest profile');button.onclick=async()=>{try{button.disabled=true;const review=await editor.reviewLatest();if(destroyed)return;alert.textContent=t('云端最新昵称：','Latest nickname: ')+review.latest.nickname+t('；最新简介：','; latest introduction: ')+review.latest.bio;const accept=document.createElement('button');accept.type='button';accept.className='button secondary';accept.textContent=t('保留我的修改并继续','Keep my edits and continue');accept.onclick=()=>{editor.acceptLatestRevision();render();};alert.append(accept);}catch(next){showError(next);}finally{button.disabled=false;}};alert.append(button);}}onError?.(error);}
 function updatePreview(){const host=container.querySelector('[data-profile-preview]');if(!host)return;const p=editor.preview();host.innerHTML=`<h2>${t('公开预览','Public preview')}</h2><div class="public-identity"><span class="public-avatar">${previewUrl?`<img src="${escape(previewUrl)}" alt="">`:escape((p.nickname||t('我','Me')).slice(0,1))}</span><strong>${escape(p.nickname||t('尚未填写昵称','Add a nickname'))}</strong></div>${editor.values().discoverable?`<p>${escape([p.cityName??p.cityId,p.districtName??p.districtId].filter(Boolean).join(' · '))}</p><p>${escape(p.bio)}</p><p>${escape(p.petTypes.map(x=>x==='cat'?t('猫','Cat'):t('狗','Dog')).join(' · '))} ${escape(p.purposes.map(x=>purposeLabel(x)).join(' · '))}</p>`:`<p class="form-tip">${t('尚未加入发现。发帖和评论会显示昵称与头像。','Discovery is off. Posts and comments display your nickname and avatar.')}</p>`}`;}
 function purposeLabel(p){return en()?({'新手互助':'Beginner help','遛宠搭子':'Walking partners','养猫交流':'Cat care','多宠家庭':'Multi-pet households'}[p]??p):p;}
 function sync(){const form=container.querySelector('form');if(!form)return;for(const name of ['nickname','bio'])editor.set(name,form.elements.namedItem(name).value);editor.set('discoverable',form.elements.namedItem('discoverable').checked);editor.set('petTypes',[...form.querySelectorAll('[name="petTypes"]:checked')].map(x=>x.value));editor.set('purposes',[...form.querySelectorAll('[name="purposes"]:checked')].map(x=>x.value));updatePreview();onChanged();}
 function render(){if(destroyed)return;regionControl?.destroy?.();const v=editor.values();container.innerHTML=`<div class="page-heading"><div><h1>${t('个人资料','Personal profile')}</h1><p>${t('选择你的公开身份，也决定是否让宠友找到你。','Choose your public identity and whether friends can discover you.')}</p></div></div><div class="profile-layout"><section class="panel profile-editor"><form data-profile-form><p class="form-tip">${t('登录邮箱（仅自己可见）：','Sign-in email (only you can see it): ')}<span data-own-email>${escape(editor.account().email||'—')}</span></p><label class="field full"><span>${t('昵称','Nickname')}</span><input name="nickname" maxlength="30" required value="${escape(v.nickname)}" autocomplete="nickname"></label><div class="field full"><span>${t('公开头像','Public avatar')}</span><div class="profile-avatar-controls"><label class="button secondary profile-file-button">${t('选择图片','Choose an image')}<input type="file" name="avatar" accept="image/jpeg,image/png,image/webp"></label><button type="button" class="button text" data-remove-avatar>${t('移除头像','Remove avatar')}</button></div><p class="form-tip">${t('主动选择公开图片，原图最多10MiB。','Choose an image to make public, up to 10MiB before processing.')}</p></div><label class="health-plan-choice full"><input type="checkbox" name="discoverable" ${v.discoverable?'checked':''}><span>${t('加入宠友发现','Join friend discovery')}</span></label><div data-profile-region></div><fieldset class="profile-options"><legend>${t('养宠类别','Pet types')}</legend>${['cat','dog'].map(x=>`<label><input name="petTypes" type="checkbox" value="${x}" ${v.petTypes.includes(x)?'checked':''}>${x==='cat'?t('猫','Cat'):t('狗','Dog')}</label>`).join('')}</fieldset><fieldset class="profile-options"><legend>${t('交流目的','Meet friends for')}</legend>${['新手互助','遛宠搭子','养猫交流','多宠家庭'].map(x=>`<label><input name="purposes" type="checkbox" value="${escape(x)}" ${v.purposes.includes(x)?'checked':''}>${purposeLabel(x)}</label>`).join('')}</fieldset><label class="field full"><span>${t('一句话介绍 · 可选','Short introduction · optional')}</span><textarea name="bio" maxlength="120">${escape(v.bio)}</textarea></label><p class="profile-privacy-note">${t('发帖公开昵称和头像。加入发现后公开所在地、养宠类别、交流目的和简介；退出发现保留已发表内容的作者身份。','Posts make your nickname and avatar public. Discovery also shares your region, pet types, interests and introduction. Leaving discovery keeps the identity on existing posts.')}</p><p data-profile-error class="form-error" role="alert" tabindex="-1" hidden></p><div class="form-actions"><button class="button" type="submit">${t('保存资料','Save profile')}</button></div></form></section><section class="panel profile-preview" data-profile-preview></section></div><section class="panel photo-wall-panel profile-hidden-panel" data-profile-hidden></section>`;
  const regionHost=container.querySelector('[data-profile-region]');if(mountRegionPicker)regionControl=mountRegionPicker({container:regionHost,repository,initialValue:{cityId:v.cityId,districtId:v.districtId,cityName:v.cityName,districtName:v.districtName},getLocale,getGeneration:()=>getSession()?.generation,onChange:r=>{editor.setRegion(r);onChanged();updatePreview();}});else regionHost.innerHTML=`<p class="form-tip">${t('地区选择正在准备；你的已存地区会保留。','Region selection is being prepared; your saved region is retained.')}</p>`;updatePreview();renderHidden();
  if(v.avatarAssetId&&resolveImage&&!previewUrl){const seq=++requestSequence;resolveImage(v.avatarAssetId,{kind:'profile',id:v.authorId}).then(result=>{if(!destroyed&&seq===requestSequence){previewUrl=result.dataUrl??URL.createObjectURL(result.blob??result);updatePreview();}}).catch(()=>{});}
 }
 function hiddenError(error){if(destroyed||error.code==='WORKSPACE_CHANGED'||error.code==='IDENTITY_CHANGED')return;onError?.(error);}
 function renderHidden(){
  if(destroyed)return;const host=container.querySelector('[data-profile-hidden]');if(!host)return;const state=hiddenPosts.getState(),doc=host.ownerDocument;host.replaceChildren();
  const heading=doc.createElement('h2');heading.textContent=t('已隐藏内容','Hidden posts');const description=doc.createElement('p');description.className='form-tip';description.textContent=t('只影响当前账号的社区阅读。恢复后仍按帖子的公开状态显示。','Hiding affects only your account. Restoring follows the post’s current public status.');host.append(heading,description);
  const status=doc.createElement('p');status.setAttribute('role',state.status==='error'?'alert':'status');status.className='form-tip';status.textContent=state.status==='loading'?t('正在读取已隐藏内容…','Loading hidden posts…'):state.status==='error'?t('读取失败，已有内容已保留。请重试。','Could not load hidden posts. Existing rows are kept. Retry.'):!state.items.length?t('你还没有隐藏任何帖子。','You have not hidden any posts.') :'';host.append(status);
  if(state.status==='error'){const retry=doc.createElement('button');retry.type='button';retry.className='button secondary';retry.textContent=t('重新读取隐藏列表','Retry hidden posts');retry.disabled=state.busyIds.length>0;retry.onclick=()=>hiddenPosts.load().catch(hiddenError);host.append(retry);}
  const list=doc.createElement('ul');list.className='profile-hidden-list';for(const row of state.items){const li=doc.createElement('li');li.dataset.hiddenPost=row.postId;const title=doc.createElement('p');title.textContent=row.available?row.title:t('内容已移除或暂时不可见','Post removed or unavailable');li.append(title);if(!row.available){const note=doc.createElement('p');note.className='form-tip';note.textContent=t('移除隐藏标记不会恢复已删除或下架的帖子。','Removing the hidden marker does not restore a deleted or moderated post.');li.append(note);}const restore=doc.createElement('button');restore.type='button';restore.className='button secondary';restore.disabled=state.busyIds.includes(row.postId)||state.status==='loading';restore.textContent=state.busyIds.includes(row.postId)?t('正在恢复…','Restoring…'):row.available?t('恢复显示','Restore visibility'):t('移除隐藏标记','Remove hidden marker');restore.onclick=()=>hiddenPosts.restore(row.postId).catch(hiddenError);li.append(restore);if(state.errors[row.postId]){const alert=doc.createElement('p');alert.setAttribute('role','alert');alert.className='form-error';alert.textContent=t('恢复未成功，标记已保留。请重试。','Could not restore. The hidden marker is kept. Retry.');li.append(alert);}list.append(li);}host.append(list);
  if(state.nextCursor){const more=doc.createElement('button');more.type='button';more.className='button secondary';more.textContent=t('更多已隐藏内容','More hidden posts');more.disabled=state.status==='loading'||state.busyIds.length>0;more.onclick=()=>hiddenPosts.load({more:true}).catch(hiddenError);host.append(more);}
 }
 const input=event=>{if(event.target.matches('[name="avatar"]'))return;sync();};
 const change=event=>{if(!event.target.matches('[name="avatar"]'))return;requestSequence++;pendingFile=event.target.files?.[0]??null;pendingAsset=null;removeImage=false;release();if(pendingFile)previewUrl=URL.createObjectURL(pendingFile);updatePreview();onChanged();};
 const click=event=>{if(event.target.closest('[data-remove-avatar]')){requestSequence++;pendingFile=null;pendingAsset=null;removeImage=true;release();editor.set('avatarAssetId',null);updatePreview();onChanged();}};
 const submit=async event=>{if(!event.target.matches('[data-profile-form]'))return;event.preventDefault();sync();const button=event.target.querySelector('[type="submit"]');if(button.disabled)return;const controls=[...event.target.elements].map(el=>({el,disabled:el.disabled}));for(const {el}of controls)el.disabled=true;button.textContent=t('正在保存…','Saving…');let failure=null;try{const result=await saveFlow.save({file:pendingFile,removeImage});if(destroyed)return;pendingFile=null;pendingAsset=null;removeImage=false;render();onSaved?.(result);}catch(error){failure=error;showError(error);}finally{if(!destroyed){for(const {el,disabled}of controls)el.disabled=disabled;button.textContent=t('保存资料','Save profile');if(localeRefreshPending){localeRefreshPending=false;render();if(failure)showError(failure);}}}};
 container.addEventListener('input',input);container.addEventListener('change',change);container.addEventListener('click',click);container.addEventListener('submit',submit);
 function guest(){container.innerHTML=`<div class="page-heading"><div><h1>${t('个人资料','Personal profile')}</h1><p>${t('登录后设置公开昵称和宠友资料。','Sign in to choose your public identity and friend profile.')}</p></div></div><section class="panel empty-health"><button class="button" data-profile-login>${t('邮箱登录','Sign in with email')}</button></section>`;container.querySelector('[data-profile-login]').onclick=()=>onLogin?.();}
 function failed(){container.innerHTML=`<section class="panel"><p role="alert">${t('暂时无法读取资料，已有内容已保留。','Could not load your profile. Existing content is retained.')}</p><button class="button secondary" data-profile-retry>${t('重试','Retry')}</button></section>`;container.querySelector('[data-profile-retry]').onclick=load;}
 function loading(){container.innerHTML=`<p role="status">${t('正在读取个人资料…','Loading your profile…')}</p>`;}
 function load(){phase='loading';loading();editor.load().then(()=>{if(destroyed)return;phase='ready';render();hiddenPosts.load().catch(hiddenError);}).catch(error=>{if(destroyed)return;phase='error';failed();onError?.(error);});}
 if(!getSession()?.userId){phase='guest';guest();}else load();
 return {hasUnsavedChanges:()=>editor.isDirty()||!!pendingFile||removeImage,isSaving:()=>saveFlow.isSaving()||editor.isBusy()||hiddenPosts.isBusy(),refreshLocale(){if(saveFlow.isSaving()||editor.isBusy()){localeRefreshPending=true;return;}if(phase==='ready')render();else if(phase==='guest')guest();else if(phase==='error')failed();else loading();},destroy(){destroyed=true;requestSequence++;saveFlow.destroy();hiddenPosts.destroy();regionControl?.destroy?.();release();editor.destroy();container.removeEventListener('input',input);container.removeEventListener('change',change);container.removeEventListener('click',click);container.removeEventListener('submit',submit);}};
}
