import {computeRecapFacts,recapSourceHash} from '../domain/recap-facts.js';
import {stage3Text as t,escapeStage3 as esc,stage3Error,refreshStage3Copy} from '../ui/stage3-copy.js';
import {createCommunityRecapDraft} from './recap-community-share.js';
export const todayShanghai=()=>new Date(Date.now()+8*3600000).toISOString().slice(0,10);
const shift=(date,days)=>new Date(Date.parse(date+'T12:00:00Z')+days*86400000).toISOString().slice(0,10);
export function createWeeklyRecap({request,getSnapshot,getRepository,getScope,getLocale,openModal,onChanged,onSource,onCommunityShare}={}){
 let host,key=null,recap=null,busy=false,range='7',from=shift(todayShanghai(),-6),to=todayShanghai(),status='',renderId=0;
 const scopeKey=()=>{const s=getScope();return `${s.generation}:${s.mode}:${s.workspaceId}:${s.petId}`;};
 function setRange(){to=todayShanghai();from=shift(to,range==='30'?-29:-6);}
 async function render(){
   if(!host)return;const thisKey=scopeKey(),turn=++renderId;
   if(key!==thisKey){key=thisKey;recap=null;range='7';setRange();status='';busy=false;}
   const snapshot=getSnapshot(),petId=getScope().petId,saved=(snapshot.profile.stage3?.recaps??[]).filter(r=>r.petId===petId).sort((a,b)=>b.generatedAt.localeCompare(a.generatedAt));
   if(!recap)recap=saved.find(r=>r.from===from&&r.to===to)??null;
   const facts=computeRecapFacts({snapshot,petId,from,to});
   let stale=false;if(recap)stale=recap.sourceHash!==await recapSourceHash({snapshot,petId,from:recap.from,to:recap.to});
   if(turn!==renderId||key!==scopeKey()||!host?.isConnected)return;
   const alreadySaved=recap&&saved.some(r=>r.id===recap.id);
   host.innerHTML=`<p class="demo-note">${esc(t('recapDesc'))}</p><div class="recap-range"><label><span>${esc(t('range'))}</span><select data-recap-range ${busy?'disabled':''}><option value="7" ${range==='7'?'selected':''}>${esc(t('seven'))}</option><option value="30" ${range==='30'?'selected':''}>${esc(t('thirty'))}</option><option value="custom" ${range==='custom'?'selected':''}>${esc(t('custom'))}</option></select></label><label><span>${esc(t('from'))}</span><input type="date" data-recap-from ${busy?'disabled':''} value="${from}" max="${todayShanghai()}"></label><label><span>${esc(t('to'))}</span><input type="date" data-recap-to ${busy?'disabled':''} value="${to}" max="${todayShanghai()}"></label></div><div class="recap-facts"><span>${esc(t('recordCount',{count:facts.recordCount}))}</span><span>${esc(facts.weightChangeKg===null?t('noWeightChange'):t('weightChange',{value:facts.weightChangeKg}))}</span><span>${esc(t('careCount',{count:facts.completedCareCount}))}</span></div>${getScope().mode==='demo'?`<p class="demo-note">${esc(t('demoRecap'))}</p>`:''}<p class="form-tip">${esc(t('recapConsent'))}</p>${facts.recordCount>20?`<p class="demo-note">${esc(t('sourcesLimited'))}</p>`:''}${recap?`<article class="recap-story"><p>${esc(recap.story)}</p><small>${esc(t('generated',{time:new Date(recap.generatedAt).toLocaleString(getLocale()==='en'?'en-GB':'zh-CN',{timeZone:'Asia/Shanghai'})}))}</small>${stale?`<p class="form-tip" data-recap-stale>${esc(t('stale'))}</p>`:''}<details><summary>${esc(t('basis'))}</summary><ul>${[...recap.recordIds,...recap.reminderIds].map(id=>{const source=snapshot.records.find(r=>r.id===id&&r.deletedAt===null)||snapshot.reminders.find(r=>r.id===id&&r.deletedAt===null);return source?`<li><button class="text-button" data-recap-source="${esc(id)}">${esc(source.occurredDate||source.dueDate)} · ${esc(source.title)}</button></li>`:'';}).join('')}</ul></details></article>`:!facts.recordCount?`<p class="empty-state">${esc(t('noRecords'))}</p>`:''}<p class="demo-note" role="status" data-recap-status>${esc(status)}</p><div class="recap-actions"><button type="button" class="button secondary" data-recap-generate ${busy||!facts.recordCount?'disabled':''}>${esc(t(busy?'loading':recap?'regenerate':'generate'))}</button>${recap?`<button type="button" class="text-button" data-recap-save ${busy||stale||alreadySaved?'disabled':''}>${esc(t(alreadySaved?'recapSaved':'saveRecap'))}</button><button type="button" class="text-button" data-recap-share>${esc(t('share'))}</button>`:''}</div>${saved.length?`<label class="field recap-history"><span>${esc(t('history'))}</span><select data-recap-history ${busy?'disabled':''}><option value="">—</option>${saved.map(r=>`<option value="${esc(r.id)}">${r.from} — ${r.to}</option>`).join('')}</select></label>`:''}`;
   host.querySelector('[data-recap-range]').onchange=e=>{if(busy)return;range=e.target.value;if(range!=='custom')setRange();recap=null;status='';render();};
   for(const name of ['from','to'])host.querySelector('[data-recap-'+name+']').onchange=e=>{if(busy)return;if(name==='from')from=e.target.value;else to=e.target.value;range='custom';recap=null;status='';if(!from||!to||from>to||to>todayShanghai()){status=t('invalid');host.querySelector('[data-recap-status]').textContent=status;return;}render();};
   host.querySelector('[data-recap-generate]').onclick=async()=>{if(busy||!from||!to||from>to)return;busy=true;for(const c of host.querySelectorAll('[data-recap-range],[data-recap-from],[data-recap-to],[data-recap-history]'))c.disabled=true;status='';render();const origin=key;try{const result=await request('ai.recaps.generate',{petId,from,to,uiLocale:getLocale()});if(origin!==scopeKey())return;recap=result.recap??null;status=result.empty?t('noRecords'):'';}catch(error){if(origin===scopeKey())status=stage3Error(error);}finally{if(origin===scopeKey()){busy=false;render();}}};
   const saveButton=host.querySelector('[data-recap-save]');if(saveButton)saveButton.onclick=async()=>{if(busy)return;busy=true;for(const c of host.querySelectorAll('[data-recap-range],[data-recap-from],[data-recap-to],[data-recap-history]'))c.disabled=true;saveButton.disabled=true;const origin=key,repo=getRepository(),savedRecap=recap;try{await repo.saveRecap(savedRecap,{baseRevision:repo.getRevision?.(),operationId:'recap-'+savedRecap.id});if(origin!==scopeKey())return;status=t('recapSaved');await onChanged();}catch(error){if(origin===scopeKey())status=stage3Error(error);}finally{if(origin===scopeKey()){busy=false;render();}}};
   for(const button of host.querySelectorAll('[data-recap-source]'))button.onclick=()=>onSource({kind:snapshot.records.some(r=>r.id===button.dataset.recapSource)?'record':'reminder',id:button.dataset.recapSource});
   const history=host.querySelector('[data-recap-history]');if(history)history.onchange=e=>{if(busy)return;const selected=saved.find(r=>r.id===e.target.value);if(selected){recap=selected;from=selected.from;to=selected.to;range='custom';render();}};
   const share=host.querySelector('[data-recap-share]');if(share)share.onclick=()=>{const shareScope=scopeKey(),preview=createCommunityRecapDraft({snapshot:getSnapshot(),petId:getScope().petId,from:recap.from,to:recap.to,locale:getLocale()});if(!openModal(t('share'),`<form id="recap-share-form" data-readonly-ai><p class="form-tip" data-s3-key="shareHint">${esc(t('shareHint'))}</p><label class="field"><span data-s3-key="share">${esc(t('share'))}</span><textarea id="recap-share-text" rows="7">${esc(preview.title+'\n'+preview.text)}</textarea></label><p role="status" id="recap-copy-status"></p><div class="form-actions"><button class="button secondary" type="button" data-action="close" data-s3-key="cancel">${esc(t('cancel'))}</button><button class="button" type="button" id="recap-copy" data-s3-key="copy">${esc(t('copy'))}</button></div></form>`))return;if(onCommunityShare&&getScope().mode!=='demo'){const publish=document.createElement('button');publish.type='button';publish.dataset.recapCommunityPublish='';publish.className='button secondary';publish.textContent=getLocale()==='en'?'Publish to community':'\u53d1\u5e03\u5230\u793e\u533a';publish.onclick=()=>{if(shareScope!==scopeKey())return;const draft=createCommunityRecapDraft({snapshot:getSnapshot(),petId:getScope().petId,from:recap.from,to:recap.to,locale:getLocale(),editedText:document.querySelector('#recap-share-text').value});onCommunityShare(draft);};document.querySelector('#recap-share-form .form-actions').append(publish);}document.querySelector('#recap-share-form').__pawLocaleRefresh=()=>{refreshStage3Copy(document.querySelector('#recap-share-form'));document.querySelector('#dialog-title').textContent=t('share');const publishButton=document.querySelector('[data-recap-community-publish]');if(publishButton)publishButton.textContent=getLocale()==='en'?'Publish to community':'发布到社区';};document.querySelector('#recap-copy').onclick=async()=>{const field=document.querySelector('#recap-share-text');try{await navigator.clipboard.writeText(field.value);document.querySelector('#recap-copy-status').textContent=t('copied');}catch{field.select();}};};
 }
 return {mount(target){host=target;render().catch(error=>{if(host?.isConnected)host.textContent=stage3Error(error);});},refresh:render};
}
