import os
from playwright.sync_api import sync_playwright
BASE=os.environ.get('PAW_DIARY_TEST_URL','http://127.0.0.1:4193/paw-diary/')
with sync_playwright() as p:
    browser=p.chromium.launch(headless=True,executable_path='/Applications/Google Chrome.app/Contents/MacOS/Google Chrome')
    context=browser.new_context(viewport={'width':390,'height':844})
    page=context.new_page(); errors=[]; page.on('pageerror',lambda e:errors.append(str(e)))
    page.goto(BASE); page.wait_for_load_state('networkidle')
    page.get_by_role('button',name='开始记录我的宠物',exact=True).wait_for(timeout=5000)
    original=page.evaluate("localStorage.getItem('paw-diary:v3:demo')")
    page.get_by_role('button',name='开始记录我的宠物',exact=True).click()
    page.get_by_role('dialog').wait_for()
    page.locator('#pet-form [name=name]').fill('健康档案')
    page.locator('#pet-form [name=type]').select_option('other')
    page.locator('#pet-form [name=typeLabel]').fill('兔子')
    page.locator('#pet-form [name=estimatedAgeMonths]').fill('12')
    page.locator('#pet-form button[type=submit]').click()
    page.wait_for_function("!document.querySelector('#dialog').open")
    page.reload();page.wait_for_load_state('networkidle')
    assert page.get_by_role('heading',name='你好呀，健康档案。').is_visible()
    page.get_by_role('button',name='记一笔',exact=True).click()
    page.locator('#record-form [name=type]').select_option('other')
    page.locator('#record-form [name=typeLabel]').fill('剪指甲')
    page.locator('#record-form [name=title]').fill('第一次护理')
    page.locator('#record-form [name=note]').fill('健康档案')
    page.locator('#dialog-locale-select').select_option('en')
    assert page.locator('#record-form [name=note]').input_value()=='健康档案'
    assert page.locator('#record-form [name=typeLabel]').input_value()=='剪指甲'
    page.locator('#record-form button[type=submit]').click()
    page.wait_for_function("!document.querySelector('#dialog').open")
    assert '健康档案' in page.locator('#main').inner_text()
    assert page.evaluate("localStorage.getItem('paw-diary:v3:demo')")==original
    context.set_offline(True)
    page.locator('[data-action=record]').first.click()
    page.locator('#record-form [name=type]').select_option('daily')
    page.locator('#record-form [name=title]').fill('离线小事')
    page.locator('#record-form button[type=submit]').click()
    page.wait_for_function("!document.querySelector('#dialog').open")
    context.set_offline(False)
    page.reload();page.wait_for_load_state('networkidle')
    assert '离线小事' in page.locator('#main').inner_text()
    assert not errors,errors
    print('PASS 未登录个人档案/其他类型/刷新/双语草稿/离线本地写入与旧demo隔离')
    browser.close()
