"""Decoded local avatar preview beside its picker, without publication before save."""
import argparse,json
from pathlib import Path
from playwright.sync_api import sync_playwright
ROOT=Path(__file__).resolve().parents[2]
p=argparse.ArgumentParser();p.add_argument('--url',default='http://127.0.0.1:4202');p.add_argument('--label',default='green');a=p.parse_args();OUT=ROOT/'test-results/v104/avatar-preview'/a.label;OUT.mkdir(parents=True,exist_ok=True)
FIXTURE='''<!doctype html><meta charset="utf-8"><link rel="stylesheet" href="/style.css"><main><div id="fixture"></div></main><script type="module">
import {mountProfile} from '/src/features/profile.js';
const canvas=document.createElement('canvas');canvas.width=1280;canvas.height=960;const ctx=canvas.getContext('2d'),pixels=ctx.createImageData(1280,960);let seed=123456;for(let i=0;i<pixels.data.length;i+=4){seed=(Math.imul(seed,1664525)+1013904223)>>>0;pixels.data[i]=seed&255;pixels.data[i+1]=(seed>>>8)&255;pixels.data[i+2]=(seed>>>16)&255;pixels.data[i+3]=255;}ctx.putImageData(pixels,0,0);window.png=canvas.toDataURL('image/png');window.jpg=canvas.toDataURL('image/jpeg');window.saved=[];window.uploads=0;window.reads=0;window.language='zh-CN';window.fail=true;
const own={nickname:'合成头像测试',bio:'',cityId:null,districtId:null,petTypes:[],purposes:[],discoverable:false,avatarAssetId:'old-avatar',authorId:'synthetic-author',revision:1};
const repository={request:async(action,payload)=>{if(action==='profiles.getOwn')return structuredClone(own);if(action==='auth.getOwn')return{};if(action==='community.hidden.list')return{items:[]};if(action==='profiles.saveOwn'){window.saved.push(payload);if(window.fail)throw{code:'UNAVAILABLE'};return{...payload,authorId:own.authorId,revision:2};}throw{code:'INVALID_INPUT'};}};
window.profile=mountProfile({container:document.querySelector('#fixture'),repository,getSession:()=>({userId:'synthetic-owner',generation:1}),getLocale:()=>window.language,uploadImage:async file=>{window.uploads++;await new Promise(r=>window.finishUpload=r);return{assetId:'new-avatar'};},resolveImage:async()=>{window.reads++;return await new Promise(r=>window.finishRead=()=>r({dataUrl:window.jpg}));}});window.ready=true;
</script>'''
(OUT/'fixture.html').write_text(FIXTURE);reports=[]
with sync_playwright() as p:
 b=p.chromium.launch(channel='chrome',headless=False)
 for width in [1440,390]:
  page=b.new_page(viewport={'width':width,'height':1000});page.set_default_timeout(5000);errors=[];page.on('pageerror',lambda e:errors.append(str(e)));page.goto(a.url+'/test-results/v104/avatar-preview/'+a.label+'/fixture.html');page.locator('[name="avatar"]').wait_for(state='attached')
  page.locator('.profile-file-button').scroll_into_view_if_needed();assert page.locator('[data-profile-inline-avatar]').count()==1,'Missing avatar preview next to image picker'
  png=page.evaluate('png');import base64
  data=base64.b64decode(png.split(',')[1]);page.evaluate('window.chosenAt=performance.now()');page.locator('[name="avatar"]').set_input_files({'name':'valid-1280.png','mimeType':'image/png','buffer':data});page.wait_for_function("document.querySelector('[data-profile-inline-avatar] img')?.naturalWidth===1280")
  elapsed=page.evaluate('performance.now()-chosenAt');rect=page.locator('[data-profile-inline-avatar] img').bounding_box();assert rect['y']>=0 and rect['y']+rect['height']<=1000,'Selected avatar is outside picker viewport';assert elapsed<2000,elapsed;assert page.evaluate('uploads===0 && saved.length===0 && reads===1'),'Local choice published or uploaded before save'
  local=page.locator('[data-profile-inline-avatar] img').get_attribute('src');page.evaluate('finishRead()');page.wait_for_timeout(80);assert page.locator('[data-profile-inline-avatar] img').get_attribute('src')==local,'Late existing-avatar read overwrote local choice'
  page.evaluate("language='en';profile.refreshLocale()");assert page.locator('[data-profile-inline-avatar] img').get_attribute('src')==local;assert 'save' in page.locator('[data-profile-avatar-status]').inner_text().lower()
  page.get_by_role('button',name='Save profile',exact=True).click();page.wait_for_function('uploads===1');assert page.locator('[data-profile-inline-avatar] img').get_attribute('src')==local;assert 'saving' in page.locator('[data-profile-avatar-status]').inner_text().lower();page.evaluate('finishUpload()');page.locator('[data-profile-error]').wait_for(state='visible');assert page.locator('[data-profile-inline-avatar] img').get_attribute('src')==local
  page.evaluate('fail=false');page.get_by_role('button',name='Save profile',exact=True).click();page.wait_for_function('saved.length===2');assert page.evaluate('uploads===1'),'Retry duplicated image upload';assert page.locator('[data-profile-inline-avatar] img').get_attribute('src')==local
  jpg=base64.b64decode(page.evaluate('jpg').split(',')[1]);page.locator('[name="avatar"]').set_input_files({'name':'valid-1280.jpg','mimeType':'image/jpeg','buffer':jpg});page.wait_for_function("document.querySelector('[data-profile-inline-avatar] img')?.naturalWidth===1280");assert page.locator('[data-profile-inline-avatar] img').get_attribute('src')!=local
  page.get_by_role('button',name='Remove avatar',exact=True).click();assert page.locator('[data-profile-inline-avatar] img').count()==0
  page.locator('[name="avatar"]').set_input_files({'name':'broken.png','mimeType':'image/png','buffer':b'not an image'});page.locator('[data-profile-avatar-error]').wait_for(state='visible');assert 'image' in page.locator('[data-profile-avatar-error]').inner_text().lower();assert page.locator('[data-profile-inline-avatar] img').count()==0;page.get_by_role('button',name='Save profile',exact=True).click();assert page.evaluate('saved.length===2 && uploads===1');assert 'image' in page.locator('[data-profile-error]').inner_text().lower();page.locator('[name="avatar"]').set_input_files({'name':'recovered.jpg','mimeType':'image/jpeg','buffer':jpg});page.wait_for_function("document.querySelector('[data-profile-inline-avatar] img')?.naturalWidth===1280");assert not page.locator('[data-profile-avatar-error]').is_visible();assert not page.locator('[data-profile-error]').is_visible()
  assert not errors,errors;page.screenshot(path=str(OUT/f'preview-{width}.png'));reports.append({'width':width,'pngBytes':len(data),'jpegBytes':len(jpg),'pngChoiceToDecodeMs':elapsed,'inlinePreviewInViewport':True,'localNoPublication':True,'heldUploadVisible':True,'failureAndRetryKeepFile':True,'swapRemoveLocaleAndLateRead':True,'invalidImageSpecificError':True,'pageErrors':errors});page.evaluate('profile.destroy()');page.close()
 b.close()
(OUT/'report.json').write_text(json.dumps(reports,ensure_ascii=False,indent=2));print(json.dumps(reports))
