"""Real local UI with real configured free model; only synthetic pet data."""
import os,json
from pathlib import Path
from playwright.sync_api import sync_playwright,expect
BASE=os.environ.get('PAW_DIARY_TEST_URL','http://127.0.0.1:4199/')
OUT=Path(__file__).resolve().parents[2]/'test-results/stage3/flow'
OUT.mkdir(parents=True,exist_ok=True)
with sync_playwright() as p:
    browser=p.chromium.launch(channel='chrome',headless=os.environ.get('PAW_HEADFUL')!='1')
    page=browser.new_page(viewport={'width':390,'height':844});errors=[]
    page.on('pageerror',lambda e:errors.append(str(e)))
    page.goto(BASE+'#home',wait_until='networkidle')
    expect(page.locator('[data-recap-range]').locator('..').locator('.select-trigger')).to_be_visible()
    page.locator('[data-action=workspace-local]').first.click()
    expect(page.locator('#pet-form')).to_be_visible()
    page.locator('#pet-form [name=name]').fill('阶段3合成验收猫')
    page.locator('#pet-type').locator('..').locator('.select-trigger').click()
    page.locator('#pet-type').locator('..').get_by_role('option',name='猫咪',exact=True).click()
    page.locator('#pet-form [name=estimatedAgeMonths]').fill('12')
    page.locator('#pet-form [type=submit]').click()
    expect(page.locator('#dialog')).not_to_be_visible()
    expect(page.locator('[data-home-onboarding]')).to_contain_text('记第一笔')
    page.reload(wait_until='networkidle')
    expect(page.locator('[data-home-onboarding]')).to_contain_text('记第一笔')
    page.locator('[data-action=record]').first.click()
    page.locator('[data-action=record-mode][data-value=ai]').click()
    page.locator('#ai-text').fill('昨天称重4.6公斤，今天做了驱虫。')
    page.locator('#ai-parse').click()
    expect(page.locator('.ai-draft')).to_have_count(2,timeout=40000)
    page.locator('.ai-draft [name=title]').last.fill('合成驱虫记录')
    page.locator('#ai-confirm').click()
    expect(page.locator('#dialog')).not_to_be_visible(timeout=15000)
    expect(page.locator('[data-home-onboarding]')).to_contain_text('设提醒')
    page.locator('[data-s3-skip]').click()
    expect(page.locator('[data-home-onboarding]')).not_to_be_visible()
    page.reload(wait_until='networkidle')
    expect(page.locator('[data-home-onboarding]')).not_to_be_visible()
    expect(page.locator('[data-recap-from]')).to_be_visible()
    page.locator('[data-recap-generate]').click()
    expect(page.locator('.recap-story')).to_be_visible(timeout=40000)
    page.locator('[data-recap-save]').click()
    expect(page.locator('[data-recap-save]')).to_contain_text('已私有保存',timeout=15000)
    page.reload(wait_until='networkidle')
    expect(page.locator('.recap-story')).to_be_visible()
    page.locator('[data-recap-share]').click()
    share=page.locator('#recap-share-text').input_value()
    assert '4.6' not in share and '驱虫' not in share
    page.locator('#dialog [data-action=close]').click()
    page.screenshot(path=str(OUT/'390-flow.png'),full_page=True)
    page.locator('#stage3-assistant-launcher').click()
    expect(page.locator('#assistant-form')).to_be_visible()
    page.locator('#assistant-question').fill('最近做了什么驱虫？')
    page.locator('#assistant-ask').click()
    expect(page.locator('.assistant-message').last).to_contain_text('驱虫',timeout=40000)
    expect(page.locator('.assistant-sources button').first).to_be_visible()
    page.screenshot(path=str(OUT/'390-assistant.png'),full_page=True)
    page.locator('#dialog [data-action=close]').click()
    page.goto(BASE+'#health',wait_until='networkidle')
    assert '合成驱虫记录' in page.locator('#main').inner_text()
    assert not errors,errors
    print('PASS: real free AI drafts, local confirmation, onboarding resume, private recap reload/share and sourced assistant')
    browser.close()
