import test from 'node:test';
import assert from 'node:assert/strict';
import {IDBFactory} from 'fake-indexeddb';
import {createLocalRepository} from '../src/data/local-repository.js';
import {createAttachmentRepository,inspectAttachmentBlob} from '../src/media/attachments.js';
const pdf=()=>new Blob(['%PDF-1.4\noriginal file\n%%EOF'],{type:'application/pdf'});
async function setup(){const repo=createLocalRepository({indexedDB:new IDBFactory()});const pet=await repo.savePet({name:'附件测试',type:'cat'});const record=await repo.saveRecord({petId:pet.id,type:'daily',occurredDate:'2026-10-07',title:'日常'});return {repo,pet,record,files:createAttachmentRepository({repository:repo})};}
test('PDF original bytes, retry receipt, three-file cap, gallery isolation and parent lifecycle',async()=>{const {repo,pet,record,files}=await setup();const input={petId:pet.id,parentKind:'record',parentId:record.id,filename:'健康报告.pdf',blob:pdf(),operationId:'same-upload'};const one=await files.save(input);assert.equal((await files.save(input)).id,one.id);assert.equal(await (await files.read(one.id)).blob.text(),await pdf().text());assert.equal((await repo.media.list({petId:pet.id})).items.length,0);await files.save({...input,operationId:'two'});await files.save({...input,operationId:'three'});await assert.rejects(files.save({...input,operationId:'four'}),/三个|3|上限/);await repo.moveToTrash({kind:'record',ids:[record.id]});await assert.rejects(files.read(one.id));assert.equal((await files.list({petId:pet.id,parentKind:'record',parentId:record.id})).items.length,0);assert.equal(await (await files.read(one.id,{includeDeleted:true})).blob.text(),await pdf().text());await repo.restoreFromTrash({kind:'record',ids:[record.id]});assert.equal((await files.list({petId:pet.id,parentKind:'record',parentId:record.id})).items.length,3);});
test('wrong parent pet and disguised/oversize files rejected without mutation',async()=>{const {repo,pet,record,files}=await setup(),other=await repo.savePet({name:'另一个',type:'dog'}),revision=repo.getRevision();await assert.rejects(files.save({petId:other.id,parentKind:'record',parentId:record.id,blob:pdf(),filename:'a.pdf'}));await assert.rejects(inspectAttachmentBlob(new Blob(['<html>bad</html>'],{type:'application/pdf'})));await assert.rejects(inspectAttachmentBlob(new Blob(['%PDF-',new Uint8Array(5*1024*1024)],{type:'application/pdf'})));assert.equal(repo.getRevision(),revision);});
test('complete archive v2 retains original attachment and rebinds its parent across workspaces',async()=>{const {repo,pet,record,files}=await setup();await files.save({petId:pet.id,parentKind:'record',parentId:record.id,blob:pdf(),filename:'原件.pdf'});const archive=await repo.exportArchive();assert.equal(archive.formatVersion,2);const target=createLocalRepository({indexedDB:new IDBFactory()}),preview=await target.previewArchiveImport(archive);await target.commitArchiveImport(preview);const item=(await target.media.listAll())[0],state=await target.snapshot();assert.equal(item.parentId,state.records[0].id);assert.equal(item.petId,state.pets[0].id);assert.equal(await (await target.media.read(item.id)).blob.text(),await pdf().text());});
test('custom catalog and icon snapshots round trip with stable remapped IDs; incompatible fourth type is rejected',async()=>{const {repo,pet}=await setup();const catalog=await repo.manageRecordTypes({action:'add',name:'合成类型',iconKey:'paw'}),type=catalog.custom[0];await repo.saveRecord({petId:pet.id,type:'other',typeLabel:type.name,customTypeId:type.id,iconKey:type.iconKey,occurredDate:'2026-10-07',title:'合成记录'});const archive=await repo.exportArchive();assert.equal(archive.snapshot.profile.recordTypeCatalog.custom[0].name,'合成类型');const target=createLocalRepository({indexedDB:new IDBFactory()});const preview=await target.previewArchiveImport(archive);await target.commitArchiveImport(preview);const state=await target.snapshot(),r=state.records.find(x=>x.type==='other');assert.equal(r.customTypeId,state.profile.recordTypeCatalog.custom[0].id);assert.equal(r.iconKey,'paw');assert.notEqual(r.customTypeId,type.id);const full=createLocalRepository({indexedDB:new IDBFactory()});for(let i=0;i<3;i++)await full.manageRecordTypes({action:'add',name:'现有'+i,iconKey:'book'});const before=await full.snapshot();await assert.rejects(full.previewArchiveImport(archive),/3|类型/);assert.deepEqual(await full.snapshot(),before);});
