import test from 'node:test';
import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {createHash} from 'node:crypto';
const require=createRequire(import.meta.url);
let api={};try{api=require('../backend/community/media.cjs');}catch(e){if(e.code!=='MODULE_NOT_FOUND')throw e;}
const png=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+ip1sAAAAASUVORK5CYII=','base64');
const sha=bytes=>createHash('sha256').update(bytes).digest('hex');
const owner=uid=>createHash('sha256').update('paw-community-owner:'+uid).digest('hex');
function fixture(){
 assert.equal(typeof api.createCommunityMediaService,'function','public media upload service must exist');
 const docs=new Map(),objects=new Map();let serial=0,time=100000;
 const tx={get:async(k,id)=>structuredClone(docs.get(k+':'+id)),put:async(k,id,v)=>docs.set(k+':'+id,structuredClone(v)),remove:async(k,id)=>docs.delete(k+':'+id),findProfileByAuthorId:async id=>structuredClone(docs.get('profiles:'+id))};
 let queue=Promise.resolve();const store={transaction:fn=>{const p=queue.then(async()=>{const before=structuredClone(docs);try{return await fn(tx);}catch(e){docs.clear();for(const [k,v]of before)docs.set(k,v);throw e;}});queue=p.catch(()=>{});return p;}};
 const storage={prepare:async path=>({fileRef:path,upload:{url:'https://uploads.test/'+path,method:'PUT',headers:{}}}),read:async ref=>{const b=objects.get(ref);if(!b)throw Error('missing object');return b;},remove:async ref=>objects.delete(ref)};
 const fetch=async(url,options)=>{objects.set(url.slice('https://uploads.test/'.length),Buffer.from(options.body));return {ok:true};};
 const service=api.createCommunityMediaService({store,storage,fetch,ownerIdFor:owner,clock:()=>time,idFactory:()=>`id-${++serial}`});
 const a={userId:'A'},b={userId:'B'},input={kind:'post',mime:'image/png',bytes:png.length,sha256:sha(png),width:1,height:1};
 const call=(action,p={},principal=a)=>service.handle(action,p,{principal});
 const upload=async(kind='post')=>{const ticket=await call('community.media.prepare',{...input,kind});return call('community.media.confirm',{ticketId:ticket.ticketId,bytesBase64:png.toString('base64')});};
 return {docs,objects,storage,fetch,tx,store,service,call,upload,a,b,input,advance:n=>time+=n};
}
const rejectCode=(promise,code)=>assert.rejects(promise,e=>e.code===code);
test('draft media is owner only and private IDs cannot be bound',async()=>{const f=fixture(),{assetId}=await f.upload();await rejectCode(f.call('community.media.read',{assetId},null),'FORBIDDEN');await rejectCode(f.call('community.media.read',{assetId},f.b),'FORBIDDEN');assert.equal((await f.call('community.media.read',{assetId})).sha256,sha(png));await rejectCode(f.store.transaction(tx=>api.bindCommunityAsset(tx,{assetId:'cloud://private',ownerId:owner('A'),targetKind:'post',targetId:'p',now:100000})),'FORBIDDEN');await rejectCode(f.store.transaction(tx=>api.bindCommunityAsset(tx,{assetId,ownerId:owner('B'),targetKind:'post',targetId:'p',now:100000})),'FORBIDDEN');});
test('published post bytes match hash and deletion revokes anonymous new reads',async()=>{const f=fixture(),{assetId}=await f.upload();await f.store.transaction(async tx=>{await tx.put('posts','p',{id:'p',deletedAt:null,moderationStatus:'visible',ownerId:owner('A'),authorId:'author-a',imageAssetId:assetId});await api.bindCommunityAsset(tx,{assetId,ownerId:owner('A'),targetKind:'post',targetId:'p',now:100000});});const r=await f.call('community.media.read',{assetId,reference:{kind:'post',id:'p'}},null);assert.deepEqual(Buffer.from(r.dataUrl.split(',')[1],'base64'),png);assert.equal(r.sha256,sha(png));await rejectCode(f.call('community.media.read',{assetId},null),'FORBIDDEN');await f.tx.put('posts','p',{id:'p',deletedAt:'2026-10-07T00:00:00Z',moderationStatus:'visible',imageAssetId:assetId});await rejectCode(f.call('community.media.read',{assetId,reference:{kind:'post',id:'p'}},null),'FORBIDDEN');});
test('non-discoverable current avatar remains readable via valid post/comment only',async()=>{const f=fixture(),{assetId}=await f.upload('avatar');await f.store.transaction(async tx=>{await tx.put('profiles','author-a',{authorId:'author-a',ownerId:owner('A'),avatarAssetId:assetId,discoverable:false});await tx.put('posts','p',{id:'p',authorId:'author-a',deletedAt:null,moderationStatus:'visible'});await tx.put('comments','c',{id:'c',authorId:'author-a',postId:'p',deletedAt:null,moderationStatus:'visible'});await api.bindCommunityAsset(tx,{assetId,ownerId:owner('A'),targetKind:'profile',targetId:'author-a',now:100000});});await rejectCode(f.call('community.media.read',{assetId,reference:{kind:'profile',id:'author-a'}},null),'FORBIDDEN');assert.equal((await f.call('community.media.read',{assetId,reference:{kind:'post',id:'p'}},null)).sha256,sha(png));assert.equal((await f.call('community.media.read',{assetId,reference:{kind:'comment',id:'c'}},null)).sha256,sha(png));await f.tx.put('posts','p',{deletedAt:null,moderationStatus:'hidden',authorId:'author-a'});await rejectCode(f.call('community.media.read',{assetId,reference:{kind:'comment',id:'c'}},null),'FORBIDDEN');});
test('one use binding prevents reuse after unbinding and owner remove cannot break live parents',async()=>{const f=fixture(),{assetId}=await f.upload();await f.store.transaction(tx=>api.bindCommunityAsset(tx,{assetId,ownerId:owner('A'),targetKind:'post',targetId:'p',now:100000}));await rejectCode(f.call('community.media.remove',{assetId}),'CONFLICT');await f.store.transaction(tx=>api.unbindCommunityAsset(tx,{assetId,targetKind:'post',targetId:'p',now:100000}));await rejectCode(f.store.transaction(tx=>api.bindCommunityAsset(tx,{assetId,ownerId:owner('A'),targetKind:'post',targetId:'new',now:100000})),'FORBIDDEN');await f.call('community.media.remove',{assetId});assert.equal(f.objects.size,0);});
test('prepare/confirm/remove require a principal and foreign tickets reject',async()=>{const f=fixture();await rejectCode(f.call('community.media.prepare',f.input,null),'UNAUTHENTICATED');const {ticketId}=await f.call('community.media.prepare',f.input);await rejectCode(f.call('community.media.confirm',{ticketId,bytesBase64:png.toString('base64')},f.b),'FORBIDDEN');await rejectCode(f.call('community.media.remove',{assetId:ticketId},null),'UNAUTHENTICATED');});
test('actual MIME hash dimensions and strict base64 are checked before uploading',async()=>{for(const patch of [{mime:'image/jpeg'},{sha256:'0'.repeat(64)},{width:2},{height:2}]){const f=fixture(),{ticketId}=await f.call('community.media.prepare',{...f.input,...patch});await rejectCode(f.call('community.media.confirm',{ticketId,bytesBase64:png.toString('base64')}),'INVALID_INPUT');assert.equal(f.objects.size,0);}const f=fixture(),{ticketId}=await f.call('community.media.prepare',f.input);await rejectCode(f.call('community.media.confirm',{ticketId,bytesBase64:'!!!!'}),'INVALID_INPUT');});
test('1MiB and 20 pending ticket boundaries are enforced',async()=>{const f=fixture();await rejectCode(f.call('community.media.prepare',{...f.input,bytes:1048577}),'INVALID_INPUT');await f.call('community.media.prepare',{...f.input,bytes:1048576});for(let i=1;i<20;i++)await f.call('community.media.prepare',f.input);await rejectCode(f.call('community.media.prepare',f.input),'QUOTA_EXCEEDED');});
test('expired ticket cannot confirm and cleanup removes only expired unbound assets',async()=>{const f=fixture(),{ticketId}=await f.call('community.media.prepare',f.input),draft=await f.upload(),live=await f.upload();await f.store.transaction(tx=>api.bindCommunityAsset(tx,{assetId:live.assetId,ownerId:owner('A'),targetKind:'post',targetId:'p',now:100000}));f.advance(86400001);await rejectCode(f.call('community.media.confirm',{ticketId,bytesBase64:png.toString('base64')}),'INVALID_INPUT');const result=await f.service.cleanupCandidates([ticketId,draft.assetId,live.assetId]);assert.equal(result.removed.length,2);assert.equal(f.objects.size,1);assert.ok(await f.tx.get('media',live.assetId));});
test('50MiB aggregate reservations reject excess',async()=>{const f=fixture();await f.tx.put('media','quota:'+owner('A'),{kind:'quota',ownerId:owner('A'),bytes:50*1048576-1,pending:{}});await rejectCode(f.call('community.media.prepare',f.input),'QUOTA_EXCEEDED');});

let client={};try{client=await import('../src/media/community-images.js');}catch(e){if(e.code!=='ERR_MODULE_NOT_FOUND')throw e;}
test('image loader limits concurrency to three and coalesces identical reference requests',async()=>{
 assert.equal(typeof client.createCommunityImageLoader,'function','lazy public image loader must exist');let running=0,peak=0,calls=0;const waiting=[];
 const loader=client.createCommunityImageLoader({read:async()=>{calls++;running++;peak=Math.max(peak,running);await new Promise(resolve=>waiting.push(resolve));running--;return {dataUrl:'data:image/png;base64,'+png.toString('base64'),sha256:sha(png)};}});
 const first=loader.load('a',{kind:'post',id:'p'}),same=loader.load('a',{kind:'post',id:'p'});const rest=['b','c','d','e'].map(id=>loader.load(id,{kind:'post',id:'p'}));
 await new Promise(r=>setImmediate(r));assert.equal(calls,3);assert.equal(first,same);let settled=0;for(const p of [first,...rest])p.then(()=>settled++);for(let cycle=0;settled<5&&cycle<1000;cycle++){waiting.splice(0).forEach(r=>r());await new Promise(r=>setTimeout(r,1));}assert.equal(settled,5,'all queued requests must settle');await Promise.all([first,same,...rest]);assert.equal(peak,3);assert.equal(calls,5);
});
test('image loader rejects stale account results after reset and mismatched byte hashes',async()=>{
 assert.equal(typeof client.createCommunityImageLoader,'function');let resolve;const loader=client.createCommunityImageLoader({read:()=>new Promise(r=>resolve=r)});const pending=loader.load('a',{kind:'post',id:'p'});await new Promise(r=>setImmediate(r));loader.reset();resolve({dataUrl:'data:image/png;base64,'+png.toString('base64'),sha256:sha(png)});await rejectCode(pending,'STALE_CONTEXT');const bad=client.createCommunityImageLoader({read:async()=>({dataUrl:'data:image/png;base64,'+png.toString('base64'),sha256:'0'.repeat(64)})});await rejectCode(bad.load('a',{kind:'post',id:'p'}),'INVALID_INPUT');
});
test('expired drafts cannot be bound',async()=>{const f=fixture(),{assetId}=await f.upload();f.advance(86400001);await rejectCode(f.store.transaction(tx=>api.bindCommunityAsset(tx,{assetId,ownerId:owner('A'),targetKind:'post',targetId:'p',now:86500001})),'FORBIDDEN');});
test('failed storage deletion preserves metadata and capacity for a later retry',async()=>{const f=fixture(),{assetId}=await f.upload(),before=await f.tx.get('media','quota:'+owner('A'));f.storage.remove=async()=>{throw Object.assign(Error('unavailable'),{code:'UNAVAILABLE'});};await rejectCode(f.call('community.media.remove',{assetId}),'UNAVAILABLE');assert.deepEqual(await f.tx.get('media','quota:'+owner('A')),before);assert.ok(await f.tx.get('media',assetId));f.storage.remove=async ref=>f.objects.delete(ref);await f.call('community.media.remove',{assetId});assert.equal(await f.tx.get('media',assetId),undefined);});
test('capacity ledger stays compact after many confirmed tiny images',async()=>{const f=fixture();for(let i=0;i<300;i++)await f.upload();const q=await f.tx.get('media','quota:'+owner('A'));assert.ok(JSON.stringify(q).length<1000,'confirmed image IDs must not accumulate in quota document');});
test('cleanup recovers expired interrupted uploads while preserving bound media',async()=>{const f=fixture(),{ticketId}=await f.call('community.media.prepare',f.input);await f.store.transaction(async tx=>{const a=await tx.get('media',ticketId);a.state='uploading';a.fileRef='community/orphan';f.objects.set(a.fileRef,png);await tx.put('media',ticketId,a);});f.advance(86400001);assert.equal((await f.service.cleanupCandidates([ticketId])).removed.length,1);assert.equal(f.objects.size,0);});
test('corrupt PNG image data is rejected despite matching claimed hash and header',async()=>{const f=fixture(),corrupt=Buffer.from(png);corrupt[45]^=1;const {ticketId}=await f.call('community.media.prepare',{...f.input,sha256:sha(corrupt)});await rejectCode(f.call('community.media.confirm',{ticketId,bytesBase64:corrupt.toString('base64')}),'INVALID_INPUT');assert.equal(f.objects.size,0);});
test('cleanup command dry-run leaves expired objects intact and apply rechecks candidates',async()=>{const {cleanupCommunityMedia}=await import('../scripts/community-media-cleanup.mjs');const f=fixture(),{assetId}=await f.upload();f.advance(86400001);f.store.query=async()=>[await f.tx.get('media',assetId)];const preview=await cleanupCommunityMedia({store:f.store,storage:f.storage,clock:()=>86500001});assert.deepEqual(preview.removed,[assetId]);assert.equal(f.objects.size,1);const applied=await cleanupCommunityMedia({store:f.store,storage:f.storage,clock:()=>86500001,dryRun:false});assert.deepEqual(applied.removed,[assetId]);assert.equal(f.objects.size,0);});
test('prepare idempotency atomically reuses a ticket and rejects changed input',async()=>{const f=fixture();const first=await f.service.handle('community.media.prepare',f.input,{principal:f.a,idempotencyKey:'retry-prepare'});const repeated=await f.service.handle('community.media.prepare',f.input,{principal:f.a,idempotencyKey:'retry-prepare'});assert.deepEqual(repeated,first);await rejectCode(f.service.handle('community.media.prepare',{...f.input,width:2},{principal:f.a,idempotencyKey:'retry-prepare'}),'CONFLICT');assert.equal((await f.tx.get('media','quota:'+owner('A'))).bytes,png.length);});
test('remove idempotency succeeds after object and metadata have been deleted',async()=>{const f=fixture(),{assetId}=await f.upload();const context={principal:f.a,idempotencyKey:'retry-remove'};await f.service.handle('community.media.remove',{assetId},context);assert.deepEqual(await f.service.handle('community.media.remove',{assetId},context),{removed:true});});
test('confirm operation key cannot be reused for another ticket',async()=>{const f=fixture(),a=await f.call('community.media.prepare',f.input),b=await f.call('community.media.prepare',f.input);const context={principal:f.a,idempotencyKey:'confirm-once'};await f.service.handle('community.media.confirm',{ticketId:a.ticketId,bytesBase64:png.toString('base64')},context);await rejectCode(f.service.handle('community.media.confirm',{ticketId:b.ticketId,bytesBase64:png.toString('base64')},context),'CONFLICT');});
test('PNG chunk checksum corruption is rejected even when claimed SHA matches',async()=>{const f=fixture(),corrupt=Buffer.from(png);corrupt[corrupt.length-1]^=1;const {ticketId}=await f.call('community.media.prepare',{...f.input,sha256:sha(corrupt)});await rejectCode(f.call('community.media.confirm',{ticketId,bytesBase64:corrupt.toString('base64')}),'INVALID_INPUT');});
test('Date-returning gateway clocks still expire uploads after 24 hours',async()=>{const f=fixture();let now=100000;const service=api.createCommunityMediaService({store:f.store,storage:f.storage,fetch:f.fetch,clock:()=>new Date(now),ownerIdFor:owner,idFactory:()=> 'date-clock-ticket'});const {ticketId}=await service.handle('community.media.prepare',f.input,{principal:f.a});now+=86400001;await rejectCode(service.handle('community.media.confirm',{ticketId,bytesBase64:png.toString('base64')},{principal:f.a}),'INVALID_INPUT');});
test('JPEG without SOS compressed scan and WebP without VP8/VP8L frame are rejected',async()=>{
 const jpegHeader=Buffer.from('ffd8ffc00011080001000103012200021101031101ffd9','hex');
 const webpHeader=Buffer.alloc(30);webpHeader.write('RIFF');webpHeader.writeUInt32LE(22,4);webpHeader.write('WEBPVP8X',8);webpHeader.writeUInt32LE(10,16);
 for(const [bytes,mime]of [[jpegHeader,'image/jpeg'],[webpHeader,'image/webp']]){const f=fixture(),input={...f.input,mime,bytes:bytes.length,sha256:sha(bytes)};if(mime==='image/webp')await rejectCode(f.call('community.media.prepare',input),'INVALID_INPUT');else{const {ticketId}=await f.call('community.media.prepare',input);await rejectCode(f.call('community.media.confirm',{ticketId,bytesBase64:bytes.toString('base64')}),'INVALID_INPUT');}assert.equal(f.objects.size,0);}
});
test('cleanup racing a pending PUT cannot leave an untracked uncharged object',async()=>{
 const f=fixture();let releasePut,started;const putStarted=new Promise(r=>started=r);let now=100000;
 const service=api.createCommunityMediaService({store:f.store,storage:f.storage,ownerIdFor:owner,clock:()=>now,idFactory:()=> 'race-image',fetch:async(url,options)=>{started();await new Promise(r=>releasePut=r);return f.fetch(url,options);}});
 const {ticketId}=await service.handle('community.media.prepare',f.input,{principal:f.a});const confirming=service.handle('community.media.confirm',{ticketId,bytesBase64:png.toString('base64')},{principal:f.a}).catch(error=>({error}));await putStarted;now+=86400001;await service.cleanupCandidates([ticketId]);releasePut();const result=await confirming;assert.equal(result.error?.code,'CONFLICT');await service.cleanupCandidates([ticketId]);assert.equal(f.objects.size,0,'pending PUT must not resurrect an object after metadata deletion');assert.equal(await f.tx.get('media',ticketId),undefined);assert.equal((await f.tx.get('media','quota:'+owner('A'))).bytes,0);
});
test('valid source WebP is normalized to PNG before public media prepare',async()=>{
 const webp=Buffer.from('UklGRjwAAABXRUJQVlA4IDAAAADQAQCdASoBAAEAAUAmJaACdLoB+AADsAD+8ut//NgVzXPv9//S4P0uD9Lg/9KQAAA=','base64');
 const prepared=await client.prepareCommunityImage(new Blob([webp],{type:'image/webp'}),{decode:async()=>({width:1,height:1,close(){}}),createCanvas:()=>({getContext:()=>({drawImage(){}}),convertToBlob:async({type})=>new Blob([type==='image/png'?png:webp],{type})})});
 assert.equal(prepared.metadata.mime,'image/png');assert.equal(prepared.metadata.sha256,sha(png));assert.deepEqual(Buffer.from(prepared.bytesBase64,'base64'),png);
});
test('strict JPEG decoder accepts a real one-pixel JPEG and preserves exact bytes',async()=>{
 const jpeg=Buffer.from('/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAgGBgcGBQgHBwcJCQgKDBQNDAsLDBkSEw8UHRofHh0aHBwgJC4nICIsIxwcKDcpLDAxNDQ0Hyc5PTgyPC4zNDL/2wBDAQkJCQwLDBgNDRgyIRwhMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjL/wAARCAABAAEDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwDi6KKK+ZP3E//Z','base64');
 const f=fixture(),{ticketId}=await f.call('community.media.prepare',{...f.input,mime:'image/jpeg',bytes:jpeg.length,sha256:sha(jpeg)});const {assetId}=await f.call('community.media.confirm',{ticketId,bytesBase64:jpeg.toString('base64')});const reply=await f.call('community.media.read',{assetId});assert.equal(reply.sha256,sha(jpeg));assert.deepEqual(Buffer.from(reply.dataUrl.split(',')[1],'base64'),jpeg);
});
test('failed exact-object cleanup keeps a charged tombstone until cleanup succeeds',async()=>{
 const f=fixture();let releasePut,started;const putStarted=new Promise(r=>started=r);let now=100000;
 const service=api.createCommunityMediaService({store:f.store,storage:f.storage,ownerIdFor:owner,clock:()=>now,idFactory:()=> 'race-delete-failure',fetch:async(url,options)=>{started();await new Promise(r=>releasePut=r);return f.fetch(url,options);}});
 const {ticketId}=await service.handle('community.media.prepare',f.input,{principal:f.a}),confirming=service.handle('community.media.confirm',{ticketId,bytesBase64:png.toString('base64')},{principal:f.a}).catch(error=>({error}));await putStarted;now+=86400001;f.storage.remove=async()=>{throw Object.assign(Error('delete failed'),{code:'UNAVAILABLE'});};releasePut();assert.equal((await confirming).error.code,'UNAVAILABLE');assert.equal(f.objects.size,1);assert.equal((await f.tx.get('media',ticketId)).state,'cleaning');assert.equal((await f.tx.get('media','quota:'+owner('A'))).bytes,png.length);f.storage.remove=async ref=>f.objects.delete(ref);await service.cleanupCandidates([ticketId]);assert.equal(f.objects.size,0);assert.equal((await f.tx.get('media','quota:'+owner('A'))).bytes,0);
});
test('PNG with valid checksums but incomplete decoded scanline is rejected',async()=>{
 const {deflateSync}=await import('node:zlib');const crc=bytes=>{let c=0xffffffff;for(const n of bytes){c^=n;for(let i=0;i<8;i++)c=c>>>1^(c&1?0xedb88320:0);}return(c^0xffffffff)>>>0;};const chunk=(kind,bytes)=>{const type=Buffer.from(kind),out=Buffer.alloc(bytes.length+12);out.writeUInt32BE(bytes.length);type.copy(out,4);bytes.copy(out,8);out.writeUInt32BE(crc(Buffer.concat([type,bytes])),bytes.length+8);return out;};
 const fake=Buffer.concat([png.subarray(0,33),chunk('IDAT',deflateSync(Buffer.from([0]))),chunk('IEND',Buffer.alloc(0))]);const f=fixture(),{ticketId}=await f.call('community.media.prepare',{...f.input,bytes:fake.length,sha256:sha(fake)});await rejectCode(f.call('community.media.confirm',{ticketId,bytesBase64:fake.toString('base64')}),'INVALID_INPUT');
});
test('transient confirmation failure preserves an unexpired ticket for the same retry',async()=>{const f=fixture(),read=f.storage.read;let fail=true;f.storage.read=async(...args)=>{if(fail){fail=false;throw Object.assign(Error('transient read'),{code:'UNAVAILABLE'});}return read(...args);};const {ticketId}=await f.call('community.media.prepare',f.input);await rejectCode(f.call('community.media.confirm',{ticketId,bytesBase64:png.toString('base64')}),'UNAVAILABLE');assert.equal(f.objects.size,0);const result=await f.call('community.media.confirm',{ticketId,bytesBase64:png.toString('base64')});assert.equal(result.assetId,ticketId);assert.equal(f.objects.size,1);});
test('unknown PUT outcome retains its exact charged reference until delayed commits can be cleaned',async()=>{
 const f=fixture();let lateCommit,now=100000;const service=api.createCommunityMediaService({store:f.store,storage:f.storage,ownerIdFor:owner,clock:()=>now,idFactory:()=> 'unknown-put',fetch:async(url,options)=>{lateCommit=()=>f.fetch(url,options);throw Object.assign(Error('transport timeout'),{code:'UNAVAILABLE'});}});
 const {ticketId}=await service.handle('community.media.prepare',f.input,{principal:f.a});await rejectCode(service.handle('community.media.confirm',{ticketId,bytesBase64:png.toString('base64')},{principal:f.a}),'UNAVAILABLE');await lateCommit();
 const tracked=await f.tx.get('media',ticketId);assert.equal(tracked.state,'cleaning');assert.ok(tracked.fileRef,'unknown server-side commit must keep its exact object reference');assert.equal((await f.tx.get('media','quota:'+owner('A'))).bytes,png.length);
 now+=86400001;await service.cleanupCandidates([ticketId]);assert.ok(await f.tx.get('media',ticketId),'unknown upload tombstone cannot release before its safety window');now+=60000;await service.cleanupCandidates([ticketId]);assert.equal(f.objects.size,0);assert.equal(await f.tx.get('media',ticketId),undefined);assert.equal((await f.tx.get('media','quota:'+owner('A'))).bytes,0);
});
test('JPEG tables and frame without any compressed scan cannot decode as a blank substitute',async()=>{const jpeg=require('jpeg-js').encode({data:Buffer.from([255,0,0,255]),width:1,height:1},80).data;let at=2;while(jpeg[at+1]!==0xda)at+=2+jpeg.readUInt16BE(at+2);const fake=Buffer.concat([jpeg.subarray(0,at),Buffer.from([255,217])]);const f=fixture(),{ticketId}=await f.call('community.media.prepare',{...f.input,mime:'image/jpeg',bytes:fake.length,sha256:sha(fake)});await rejectCode(f.call('community.media.confirm',{ticketId,bytesBase64:fake.toString('base64')}),'INVALID_INPUT');});
