import test from 'node:test';import assert from 'node:assert/strict';import {createRequire,Module} from 'node:module';import {buildSync} from 'esbuild';import {existsSync} from 'node:fs';
const require=createRequire(import.meta.url);const{createMemoryCommunityStore}=require('../backend/community/store.cjs');let entry={};
if(existsSync('cloudfunctions/paw-community/index.js')){const built=buildSync({entryPoints:['cloudfunctions/paw-community/index.js'],bundle:true,platform:'node',format:'cjs',packages:'external',write:false,logLevel:'silent'});const compiled=new Module(import.meta.filename);compiled.paths=modulePaths();compiled._compile(built.outputFiles[0].text,import.meta.filename);entry=compiled.exports;}
function modulePaths(){return Module._nodeModulePaths(process.cwd());}
function harness({profile={sub:'A',email:'verified@example.test',email_verified:true},proof=null}={}){assert.equal(typeof entry.createCommunityEntrypoint,'function','trusted community entrypoint must exist');let reads=0;const store=createMemoryCommunityStore(),app={auth:()=>({getAuthContext:async()=>({uid:'A'}),getUserInfo:()=>({uid:'A',isAnonymous:false})})};const main=entry.createCommunityEntrypoint({app,store,storage:{},regions:{},getPlatformContext:()=>({TCB_UUID:'A',TCB_ISANONYMOUS_USER:'false'}),readVerifiedProfile:async token=>{reads++;return token==='valid-A'?profile:null;},readVerifiedProof:async()=>proof});return{main,reads:()=>reads};}
test('entrypoint allows genuine tokenless anonymous reads but rejects explicit empty or bad tokens',async()=>{const{main}=harness();const base={version:1,action:'profiles.discover',payload:{}};assert.equal((await main(base,{})).ok,true);for(const authToken of ['',null,42,'expired'])assert.equal((await main({...base,authToken},{})).error?.code,'UNAUTHENTICATED');});
test('entrypoint email comes from the same verified server profile and is not included in public identity',async()=>{const{main,reads}=harness();const own=await main({version:1,action:'auth.getOwn',payload:{},authToken:'valid-A'},{});assert.deepEqual(own,{ok:true,data:{email:'verified@example.test'}});assert.equal(reads(),1);const publicList=await main({version:1,action:'profiles.discover',payload:{},authToken:'valid-A'},{});assert.equal(JSON.stringify(publicList).includes('verified@example.test'),false);});
test('entrypoint rejects mismatched uid and unproven email without anonymous fallback',async()=>{for(const profile of [{sub:'B',email:'b@example.test',email_verified:true},{sub:'A',email:'a@example.test',email_verified:false}]){const{main}=harness({profile});assert.equal((await main({version:1,action:'profiles.discover',payload:{},authToken:'valid-A'},{})).error?.code,'UNAUTHENTICATED');}});
test('trusted email OTP proof is reused without exposing proof or platform UID',async()=>{const{emailHash}=require('../backend/email-auth.cjs');const{main}=harness({profile:{sub:'A',email:'a@example.test',email_verified:false},proof:{kind:'verified',ownerId:'A',emailHash:emailHash('a@example.test'),verifiedAt:'2026-10-07T12:00:00Z'}});assert.deepEqual(await main({version:1,action:'auth.getOwn',payload:{},authToken:'valid-A'},{}),{ok:true,data:{email:'a@example.test'}});});
test('supplied invalid token is not overridden by another context credential',async()=>{const{main}=harness();assert.equal((await main({version:1,action:'profiles.discover',payload:{},authToken:'expired'},{extendedContext:{accessToken:'valid-A'}})).error?.code,'UNAUTHENTICATED');});
test('actual function entry registers public posts and interaction handlers',async()=>{const{main}=harness();const list=await main({version:1,action:'community.list',payload:{}},{});assert.deepEqual(list,{ok:true,data:{items:[],nextCursor:null}});});
test('actual entry dispatches report and hidden actions alongside posts without exposing admin actions',async()=>{const{main}=harness();const hidden=await main({version:1,action:'community.hidden.list',payload:{},authToken:'valid-A'},{});assert.deepEqual(hidden,{ok:true,data:{items:[],nextCursor:null}});assert.equal((await main({version:1,action:'admin.hide',payload:{},authToken:'valid-A'},{})).error?.code,'INVALID_INPUT');});
test('actual platform tcbContext metadata is ignored without trusting its forged identity or token',async()=>{const{main}=harness();const metadata={uid:'forged-B',authToken:'valid-A',isAnonymous:false,emailVerified:true};const read=await main({version:1,action:'profiles.discover',payload:{},tcbContext:metadata},{});assert.equal(read.ok,true);assert.deepEqual(read.data,{items:[],nextCursor:null});assert.equal(Object.hasOwn(read,'diagnostic'),false);const write=await main({version:1,action:'profiles.saveOwn',payload:{nickname:'Forged'},idempotencyKey:'fake-platform',tcbContext:metadata},{});assert.equal(write.error?.code,'UNAUTHENTICATED');assert.equal(Object.hasOwn(write,'diagnostic'),false);});
test('removing platform metadata preserves unknown envelope rejection and removes temporary diagnostics',async()=>{const{main}=harness();const response=await main({version:1,action:'profiles.discover',payload:{},tcbContext:{uid:'synthetic'},ownerId:'forged'},{});assert.equal(response.error?.code,'INVALID_INPUT');assert.equal(Object.hasOwn(response,'diagnostic'),false);});
