import test from 'node:test';import assert from 'node:assert/strict';
let api={};try{api=await import('../src/features/community-draft-handoff.js');}catch(e){if(e.code!=='ERR_MODULE_NOT_FOUND')throw e;}
function fixture(){assert.equal(typeof api.createDraftHandoff,'function','explicit community draft handoff must exist');let now=1000,id=0;return{handoff:api.createDraftHandoff({clock:()=>now,idFactory:()=>`handoff-${++id}`}),advance:n=>now+=n};}
const draft={title:'首篇',text:'今天出门了',topic:'今日萌宠',cityId:null,districtId:null,imageAssetId:null,operationId:'publish-once',baseRevision:0};
test('explicit guest login binds once then consumes the same draft once',()=>{const {handoff}=fixture();assert.equal(handoff.stage({draft,intent:'login'}),'handoff-1');handoff.bindLoginOwner('A');assert.deepEqual(handoff.consume('A'),draft);assert.equal(handoff.consume('A'),null);});
test('an A-owned profile draft cannot be given to B',()=>{const {handoff}=fixture();handoff.stage({draft,ownerId:'A',intent:'profile'});assert.equal(handoff.consume('B'),null);assert.deepEqual(handoff.consume('A'),draft);handoff.stage({draft,ownerId:'A',intent:'profile'});assert.throws(()=>handoff.bindLoginOwner('B'),e=>e.code==='IDENTITY_CHANGED');});
test('expired cancelled or logout-cleared handoff never restores a draft',()=>{const {handoff,advance}=fixture();handoff.stage({draft,intent:'login'});advance(1800001);assert.equal(handoff.consume('A'),null);handoff.stage({draft,ownerId:'A',intent:'profile'});handoff.clear();assert.equal(handoff.consume('A'),null);});
test('private snapshot credentials and guest cloud references are not eligible handoff data',()=>{const {handoff}=fixture();for(const extra of [{snapshot:{records:[]}},{authToken:'secret'},{fileRef:'cloud://private'},{imageAssetId:'private-id'}])assert.throws(()=>handoff.stage({draft:{...draft,...extra},intent:'login'}),e=>e.code==='INVALID_INPUT');});
test('guest login cannot silently rebind its already assigned owner',()=>{const {handoff}=fixture();handoff.stage({draft,intent:'login'});handoff.bindLoginOwner('A');assert.throws(()=>handoff.bindLoginOwner('B'),e=>e.code==='IDENTITY_CHANGED');assert.equal(handoff.consume('B'),null);assert.deepEqual(handoff.consume('A'),draft);});
test('comment login handoff carries only its explicit post and text',()=>{const {handoff}=fixture();const comment={kind:'comment',postId:'public-post',text:'同一条待发送评论',operationId:'comment-once'};handoff.stage({draft:comment,intent:'login'});handoff.bindLoginOwner('A');assert.deepEqual(handoff.consume('A'),comment);});
