import test from 'node:test';import assert from 'node:assert/strict';import{createRequire}from'node:module';
const require=createRequire(import.meta.url),cloudbase=require('@cloudbase/node-sdk');const{createCommunityStore}=require('../backend/community/store.cjs');
// Only the external database boundary is simulated; SDK query operators stay real.
function database(){const sdk=cloudbase.init({env:'paw-diary-d8g3p4tlsb305221d'}).database();let docs=new Map();
 const matches=(doc,input)=>{const filter=JSON.parse(JSON.stringify(input));if(filter.operator==='and')return filter.operands.every(f=>matches(doc,f));if(filter.operator==='or')return filter.operands.some(f=>matches(doc,f));return Object.entries(filter).every(([key,value])=>{const actual=doc[key];if(value&&typeof value==='object'){if(value.$regularExpression)return new RegExp(value.$regularExpression.pattern,value.$regularExpression.options).test(actual??'');if(value.$lt!==undefined)return actual<value.$lt;if(value.$in)return(Array.isArray(actual)?actual:[actual]).some(v=>value.$in.includes(v));}return actual===value;});};
 const wrap=data=>({collection(name){let condition={},ordering=[],count=100;const query={where(input){condition=input;return query;},orderBy(key,direction){ordering.push([key,direction]);return query;},limit(n){count=n;return query;},async get(){const rows=[...data].filter(([key])=>key.startsWith(name+'\0')).map(([,v])=>structuredClone(v)).filter(v=>matches(v,condition));rows.sort((a,b)=>{for(const[key,dir]of ordering){if(a[key]!==b[key])return(a[key]<b[key]?-1:1)*(dir==='desc'?-1:1);}return 0;});return{data:rows.slice(0,count)};},doc(id){const key=name+'\0'+id;return{async get(){return{data:data.has(key)?[{...structuredClone(data.get(key)),_id:id}]:[]};},async set(value){data.set(key,structuredClone(value));return{};},async remove(){data.delete(key);return{};}};}};return query;}});
 const db={command:sdk.command,RegExp:sdk.RegExp,get collection(){return wrap(docs).collection;},async runTransaction(callback){const next=new Map([...docs].map(([k,v])=>[k,structuredClone(v)]));const result=await callback(wrap(next));docs=next;return result;}};return db;
}
test('Cloud store searches title and body with the same public semantics as memory store',async()=>{const store=createCommunityStore({db:database()});await store.transaction(async tx=>{for(const[id,title,text]of[['a','FOX','quiet'],['b','dog','FOX'],['c','mouse','none']])await tx.put('posts',id,{id,title,text,createdAt:'2026-10-07T13:00:00Z',deletedAt:null,moderationStatus:'visible'});});const reply=await store.listPosts({query:'fox'});assert.deepEqual(reply.items.map(p=>p.id).sort(),['a','b']);});
test('Cloud store query preserves keyset pagination filters and hides internal document IDs',async()=>{const store=createCommunityStore({db:database()});await store.transaction(async tx=>{for(const authorId of ['a','b','c'])await tx.put('profiles',authorId,{authorId,discoverable:true,petTypes:['cat'],purposes:['新手互助'],updatedAt:'2026-10-07T13:00:00Z'});});const first=await store.discover({petTypes:['cat'],limit:1}),next=await store.discover({petTypes:['cat'],limit:1,cursor:first.nextCursor});assert.equal(first.items[0].authorId,'c');assert.equal(next.items[0].authorId,'b');assert.equal(next.items[0]._id,undefined);await assert.rejects(store.discover({petTypes:['dog'],limit:1,cursor:first.nextCursor}),e=>e.code==='INVALID_INPUT');});
test('hidden items paginate beyond one hundred and the cursor is bound to its owner',async()=>{const{createMemoryCommunityStore}=require('../backend/community/store.cjs');for(const store of[createMemoryCommunityStore(),createCommunityStore({db:database()})]){await store.transaction(async tx=>{for(let i=0;i<105;i++){const id=String(i).padStart(3,'0');await tx.put('hidden',id,{id,ownerId:'owner-A',postId:'p-'+id,hidden:true,createdAt:'2026-10-07T13:00:00Z'});}await tx.put('hidden','other',{id:'other',ownerId:'owner-B',postId:'B',hidden:true,createdAt:'2026-10-07T13:00:00Z'});});const first=await store.listOwnHidden('owner-A',{limit:50});assert.equal(first.items?.length,50);const second=await store.listOwnHidden('owner-A',{limit:50,cursor:first.nextCursor}),third=await store.listOwnHidden('owner-A',{limit:50,cursor:second.nextCursor});assert.equal(second.items.length,50);assert.equal(third.items.length,5);assert.equal(third.nextCursor,null);assert.equal(new Set([...first.items,...second.items,...third.items].map(h=>h.id)).size,105);await assert.rejects(store.listOwnHidden('owner-B',{limit:50,cursor:first.nextCursor}),e=>e.code==='INVALID_INPUT');}});
