import test from 'node:test';
import assert from 'node:assert/strict';
import {migrateV1} from '../src/domain/schema.js';
import {applyRecord,removeRecord} from '../src/domain/records.js';
import {applyReminder,completeReminder} from '../src/domain/reminders.js';
import {v1,now,ids} from './fixtures/local-state.js';
import {validateSnapshot} from '../src/domain/schema.js';
const base=()=>migrateV1(v1(),{now});
test('backup data cannot silently reinterpret grams as kilograms or discard unsupported values',()=>{
  const s=base();s.records[0].unit='g';assert.throws(()=>validateSnapshot(s));
  const nonWeight=base();nonWeight.records.find(r=>r.type==='deworm').value=3;assert.throws(()=>validateSnapshot(nonWeight));
});
test('an explicit change from weight to daily clears old weight fields without changing record identity',()=>{
  const changed=applyRecord(base(),{id:'a',type:'daily',title:'生活瞬间'},{now,idFactory:ids()});
  const record=changed.records.find(r=>r.id==='a');assert.equal(record.type,'daily');assert.equal(record.value,null);assert.equal(record.unit,null);
});
test('weight rejects invalid boundaries and impossible or future dates',()=>{for(const value of [0,201,NaN,'oops',null,''])assert.throws(()=>applyRecord(base(),{petId:'p1',type:'weight',occurredDate:'2026-10-06',value},{now,idFactory:ids()}));for(const value of [0.01,200])assert.equal(applyRecord(base(),{petId:'p1',type:'weight',occurredDate:'2026-10-06',value},{now,idFactory:ids()}).records.at(0).value,value);for(const date of ['2026-02-30','2026-10-07'])assert.throws(()=>applyRecord(base(),{petId:'p1',type:'weight',occurredDate:date,value:2},{now,idFactory:ids()}));});
test('editing preserves identity and creation time; latest actual-date weight stays correct',()=>{const s=base(),old=s.records.find(r=>r.id==='a');const changed=applyRecord(s,{id:'a',value:24,occurredDate:'2026-08-01'},{now,idFactory:ids()});const record=changed.records.find(r=>r.id==='a');assert.equal(record.createdAt,old.createdAt);assert.equal(record.updatedAt,now);assert.equal(changed.records.filter(r=>r.petId==='p1'&&r.type==='weight').sort((a,b)=>a.occurredDate.localeCompare(b.occurredDate)||a.createdAt.localeCompare(b.createdAt)).at(-1).value,22.5);assert.equal(changed.records.filter(r=>r.petId==='p2').length,1);assert.equal(s.records.find(r=>r.id==='a').value,23);});
test('delete cancels linked pending reminder and does not delete completed history',()=>{const s=removeRecord(base(),'d',{now});assert.equal(s.records.find(r=>r.id==='d').deletedAt,now);assert.equal(s.reminders.find(r=>r.originRecordId==='d')?.status,'cancelled');assert.equal(s.reminders.find(r=>r.status==='completed')?.originRecordId,'c');});
test('record next date updates one pending reminder atomically and null cancels it',()=>{let s=base();const id=s.reminders.find(r=>r.originRecordId==='d').id;s=applyRecord(s,{id:'d',nextDate:'2026-11-01'},{now,idFactory:ids()});assert.equal(s.reminders.find(r=>r.id===id).dueDate,'2026-11-01');assert.ok(!('nextDate' in s.records.find(r=>r.id==='d')));s=applyRecord(s,{id:'d',nextDate:null},{now,idFactory:ids()});assert.equal(s.reminders.find(r=>r.id===id).status,'cancelled');});
test('completion is idempotent and inherits original type without inventing dose',()=>{const s=base(),id=s.reminders.find(r=>r.originRecordId==='d').id,dep={now,idFactory:ids()};const first=completeReminder(s,id,{occurredDate:'2026-10-06',note:'已完成',idempotencyKey:'click'},dep);const again=completeReminder(first.state,id,{occurredDate:'2026-10-06',note:'再次点'},dep);assert.equal(first.state.records.length,5);assert.equal(again.state.records.length,5);assert.equal(again.record.id,first.record.id);assert.equal(first.record.type,'deworm');assert.equal(first.record.title,'驱虫');assert.equal(first.record.note,'已完成');assert.equal(first.reminder.completedAt,now);assert.equal(first.record.value,null);});
test('standalone reminder completes as daily and cancelled cannot complete',()=>{const dep={now,idFactory:ids()},s=applyReminder(base(),{petId:'p2',title:'梳毛',dueDate:'2026-10-08'},dep),rem=s.reminders.at(0);const done=completeReminder(s,rem.id,{occurredDate:'2026-10-06'},dep);assert.equal(done.record.type,'daily');assert.equal(done.record.petId,'p2');assert.throws(()=>completeReminder(applyReminder(s,{id:rem.id,status:'cancelled'},dep),rem.id,{occurredDate:'2026-10-06'},dep));});
test('legacy completed reminder retry preserves history without creating a completion record',()=>{const s=base(),id=s.reminders.find(r=>r.status==='completed').id;const result=completeReminder(s,id,{occurredDate:'2026-10-06'},{now,idFactory:ids()});assert.equal(result.record,null);assert.equal(result.state.records.length,4);assert.equal(result.reminder.completedAt,null);});
test('deleting a completion record preserves factual completed date and does not recreate it',()=>{const s=base(),id=s.reminders.find(r=>r.status==='pending').id,dep={now,idFactory:ids()};const done=completeReminder(s,id,{occurredDate:'2026-10-06'},dep);const removed=removeRecord(done.state,done.record.id,{now}),rem=removed.reminders.find(r=>r.id===id);assert.equal(rem.status,'completed');assert.equal(rem.completedAt,now);assert.equal(rem.completionRecordId,done.record.id);assert.equal(removed.records.find(r=>r.id===done.record.id).deletedAt,now);const retry=completeReminder(removed,id,{occurredDate:'2026-10-06'},dep);assert.equal(retry.record,null);assert.equal(retry.state.records.length,5);});
