import test from 'node:test';import assert from 'node:assert/strict';
import {normalizePet,validateSnapshot} from '../src/domain/schema.js';import {applyReminder,completeReminder} from '../src/domain/reminders.js';import {applyRecord} from '../src/domain/records.js';import {moveToTrash,restoreFromTrash} from '../src/domain/lifecycle.js';import {validateBackup} from '../src/domain/backup.js';import {computeRecapFacts,recapSourceHash} from '../src/domain/recap-facts.js';
let plans;try{plans=await import('../src/domain/health-plans.js');}catch{}
const now='2026-10-07T01:00:00.000Z';let n=0;const deps={now,idFactory:()=>`plan-${++n}`};const base=()=>({version:3,mode:'local',activePetId:'p',pets:[normalizePet({id:'p',name:'合成猫',type:'cat'})],records:[],reminders:[],posts:[],profile:{city:'深圳'}});
test('plan defaults and explicit health choices do not guess names',()=>{assert.equal(typeof plans?.defaultPlanHealth,'function');for(const type of ['daily','weight','other'])assert.equal(plans.defaultPlanHealth(type),false);for(const type of ['vaccine','deworm'])assert.equal(plans.defaultPlanHealth(type),true);assert.equal(plans.isHealthTodo({recordType:'daily',title:'疫苗',includeInHealth:false}),false);assert.equal(plans.isHealthTodo({recordType:'daily',includeInHealth:true}),true);});
test('legacy health interpretation preserves linked, weight and untyped independent plans',()=>{assert.equal(typeof plans?.isHealthTodo,'function');assert.equal(plans.isHealthTodo({originRecordId:'old',recordType:'daily'}),true);assert.equal(plans.isHealthTodo({recordType:'weight'}),true);assert.equal(plans.isHealthTodo({recordType:'daily'}),false);assert.equal(plans.isHealthTodo({title:'出去玩'}),true);});
test('new typed plans persist default flags, explicit choices and reject string flags',()=>{const daily=applyReminder(base(),{petId:'p',title:'出去玩',recordType:'daily',dueDate:'2026-10-09'},deps);assert.equal(daily.reminders[0].includeInHealth,false);const vaccine=applyReminder(base(),{petId:'p',title:'疫苗',recordType:'vaccine',dueDate:'2026-10-09'},deps);assert.equal(vaccine.reminders[0].includeInHealth,true);assert.throws(()=>applyReminder(base(),{petId:'p',title:'坏flag',dueDate:'2026-10-09',includeInHealth:'false'},deps));});
test('rename note, backup, recycle and completion preserve explicit ordinary classification without adding old flags',()=>{let s=applyReminder(base(),{petId:'p',title:'普通安排',recordType:'daily',dueDate:'2026-10-07',includeInHealth:false,note:'原计划'},deps),id=s.reminders[0].id;s=applyReminder(s,{id,title:'新名字',note:'新备注'},deps);assert.equal(s.reminders[0].includeInHealth,false);assert.equal(validateBackup(s).reminders[0].includeInHealth,false);s=moveToTrash(s,{kind:'reminder',ids:[id]},deps);s=restoreFromTrash(s,{kind:'reminder',ids:[id]});assert.equal(s.reminders[0].includeInHealth,false);s=completeReminder(s,id,{occurredDate:'2026-10-07'},deps).state;assert.equal(s.reminders[0].includeInHealth,false);assert.equal(s.records[0].note,'新备注');const old=applyReminder(base(),{petId:'p',title:'旧独立',dueDate:'2026-10-09'},deps);assert.equal(Object.hasOwn(validateSnapshot(old).reminders[0],'includeInHealth'),false);});
test('record-linked health choice is preserved and invalid choices cannot cross cloud domain',()=>{const s=applyRecord(base(),{petId:'p',type:'daily',title:'已游玩',occurredDate:'2026-10-06',nextDate:'2026-10-10',includeInHealth:false},deps);assert.equal(s.reminders[0].includeInHealth,false);assert.throws(()=>applyRecord(base(),{petId:'p',type:'daily',title:'坏flag',occurredDate:'2026-10-06',nextDate:'2026-10-10',includeInHealth:'false'},deps));});
test('recap excludes ordinary completion and upcoming from care but retains true sources and classification hash',async()=>{let s=applyReminder(base(),{petId:'p',recordType:'daily',title:'公园',dueDate:'2026-10-07',includeInHealth:false},deps);s=completeReminder(s,s.reminders[0].id,{occurredDate:'2026-10-07'},deps).state;s=applyReminder(s,{petId:'p',recordType:'daily',title:'再去玩',dueDate:'2026-10-10',includeInHealth:false},deps);const scope={snapshot:s,petId:'p',from:'2026-10-01',to:'2026-10-07'},facts=computeRecapFacts(scope);assert.equal(facts.completedCareCount,0);assert.equal(facts.upcomingReminders.length,0);assert.equal(facts.reminderIds.length,2);const before=await recapSourceHash(scope);s.reminders[0].includeInHealth=true;assert.notEqual(await recapSourceHash(scope),before);});
import {createRequire} from 'node:module';const require=createRequire(import.meta.url),{handleRequest}=require('../backend/api.cjs'),{memoryStore}=require('./helpers/cloud-memory.cjs');
test('trusted cloud contract persists includeInHealth and rejects string flags without a write',async()=>{const store=memoryStore();let revision=0,count=0;const run=async(action,payload)=>{const result=await handleRequest({version:1,action,payload,expectedRevision:revision,idempotencyKey:`health-plan-${++count}`},{principal:{userId:'synthetic-A',emailVerified:true,isAnonymous:false},store,clock:()=>now,idFactory:deps.idFactory});if(result.ok&&result.revision!==undefined)revision=result.revision;return result;};const p=await run('pets.save',{name:'合成猫',type:'cat'}),plan=await run('reminders.save',{petId:p.data.id,title:'出去玩',recordType:'daily',dueDate:'2026-10-09',includeInHealth:false});assert.equal(plan.ok,true);assert.equal(plan.data.includeInHealth,false);const before=revision,bad=await run('reminders.save',{petId:p.data.id,title:'错误选择',recordType:'daily',dueDate:'2026-10-09',includeInHealth:'false'});assert.equal(bad.error.code,'INVALID_INPUT');const snapshot=await run('health.snapshot',{});assert.equal(snapshot.revision,before);assert.equal(snapshot.data.reminders.length,1);assert.equal(snapshot.data.reminders[0].includeInHealth,false);});
