import test from 'node:test';import assert from 'node:assert/strict';import {createRequire} from 'node:module';const require=createRequire(import.meta.url);
async function limits(){let m;try{m=require('../backend/community/limits.cjs');}catch(e){if(e.code!=='MODULE_NOT_FOUND')throw e;}assert.ok(m,'原子位置预算尚未实现');return m;}
function store(){let values=new Map(),queue=Promise.resolve();return{transaction(fn){const run=queue.then(async()=>{const copy=structuredClone(values),result=await fn({get:async k=>copy.get(k),put:async(k,v)=>copy.set(k,structuredClone(v))});values=copy;return result;});queue=run.catch(()=>{});return run;}};}
test('Unverified free allocation blocks all upstream calls',async()=>{const {createLocationLimits}=await limits();const budget=createLocationLimits({store:store()});await assert.rejects(budget.reserveUpstream(),e=>e.code==='LOCATION_QUOTA_EXCEEDED');});
test('Concurrent reservation honors smaller verified free quota without overshoot',async()=>{const {createLocationLimits}=await limits();const budget=createLocationLimits({store:store(),freeDaily:2,freeMonthly:10,clock:()=>new Date('2026-10-07T12:00:00Z')});const outcomes=await Promise.allSettled(Array.from({length:8},()=>budget.reserveUpstream()));assert.equal(outcomes.filter(r=>r.status==='fulfilled').length,2);assert.equal(outcomes.filter(r=>r.status==='rejected').length,6);});
test('Each upstream request consumes budget and new CST day cannot bypass month limit',async()=>{const {createLocationLimits}=await limits();let now='2026-10-07T15:59:00Z';const budget=createLocationLimits({store:store(),freeDaily:10,freeMonthly:2,clock:()=>new Date(now)});await budget.reserveUpstream();now='2026-10-07T16:01:00Z';await budget.reserveUpstream();await assert.rejects(budget.reserveUpstream(),e=>e.code==='LOCATION_QUOTA_EXCEEDED');});
test('Visitor and trusted-IP limits are atomic and denied visitor does not consume IP',async()=>{const {createLocationLimits}=await limits();const budget=createLocationLimits({store:store(),freeDaily:100,freeMonthly:1000,clock:()=>new Date('2026-10-07T12:00:00Z')});for(let i=0;i<5;i++)await budget.reserveSuggestion({visitorId:'visitor-one',ipHash:'a'.repeat(64)});await assert.rejects(budget.reserveSuggestion({visitorId:'visitor-one',ipHash:'a'.repeat(64)}),e=>e.code==='LOCATION_QUOTA_EXCEEDED');for(let i=0;i<5;i++)await budget.reserveSuggestion({visitorId:'visitor-two',ipHash:'a'.repeat(64)});await assert.rejects(budget.reserveSuggestion({visitorId:'visitor-three',ipHash:'a'.repeat(64)}),e=>e.code==='LOCATION_QUOTA_EXCEEDED');await assert.rejects(budget.reserveSuggestion({visitorId:'x',ipHash:null}),e=>e.code==='REGION_UNAVAILABLE');});
test('Upstream pacing is shared by independent limiter instances using the same database',async()=>{const {createLocationLimits}=await limits();let time=Date.parse('2026-10-07T12:00:00Z');const shared=store(),options={store:shared,freeDaily:100,freeMonthly:1000,clock:()=>new Date(time),sleep:async ms=>{time+=ms;}};const first=createLocationLimits(options),second=createLocationLimits(options);assert.equal(typeof first.callUpstream,'function','共享QPS入口尚未实现');const starts=[];for(const budget of[first,second,first])await budget.callUpstream(()=>{starts.push(time);return 'ok';});assert.ok(starts[1]-starts[0]>=250);assert.ok(starts[2]-starts[1]>=250);});
test('A stalled request keeps the shared lease; another instance stops at its bounded wait without calling upstream',async()=>{const {createLocationLimits}=await limits();let time=Date.parse('2026-10-07T12:00:00Z'),release,entered;const started=new Promise(r=>entered=r),shared=store(),options={store:shared,freeDaily:100,freeMonthly:1000,clock:()=>new Date(time),sleep:async ms=>{time+=ms;},queueWaitMs:100};const a=createLocationLimits(options),b=createLocationLimits(options);assert.equal(typeof a.callUpstream,'function');let calls=0;const one=a.callUpstream(()=>{calls++;entered();return new Promise(r=>release=r);});await started;await assert.rejects(b.callUpstream(()=>{calls++;}),e=>e.code==='LOCATION_RATE_LIMITED');assert.equal(calls,1);release('done');assert.equal(await one,'done');});
test('Upstream failure releases its pacing lease without refunding daily/monthly budget',async()=>{const {createLocationLimits}=await limits();let time=Date.parse('2026-10-07T12:00:00Z');const budget=createLocationLimits({store:store(),freeDaily:2,freeMonthly:2,clock:()=>new Date(time),sleep:async ms=>{time+=ms;}});assert.equal(typeof budget.callUpstream,'function');await assert.rejects(budget.callUpstream(()=>{throw Error('synthetic failure');}),/synthetic failure/);assert.equal(await budget.callUpstream(()=> 'second'),'second');await assert.rejects(budget.callUpstream(()=> 'must not run'),e=>e.code==='LOCATION_QUOTA_EXCEEDED');});
test('An overslept waiter cannot acquire an expired deadline even when the shared gate is now free',async()=>{const {createLocationLimits}=await limits();let time=Date.parse('2026-10-07T12:00:00Z'),calls=0;const shared=store(),options={store:shared,freeDaily:100,freeMonthly:1000,clock:()=>new Date(time),sleep:async()=>{time+=5000;}};const first=createLocationLimits(options),second=createLocationLimits(options);await first.callUpstream(()=>calls++);await assert.rejects(second.callUpstream(()=>calls++),e=>e.code==='LOCATION_RATE_LIMITED');assert.equal(calls,1);});
test('upstream counter reads are serialized within a native database transaction',async()=>{const {createLocationLimits}=await limits();let busy=0,peak=0;const values=new Map(),nativeStore={transaction:fn=>fn({get:async key=>{busy++;peak=Math.max(peak,busy);await new Promise(resolve=>setImmediate(resolve));busy--;if(peak>1)throw Object.assign(Error('native transaction cannot interleave reads'),{code:'DATABASE_TRANSACTION_FAIL'});return values.get(key);},put:async(key,value)=>values.set(key,value)})};const budget=createLocationLimits({store:nativeStore,freeDaily:100,freeMonthly:1000});await budget.reserveUpstream();assert.equal(peak,1);assert.equal(values.size,2);});
