import test from 'node:test';import assert from 'node:assert/strict';import {createRequire} from 'node:module';
const require=createRequire(import.meta.url),{createMemoryCommunityStore,hashOwner}=require('../backend/community/store.cjs'),{handleCommunity}=require('../backend/community/gateway.cjs');
const profiles=[{authorId:'author-a',nickname:'合成A',cityId:'440300',cityName:'深圳市',districtId:'440305',districtName:'南山区',petTypes:['cat'],purposes:['养猫交流'],bio:'交流猫咪日常'},{authorId:'author-b',nickname:'合成B',cityId:'310000',cityName:'上海市',districtId:'310101',districtName:'黄浦区',petTypes:['dog'],purposes:['遛宠搭子'],bio:'公开散步日常'},{authorId:'author-c',nickname:'合成C',cityId:'440300',cityName:'深圳市',districtId:'440304',districtName:'福田区',petTypes:['dog'],purposes:['新手互助'],bio:''}];
async function controllerModule(){const m=await import('../src/features/nearby.js').catch(e=>{if(e.code!=='ERR_MODULE_NOT_FOUND')throw e;return {};});assert.equal(typeof m.createNearbyController,'function','真实宠友UI控制器尚未实现');return m;}
async function fixture(){const m=await controllerModule(),store=createMemoryCommunityStore();await store.transaction(async tx=>{for(const p of profiles)await tx.put('profiles',p.authorId,{...p,ownerId:hashOwner(p.authorId),discoverable:true,updatedAt:'2026-10-07T13:40:00Z'});});let session={userId:null,generation:1},browse={cityId:'440300',districtId:null,cityName:'深圳市',districtName:null};const calls=[];const repository={request:async(action,payload)=>{calls.push({action,payload});const response=await handleCommunity({version:1,action,payload},{store});if(!response.ok)throw Object.assign(Error(response.error.code),{code:response.error.code});return response.data;}};const controller=m.createNearbyController({repository,getSession:()=>session,getBrowseRegion:()=>browse,onBrowseRegion:r=>browse={...r},getOwnAuthorId:()=>session.userId?'author-a':null});return {controller,store,calls,setSession:s=>session=s,getBrowse:()=>browse};}
test('Anonymous all mode spans cities; city, pet and purpose filters combine correctly without editing own profile',async()=>{const f=await fixture();await f.controller.load();assert.equal(f.controller.getState().items.length,3);assert.equal(f.calls[0].payload.cityId,undefined);await f.controller.setFilters({scope:'city',petType:'cat',purpose:'养猫交流'});assert.deepEqual(f.controller.getState().items.map(p=>p.authorId),['author-a']);await f.controller.setFilters({scope:'all'});assert.equal(f.calls.at(-1).payload.cityId,undefined);assert.equal(f.calls.some(c=>c.action==='profiles.saveOwn'),false);});
test('Changing browse city clears a foreign district and all mode retains the preference without using it',async()=>{const f=await fixture();await f.controller.setBrowseRegion({cityId:'440300',districtId:'440305',cityName:'深圳市',districtName:'南山区'});await f.controller.setBrowseRegion({cityId:'310000',cityName:'上海市'});assert.equal(f.getBrowse().districtId,null);await f.controller.setFilters({scope:'all'});assert.equal(f.calls.at(-1).payload.districtId,undefined);assert.equal(f.getBrowse().cityId,'310000');await f.controller.setFilters({scope:'city'});assert.deepEqual(f.controller.getState().items.map(p=>p.authorId),['author-b']);});
test('A withdrawn profile vanishes from refreshed list and old details cannot reveal discovery fields',async()=>{const f=await fixture();await f.controller.load();await f.controller.openProfile('author-a');assert.equal(f.controller.getState().selected.bio,profiles[0].bio);await f.store.transaction(async tx=>{const p=await tx.get('profiles','author-a');p.discoverable=false;await tx.put('profiles','author-a',p);});await f.controller.refresh();assert.equal(f.controller.getState().selected,null);assert.equal(f.controller.getState().items.some(p=>p.authorId==='author-a'),false);await f.controller.openProfile('author-a');assert.equal(f.controller.getState().selected,null);assert.equal(f.controller.getState().detailError,'NOT_FOUND');});
test('Filter changes and account changes discard late list and detail responses',async()=>{const m=await controllerModule();let releaseList,releaseDetail,scope={userId:'a',generation:1};const controller=m.createNearbyController({getSession:()=>scope,repository:{request:async(action,payload)=>action==='profiles.getPublic'?new Promise(r=>releaseDetail=r):payload.petTypes?.[0]==='cat'?{items:[profiles[0]],nextCursor:null}:new Promise(r=>releaseList=r)}});const stale=controller.load();await controller.setFilters({petType:'cat'});releaseList({items:[profiles[1]],nextCursor:null});await stale;assert.equal(controller.getState().items[0].authorId,'author-a');const detail=controller.openProfile('author-a');scope={userId:'b',generation:2};releaseDetail(profiles[0]);await detail;assert.equal(controller.getState().selected,null);});
test('Self label uses public author identity and pagination deduplicates by authorId',async()=>{const m=await controllerModule();let requests=0;const controller=m.createNearbyController({getOwnAuthorId:()=> 'author-a',getSession:()=>({userId:'a',generation:1}),repository:{request:async()=>++requests===1?{items:[profiles[0]],nextCursor:'page2'}:{items:[profiles[0],profiles[1]],nextCursor:null}}});await controller.load();await controller.load({more:true});assert.equal(controller.getState().items.length,2);assert.equal(controller.isOwn('author-a'),true);assert.equal(controller.isOwn('author-b'),false);});
test('Read failure differs from empty and city mode without a city does not send a forged discovery request',async()=>{const m=await controllerModule();let count=0;const controller=m.createNearbyController({getBrowseRegion:()=>({cityId:null}),repository:{request:async()=>{count++;throw Object.assign(Error('offline'),{code:'UNAVAILABLE'});}}});await controller.setFilters({scope:'city'});assert.equal(count,0);assert.equal(controller.getState().needsRegion,true);await controller.setFilters({scope:'all'});assert.equal(controller.getState().error,'UNAVAILABLE');assert.equal(controller.getState().items.length,0);});
