import test from 'node:test';
import assert from 'node:assert/strict';
import {IDBFactory} from 'fake-indexeddb';
import {createLocalRepository} from '../src/data/local-repository.js';
const png=new Uint8Array([137,80,78,71,13,10,26,10,...new Uint8Array(40)]);
const blob=()=>new Blob([png],{type:'image/png'});
async function setup(){let id=0;const options={indexedDB:new IDBFactory(),idFactory:()=>`asset-${++id}`,clock:()=> '2026-10-07T00:00:00.000Z'};const repo=createLocalRepository(options);const pet=await repo.savePet({name:'咪',type:'cat'});return {repo,pet,options};}
test('photo blob and metadata survive a new repository and temporary URLs never enter health',async()=>{const {repo,pet,options}=await setup(),asset=await repo.media.save({petId:pet.id,kind:'photo',blob:blob(),caption:'第一天'});const reopened=createLocalRepository(options),listed=await reopened.media.list({petId:pet.id});assert.equal(listed.items[0].id,asset.id);assert.equal((await reopened.media.read(asset.id)).blob.size,blob().size);const resolved=await reopened.media.resolveUrl(asset.id);assert.match(resolved.url,/^blob:/);assert.ok(!JSON.stringify(await reopened.snapshot()).includes('blob:'));resolved.release();resolved.release();});
test('parent trash hides reads yet restore preserves all photo bytes',async()=>{const {repo,pet}=await setup(),asset=await repo.media.save({petId:pet.id,kind:'photo',blob:blob()});await repo.moveToTrash({kind:'pet',ids:[pet.id]});assert.equal((await repo.media.list({petId:pet.id})).items.length,0);await assert.rejects(repo.media.read(asset.id));await repo.restoreFromTrash({kind:'pet',ids:[pet.id]});assert.equal((await repo.media.list({petId:pet.id})).items[0].id,asset.id);});
test('avatar replacement commits reference and removes prior independent asset',async()=>{const {repo,pet}=await setup(),one=await repo.media.save({petId:pet.id,kind:'avatar',blob:blob()}),two=await repo.media.save({petId:pet.id,kind:'avatar',blob:blob()});assert.equal((await repo.snapshot()).pets[0].avatarAssetId,two.id);await assert.rejects(repo.media.read(one.id));await repo.media.remove({assetId:two.id});assert.equal((await repo.snapshot()).pets[0].avatarAssetId,null);});
test('stale media writes and total quota failures preserve old avatar and revision',async()=>{const {repo,pet}=await setup(),asset=await repo.media.save({petId:pet.id,kind:'avatar',blob:blob()}),revision=repo.getRevision();await assert.rejects(repo.media.save({petId:pet.id,kind:'avatar',blob:blob(),baseRevision:revision-1}),{code:'CONFLICT'});assert.equal((await repo.snapshot()).pets[0].avatarAssetId,asset.id);const quota=createLocalRepository({indexedDB:new IDBFactory(),mediaMaxBytes:blob().size-1});const p=await quota.savePet({name:'A',type:'dog'});await assert.rejects(quota.media.save({petId:p.id,kind:'photo',blob:blob()}),/容量|配额/);assert.equal((await quota.media.list({petId:p.id})).items.length,0);assert.equal(quota.getRevision(),1);});
test('delete and upload retry operation ids do not duplicate photos or revisions',async()=>{const {repo,pet}=await setup(),input={petId:pet.id,kind:'photo',blob:blob(),operationId:'save-one'};const a=await repo.media.save(input),revision=repo.getRevision();assert.equal((await repo.media.save(input)).id,a.id);assert.equal(repo.getRevision(),revision);await assert.rejects(repo.media.save({...input,caption:'different'}),{code:'INVALID_INPUT'});await repo.media.remove({assetId:a.id,operationId:'delete-one'});const after=repo.getRevision();await repo.media.remove({assetId:a.id,operationId:'delete-one'});assert.equal(repo.getRevision(),after);await assert.rejects(repo.media.read(a.id));});
test('concurrent same-operation upload retries commit exactly once',async()=>{const {repo,pet}=await setup(),input={petId:pet.id,kind:'photo',blob:blob(),operationId:'parallel'};const before=repo.getRevision(),[a,b]=await Promise.all([repo.media.save(input),repo.media.save(input)]);assert.equal(a.id,b.id);assert.equal((await repo.media.list({petId:pet.id})).items.length,1);assert.equal(repo.getRevision(),before+1);});
test('quota transaction failure preserves repository cache, snapshot, media and blob; retry succeeds',async()=>{
  const indexedDB=new IDBFactory();let armed=false;
  const wrapped={open(name,version){const request=indexedDB.open(name,version);request.addEventListener('success',()=>{const db=request.result,transaction=db.transaction.bind(db);db.transaction=(...args)=>{const tx=transaction(...args),objectStore=tx.objectStore.bind(tx);tx.objectStore=name=>{const store=objectStore(name);if(name==='blobs'&&args[1]==='readwrite'){const put=store.put.bind(store);store.put=(...values)=>{const result=put(...values);if(armed){armed=false;throw new DOMException('disk full','QuotaExceededError');}return result;};}return store;};return tx;};});return request;}};
  const repo=createLocalRepository({indexedDB:wrapped}),pet=await repo.savePet({name:'咪',type:'cat'}),before=repo.getRevision();armed=true;
  await assert.rejects(repo.media.save({petId:pet.id,kind:'avatar',blob:blob()}),{code:'QUOTA_EXCEEDED'});
  assert.equal(repo.getRevision(),before);assert.equal((await repo.snapshot()).pets[0].avatarAssetId,null);assert.equal((await repo.media.listAll()).length,0);
  const asset=await repo.media.save({petId:pet.id,kind:'avatar',blob:blob()});assert.equal((await repo.media.read(asset.id)).blob.size,blob().size);
});
test('photo captions allow 200 characters and reject 201 with no mutation',async()=>{const {repo,pet}=await setup();await repo.media.save({petId:pet.id,kind:'photo',blob:blob(),caption:'字'.repeat(200)});const revision=repo.getRevision();await assert.rejects(repo.media.save({petId:pet.id,kind:'photo',blob:blob(),caption:'字'.repeat(201)}),{code:'INVALID_INPUT'});assert.equal(repo.getRevision(),revision);});
test('concurrent upload and remove retries with explicit old revision resolve receipt before CAS',async()=>{const {repo,pet}=await setup(),baseRevision=repo.getRevision(),input={petId:pet.id,kind:'photo',blob:blob(),operationId:'explicit-upload',baseRevision};const [a,b]=await Promise.all([repo.media.save(input),repo.media.save(input)]);assert.equal(a.id,b.id);const remove={assetId:a.id,operationId:'explicit-remove',baseRevision:repo.getRevision()};await Promise.all([repo.media.remove(remove),repo.media.remove(remove)]);assert.equal((await repo.media.listAll()).length,0);assert.equal(repo.getRevision(),baseRevision+2);});
test('pagination stays stable for equal creation times and avatars stay outside the photo wall',async()=>{const {repo,pet}=await setup();const a=await repo.media.save({petId:pet.id,kind:'photo',blob:blob()}),b=await repo.media.save({petId:pet.id,kind:'photo',blob:blob()});await repo.media.save({petId:pet.id,kind:'avatar',blob:blob()});const first=await repo.media.list({petId:pet.id,limit:1}),second=await repo.media.list({petId:pet.id,limit:1,cursor:first.nextCursor});assert.deepEqual([first.items[0].id,second.items[0].id],[a.id,b.id].sort());assert.equal(second.nextCursor,null);});

test('separate media options enforce CAS and override legacy input options',async()=>{
 const {repo,pet,options}=await setup(),avatar=await repo.media.save({petId:pet.id,kind:'avatar',blob:blob()}),stale=repo.getRevision();await repo.saveProfile({city:'新版'});const revision=repo.getRevision(),before=await repo.snapshot();
 await assert.rejects(repo.media.save({petId:pet.id,kind:'avatar',blob:blob(),baseRevision:revision},{baseRevision:stale}),{code:'CONFLICT'});
 await assert.rejects(repo.media.remove({assetId:avatar.id,baseRevision:revision},{baseRevision:stale}),{code:'CONFLICT'});
 assert.deepEqual(await repo.snapshot(),before);assert.equal(repo.getRevision(),revision);assert.equal((await createLocalRepository(options).media.read(avatar.id)).blob.size,blob().size);
 const saved=await repo.media.save({petId:pet.id,kind:'photo',blob:blob(),baseRevision:stale},{baseRevision:revision,operationId:'new-options'});assert.ok(saved.id);
});
