import test from 'node:test';
import assert from 'node:assert/strict';
let domain={};try{domain=await import('../src/domain/public-profile.js');}catch(e){if(e.code!=='ERR_MODULE_NOT_FOUND')throw e;}
const validate=(...args)=>{assert.equal(typeof domain.validateProfileInput,'function','profile validation must exist');return domain.validateProfileInput(...args);};
test('public profile defaults to private discovery and normalizes text',()=>{assert.deepEqual(validate({nickname:' 合成昵称 '}),{nickname:'合成昵称',avatarAssetId:null,bio:'',cityId:null,districtId:null,petTypes:[],purposes:[],discoverable:false});});
test('joining discovery requires city pet type and purpose',()=>{for(const value of [{nickname:'A',discoverable:true},{nickname:'A',discoverable:true,cityId:'310100',petTypes:['cat']}])assert.throws(()=>validate(value),e=>e.code==='INVALID_INPUT');assert.equal(validate({nickname:'A',discoverable:true,cityId:'310100',petTypes:['cat'],purposes:['新手互助']}).discoverable,true);});
test('profile accepts only editable fields and rejects forged identities',()=>{for(const extra of [{ownerId:'B'},{email:'b@example.com'},{authorId:'B'},{nickname:'x'.repeat(31)},{bio:'x'.repeat(121)},{petTypes:['fish']},{purposes:['other']},{discoverable:'true'}])assert.throws(()=>validate({nickname:'A',...extra}),e=>e.code==='INVALID_INPUT');});
test('public projections cannot carry owner email tokens or private snapshot',()=>{assert.equal(typeof domain.publicIdentity,'function');assert.equal(typeof domain.discoverableProfile,'function');const profile={authorId:'author-A',nickname:'A',avatarAssetId:null,bio:'Hi',cityId:'310100',cityName:'上海市',districtId:null,districtName:null,petTypes:['cat'],purposes:['新手互助'],discoverable:true,ownerId:'PRIVATE',email:'PRIVATE',authToken:'PRIVATE',snapshot:{}};assert.deepEqual(domain.publicIdentity(profile),{authorId:'author-A',nickname:'A',avatarAssetId:null});assert.equal(JSON.stringify(domain.discoverableProfile(profile)).includes('PRIVATE'),false);});
test('profile validation identifies the first invalid field without exposing supplied values',()=>{
 for(const [changes,field,reason] of [[{nickname:'   '},'nickname','required'],[{nickname:'x'.repeat(31)},'nickname','length'],[{bio:'x'.repeat(121)},'bio','length'],[{discoverable:true},'cityId','required'],[{discoverable:true,cityId:'310100'},'petTypes','required'],[{discoverable:true,cityId:'310100',petTypes:['cat']},'purposes','required'],[{districtId:'310101'},'cityId','required'],[{cityId:'非法城市'},'cityId','invalid']]){
  assert.throws(()=>validate({nickname:'A',...changes}),e=>e.code==='INVALID_INPUT'&&e.field===field&&e.messageKey===`profile.${field}.${reason}`);
 }
});
