import test from 'node:test';import assert from 'node:assert/strict';import {webcrypto} from 'node:crypto';import {IDBFactory} from 'fake-indexeddb';import {createLocalRepository} from '../src/data/local-repository.js';import {createRequire} from 'node:module';
const d=await import('../src/domain/recap-facts.js').catch(()=>({}));const require=createRequire(import.meta.url),{handleRequest}=require('../backend/api.cjs'),{memoryStore}=require('./helpers/cloud-memory.cjs');
async function fixture(){let n=0;const opts={indexedDB:new IDBFactory(),clock:()=> '2026-10-07T01:00:00.000Z',idFactory:()=>`r${++n}`},repo=createLocalRepository(opts),pet=await repo.savePet({name:'咪',type:'cat'});await repo.saveRecord({petId:pet.id,type:'weight',occurredDate:'2026-10-01',value:4.61});await repo.saveRecord({petId:pet.id,type:'weight',occurredDate:'2026-10-07',value:4.7});const reminder=await repo.saveReminder({petId:pet.id,title:'护理',dueDate:'2026-10-07'});await repo.completeReminder(reminder.id,{occurredDate:'2026-10-07'});await repo.saveReminder({petId:pet.id,title:'下一次',dueDate:'2026-10-14'});await repo.saveReminder({petId:pet.id,title:'过远',dueDate:'2026-10-15'});return {repo,pet,opts};}
test('recap facts include both boundary days, round weights and use completed real reminders',async()=>{
 assert.equal(typeof d.computeRecapFacts,'function');const {repo,pet}=await fixture(),snapshot=await repo.snapshot(),facts=d.computeRecapFacts({snapshot,petId:pet.id,from:'2026-10-01',to:'2026-10-07'});assert.equal(facts.recordCount,3);assert.equal(facts.weightChangeKg,0.09);assert.equal(facts.completedCareCount,1);assert.equal(facts.upcomingReminders.length,1);assert.equal(facts.upcomingReminders[0].dueDate,'2026-10-14');
 const source=await d.recapSourceHash({snapshot,petId:pet.id,from:'2026-10-01',to:'2026-10-07'},{cryptoImpl:webcrypto});await repo.saveRecord({petId:pet.id,type:'daily',occurredDate:'2026-10-03',title:'补录'});assert.notEqual(await d.recapSourceHash({snapshot:await repo.snapshot(),petId:pet.id,from:'2026-10-01',to:'2026-10-07'},{cryptoImpl:webcrypto}),source);
 await repo.moveToTrash({kind:'pet',ids:[pet.id]});assert.throws(()=>d.computeRecapFacts({snapshot:awaitSnapshot,petId:pet.id,from:'2026-10-01',to:'2026-10-07'}),/宠物/);
});const awaitSnapshot={pets:[],records:[],reminders:[]};
test('private recap save recomputes facts, rejects stale basis and share strips health through template',async()=>{
 const {repo,pet,opts}=await fixture(),snapshot=await repo.snapshot(),scope={snapshot,petId:pet.id,from:'2026-10-01',to:'2026-10-07'},facts=d.computeRecapFacts(scope),sourceHash=await d.recapSourceHash(scope);const recap={id:'recap-1',petId:pet.id,from:scope.from,to:scope.to,generatedAt:'2026-10-07T01:00:00.000Z',sourceHash,recordIds:facts.recordIds,reminderIds:facts.reminderIds,facts:{...facts,recordCount:999},story:'体重4.7kg，护理吃了药。',storySources:[facts.recordIds[0]],uiLocale:'zh-CN'};
 assert.equal(typeof repo.saveRecap,'function');const saved=await repo.saveRecap(recap);assert.equal(saved.facts.recordCount,3);assert.equal((await createLocalRepository(opts).snapshot()).profile.stage3.recaps.length,1);const share=d.prepareRecapShare(saved,{includeWeights:false});assert.ok(!share.text.includes('4.7'));assert.ok(!share.text.includes('药'));assert.ok(share.text.includes('2026-10-01'));
 await repo.saveRecord({petId:pet.id,type:'daily',occurredDate:'2026-10-03',title:'补录'});await assert.rejects(repo.saveRecap(recap),/更新|过时/);
});
test('cloud stage3 owned actions cannot reference another account',async()=>{
 const store=memoryStore();let n=0;const run=(user,action,payload,revision)=>handleRequest({version:1,action,payload,expectedRevision:revision,idempotencyKey:`op${++n}`},{principal:{userId:user,emailVerified:true,isAnonymous:false},store,clock:()=> '2026-10-07T01:00:00.000Z',idFactory:()=>`e${++n}`});const p=await run('A','pets.save',{name:'咪',type:'cat'},0);const progress={petId:p.data.id,step:'record',recordIds:[],reminderId:null,updatedAt:'2026-10-01T00:00:00.000Z'};const a=await run('A','stage3.onboarding.save',progress,1);assert.equal(a.ok,true);assert.equal(a.data.updatedAt,'2026-10-07T01:00:00.000Z');const b=await run('B','stage3.onboarding.save',progress,0);assert.equal(b.error.code,'FORBIDDEN');
});
test('cloud recap derives trusted facts and rejects foreign or changed basis',async()=>{
 const store=memoryStore();let n=0;const run=(user,action,payload,revision)=>handleRequest({version:1,action,payload,expectedRevision:revision,idempotencyKey:`recap-op${++n}`},{principal:{userId:user,emailVerified:true,isAnonymous:false},store,clock:()=> '2026-10-07T01:00:00.000Z',idFactory:()=>`recap-e${++n}`});const pet=await run('A','pets.save',{name:'咪',type:'cat'},0),record=await run('A','records.save',{petId:pet.data.id,type:'daily',occurredDate:'2026-10-06',title:'玩耍'},1),scope={snapshot:record.snapshot,petId:pet.data.id,from:'2026-10-01',to:'2026-10-07'},facts=d.computeRecapFacts(scope),recap={id:'cloud-recap',petId:scope.petId,from:scope.from,to:scope.to,generatedAt:'2026-10-07T01:00:00.000Z',sourceHash:await d.recapSourceHash(scope,{cryptoImpl:webcrypto}),recordIds:facts.recordIds,reminderIds:facts.reminderIds,facts:{...facts,recordCount:999},story:'今天一起记录生活。',storySources:facts.recordIds,uiLocale:'zh-CN'};const saved=await run('A','stage3.recap.save',recap,2);assert.equal(saved.ok,true);assert.equal(saved.data.facts.recordCount,1);assert.equal((await run('B','stage3.recap.save',recap,0)).error.code,'FORBIDDEN');await run('A','records.save',{id:record.data.id,title:'改了记录'},3);assert.equal((await run('A','stage3.recap.save',recap,4)).error.code,'INVALID_INPUT');
});
test('hidden completion record removes completed care fact and invalidates basis even outside record date range',async()=>{
 const {repo,pet}=await fixture();const origin=await repo.saveRecord({petId:pet.id,type:'deworm',occurredDate:'2026-10-01',title:'护理',nextDate:'2026-10-07'});const pending=(await repo.snapshot()).reminders.find(r=>r.originRecordId===origin.id);await repo.completeReminder(pending.id,{occurredDate:'2026-10-07'});const reminder=(await repo.snapshot()).reminders.find(r=>r.id===pending.id);await repo.saveRecord({id:reminder.completionRecordId,occurredDate:'2026-09-30'});const scope={snapshot:await repo.snapshot(),petId:pet.id,from:'2026-10-01',to:'2026-10-07'};assert.equal(d.computeRecapFacts(scope).completedCareCount,2);const before=await d.recapSourceHash(scope);await repo.moveToTrash({kind:'record',ids:[reminder.completionRecordId]});const after={...scope,snapshot:await repo.snapshot()};assert.equal(d.computeRecapFacts(after).completedCareCount,1);assert.notEqual(await d.recapSourceHash(after),before);
});
