import {inspectAttachmentBlob} from '../media/attachments.js';
const escape=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const copy=locale=>['en','en-US'].includes(locale)?{label:'Attachments · optional',hint:'Up to 3 original images or PDFs, 5 MiB each.',upload:'Choose files',remove:'Remove',read:'View',download:'Download',confirm:'Delete this attachment?',failed:'Upload failed. Your record was saved; retry the remaining attachments.',limit:'Up to 3 attachments per record.'}:{label:'附件 · 可选',hint:'最多3个图片或PDF，单个不超过5MiB，保留原文件。',upload:'选择文件',remove:'删除',read:'查看',download:'下载',confirm:'删除这个附件？',failed:'附件上传失败，记录已保存；可重试剩余附件。',limit:'每项最多3个附件。'};
export function attachmentPickerMarkup({locale='zh-CN'}={}){const t=copy(locale);return `<section class="attachment-picker" data-attachment-picker><label>${t.label}<input type="file" data-attachment-input accept="image/jpeg,image/png,image/webp,application/pdf" multiple></label><small>${t.hint}</small><div data-attachment-items></div><p data-attachment-error role="status"></p></section>`;}
export function createAttachmentPicker({root,repository,petId,parentKind='record',parentId=null,locale='zh-CN',onChanged=async()=>{}}={}){
 const host=root.matches?.('[data-attachment-picker]')?root:root.querySelector('[data-attachment-picker]');if(!host)return null;
 const input=host.querySelector('[data-attachment-input]'),items=host.querySelector('[data-attachment-items]'),message=host.querySelector('[data-attachment-error]'),pending=[],urls=new Set();let t=copy(locale),existing=[],disposed=false,busy=false;
 const release=url=>{if(url){URL.revokeObjectURL(url);urls.delete(url);}};
 const error=e=>{message.textContent=e?.message??String(e);};
 const render=()=>{if(disposed)return;items.innerHTML=[...existing.map(a=>`<div class="attachment-item"><button type="button" data-attachment-open="${escape(a.id)}">${escape(a.filename)} · ${t.read}</button><button type="button" data-attachment-download="${escape(a.id)}">${t.download}</button><button type="button" data-attachment-remove="${escape(a.id)}">${t.remove}</button></div>`),...pending.map((a,i)=>`<div class="attachment-item">${a.preview?`<img src="${escape(a.preview)}" alt="${escape(a.file.name)}" style="width:48px;height:48px;object-fit:cover;border-radius:8px">`:""}<span>${escape(a.file.name)} · ${(a.file.size/1024).toFixed(0)} KB</span><button type="button" data-attachment-drop="${i}">${t.remove}</button></div>`)].join('');input.disabled=busy||existing.length+pending.length>=3;for(const button of items.querySelectorAll("button"))button.disabled=busy;};
 const load=async()=>{if(parentId&&repository?.attachments){existing=(await repository.attachments.list({petId,parentKind,parentId})).items;render();}};
 const change=async()=>{message.textContent='';try{const files=[...input.files];if(existing.length+pending.length+files.length>3)throw new Error(t.limit);for(const file of files)await inspectAttachmentBlob(file);if(disposed)return;pending.push(...files.map(file=>{const preview=file.type.startsWith('image/')?URL.createObjectURL(file):null;if(preview)urls.add(preview);return {file,preview,operationId:crypto.randomUUID()};}));render();}catch(e){error(e);}finally{input.value='';}};
 const click=async event=>{const target=event.target.closest('button');if(!target)return;try{if(target.dataset.attachmentDrop!==undefined){const item=pending.splice(Number(target.dataset.attachmentDrop),1)[0];release(item?.preview);render();}else if(target.dataset.attachmentRemove){if(!globalThis.confirm(t.confirm))return;await repository.attachments.remove({assetId:target.dataset.attachmentRemove});await onChanged();await load();}else if(target.dataset.attachmentOpen||target.dataset.attachmentDownload){const download=!!target.dataset.attachmentDownload,id=target.dataset.attachmentOpen??target.dataset.attachmentDownload,asset=existing.find(x=>x.id===id),tab=download?null:globalThis.open('about:blank','_blank');if(tab)tab.opener=null;try{const {blob}=await repository.attachments.read(asset.id);if(disposed){tab?.close();return;}const url=URL.createObjectURL(blob);urls.add(url);if(download){const a=document.createElement('a');a.href=url;a.download=asset.filename;a.click();}else if(tab)tab.location.href=url;else throw new Error(locale==='en'?'Please allow opening the attachment window.':'请允许打开附件窗口。');setTimeout(()=>release(url),30000);}catch(e){tab?.close();throw e;}}}catch(e){error(e);}};
 input.addEventListener('change',change);items.addEventListener('click',click);load().catch(error);
 return {
 async save(parent={}){parentKind=parent.parentKind??parentKind;parentId=parent.parentId??parentId;if(!pending.length)return existing;if(!parentId)throw new Error('附件需要已保存的记录');if(!repository.attachments)throw new Error(['en','en-US'].includes(locale)?'Switch to your personal archive to add attachments.':'请切换到个人档案后添加附件');busy=true;render();try{for(const item of [...pending]){if(disposed)throw new Error('附件操作已取消');try{const saved=await repository.attachments.save({petId,parentKind,parentId,blob:item.file,filename:item.file.name,operationId:item.operationId});if(disposed)throw new Error('附件操作已取消');existing.push(saved);pending.splice(pending.indexOf(item),1);release(item.preview);render();}catch(e){error(new Error(t.failed));throw e;}}return existing;}finally{busy=false;render();}},
 setLocale(next){locale=next;t=copy(locale);const label=host.querySelector('label');if(label)for(const node of label.childNodes)if(node.nodeType===3)node.textContent=t.label;const hint=host.querySelector('small');if(hint)hint.textContent=t.hint;render();},
 get pendingCount(){return pending.length;},get parentId(){return parentId;},refresh:load,
 dispose(){disposed=true;input.removeEventListener('change',change);items.removeEventListener('click',click);for(const url of urls)URL.revokeObjectURL(url);urls.clear();pending.length=0;}
 };
}
