import {getLocale} from './i18n.js';
const text=(zh,en)=>getLocale()==='en'?en:zh;
export function focusDialogTitle(dialog){const title=dialog.querySelector('#dialog-title');title?.setAttribute('tabindex','-1');title?.focus({preventScroll:true});}
export function createPetAvatarSave({savePet,saveAvatar}){let savedPet=null;return {getSavedPet:()=>savedPet,async save(input,selection){if(!savedPet)savedPet=await savePet(input);if(selection.kind!=='keep')await saveAvatar(savedPet,selection);return savedPet;}};}
export function mountAvatarPicker({root,petType,initialAvatar,onChange=()=>{},onError=()=>{}}){
 let manual=false,selection=initialAvatar?{kind:'keep'}:['cat','dog'].includes(petType)?{kind:'preset',preset:petType}:{kind:'keep'},preview=initialAvatar??'',url=null,turn=0,preparing=false;
 root.innerHTML=`<div class="avatar-choices" role="group" aria-label="${text('宠物头像','Pet avatar')}"><button type="button" class="avatar-choice" data-avatar-preset="cat" aria-label="${text('猫咪照片','Cat photo')}"><img src="assets/cat.jpg" alt=""></button><button type="button" class="avatar-choice" data-avatar-preset="dog" aria-label="${text('狗狗照片','Dog photo')}"><img src="assets/dog.jpg" alt=""></button><button type="button" class="avatar-choice avatar-upload" data-avatar-upload aria-label="${text('上传头像','Upload avatar')}"><svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M12 5v14M5 12h14"/></svg></button><input type="file" data-avatar-file accept="image/jpeg,image/png,image/webp" hidden></div><p class="demo-note" data-avatar-note>${text('可选现成照片或上传，保存档案时才保存头像。','Choose a photo or upload; the avatar is saved with the profile.')}</p>`;
 const update=()=>{for(const button of root.querySelectorAll('[data-avatar-preset]'))button.setAttribute('aria-pressed',String(selection.kind==='preset'&&selection.preset===button.dataset.avatarPreset));const upload=root.querySelector('[data-avatar-upload]');upload.setAttribute('aria-pressed',String(selection.kind==='upload'||selection.kind==='keep'&&Boolean(preview)));upload.innerHTML=preview&&selection.kind!=='preset'?`<img alt="" src="${preview}">`:'<svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M12 5v14M5 12h14"/></svg>';};
 root.addEventListener('click',event=>{const preset=event.target.closest('[data-avatar-preset]');if(preset){manual=true;selection={kind:'preset',preset:preset.dataset.avatarPreset};turn++;preparing=false;update();onChange(selection);}if(event.target.closest('[data-avatar-upload]'))root.querySelector('[data-avatar-file]').click();});
 root.querySelector('[data-avatar-file]').addEventListener('change',async event=>{const file=event.target.files[0];if(!file)return;manual=true;preparing=true;const ticket=++turn;try{const {processImage}=await import('../media/process-image.js');const preparedImage=await processImage(file,{kind:'avatar'});if(ticket!==turn||!root.isConnected)return;if(url)URL.revokeObjectURL(url);url=URL.createObjectURL(preparedImage.blob);preview=url;selection={kind:'upload',blob:preparedImage.blob,preparedImage};update();onChange(selection);}catch(error){if(ticket===turn)onError(error);}finally{if(ticket===turn)preparing=false;}});
 function refreshLocale(){root.querySelector('[role=group]').setAttribute('aria-label',text('宠物头像','Pet avatar'));root.querySelector('[data-avatar-preset=cat]').setAttribute('aria-label',text('猫咪照片','Cat photo'));root.querySelector('[data-avatar-preset=dog]').setAttribute('aria-label',text('狗狗照片','Dog photo'));root.querySelector('[data-avatar-upload]').setAttribute('aria-label',text('上传头像','Upload avatar'));root.querySelector('[data-avatar-note]').textContent=text('可选现成照片或上传，保存档案时才保存头像。','Choose a photo or upload; the avatar is saved with the profile.');}
 update();return {getSelection:()=>selection,isPreparing:()=>preparing,refreshLocale,setPetType(type){if(manual||initialAvatar)return;selection=['cat','dog'].includes(type)?{kind:'preset',preset:type}:{kind:'keep'};update();},destroy(){turn++;if(url)URL.revokeObjectURL(url);}};
}
