const escape=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function mountRecordDialog({host,petId,type='daily',purpose='record',existing=null,reminder=null,completion=null,today,getLocale=()=> 'zh-CN',getEntries,enhanceType,enhanceAll,onSubmit,onAi,attachmentMarkup='',mountAttachments}={}){
 const copy=(zh,en)=>getLocale()==='en'?en:zh;
 const field=(label,input,extra='')=>`<label class="field ${extra}"><span>${escape(label)}</span>${input}</label>`;
 let joinTouched=false,aiMounted=false,selectedMode='manual',picker=null;
 const record=existing,initialType=record?.customTypeId??reminder?.customTypeId??((record?.type??reminder?.recordType)==='other'?'historical:other':record?.type??reminder?.recordType??type);
 const entries=getEntries(),selected=entries.find(e=>e.id===initialType)??entries.find(e=>e.type===record?.type)??entries[0];
 host.innerHTML=`<div class="record-mode-tabs" role="group" aria-label="${copy('录入方式','Entry mode')}"><button type="button" class="record-mode-button active" data-action="record-mode" data-value="manual" aria-pressed="true">${copy('手动填写','Manual entry')}</button><button type="button" class="record-mode-button" data-action="record-mode" data-value="ai" aria-pressed="false">${copy('一句话记入','Write a sentence')}<small>${copy('AI智能生成','AI generated')}</small></button></div><form id="record-form"><div class="form-grid">${field(copy('用途','Purpose'),`<select id="record-purpose" name="purpose"><option value="record" ${purpose==='record'?'selected':''}>${copy('记录已发生','Record an event')}</option><option value="plan" ${purpose==='plan'?'selected':''}>${copy('安排计划','Schedule a plan')}</option></select>`)}${field(copy('记录类型','Record type'),`<select name="type" id="record-type">${entries.map(e=>`<option value="${escape(e.id)}" data-icon="${escape(e.iconKey)}" ${e.id===selected?.id?'selected':''}>${escape(e.builtin?copy(e.name,{weight:'Weight',vaccine:'Vaccination',deworm:'Deworming',daily:'Daily'}[e.id]):e.name)}</option>`).join('')}</select>`)}${field(copy('发生日期','Event date'),`<input name="date" type="date" value="${escape(record?.date??record?.occurredDate??today)}" max="${today}">`,'event-date-field')}${field(copy('计划日期','Planned date'),`<input name="dueDate" type="date" value="${escape(reminder?.dueDate??'')}">`,'plan-date-field')}<div id="record-value-field" class="field full">${field(copy('体重（kg）','Weight (kg)'),`<input name="value" type="number" inputmode="decimal" min="0.01" max="200" step="0.01" value="${record?.value??''}" placeholder="4.6">`)}</div>${field(copy('记录名称','Title'),`<input name="title" maxlength="60" value="${escape(record?.title??reminder?.title??(selected?.type==='weight'?copy('体重记录','Weight record'):''))}" required>`,'full')}<label class="record-todo-choice full"><input type="checkbox" name="joinTodo" ${['vaccine','deworm'].includes(selected?.type)||reminder?.originRecordId?'checked':''}> ${copy('同时加入健康待办','Also add to health to-dos')}</label>${field(copy('下次计划日期','Next planned date'),`<input name="nextDate" type="date" value="${escape(reminder?.originRecordId?reminder.dueDate:'')}">`,'next-date-field full')}${field(copy('备注 · 可选','Note · optional'),`<textarea name="note" maxlength="500">${escape(record?.note??reminder?.note??'')}</textarea>`,'full')}</div>${attachmentMarkup}<p class="form-tip">${copy('发生记录和未来计划分别保存，日期由你决定。','Events and plans are saved separately. You choose the dates.')}</p><p class="form-error" role="alert" hidden></p><div class="form-actions"><button type="button" class="button secondary" data-action="close">${copy('取消','Cancel')}</button><button type="submit" class="button">${copy('保存','Save')}</button></div></form><section id="record-ai-panel" hidden></section>`;
 const form=host.querySelector('#record-form'),purposeSelect=form.querySelector('#record-purpose'),typeSelect=form.querySelector('#record-type'),join=form.querySelector('[name=joinTodo]');
 if(existing||reminder?.id)purposeSelect.disabled=true;
 if(completion){purposeSelect.value='record';purposeSelect.disabled=true;typeSelect.disabled=true;join.checked=false;}
 if(existing&&reminder?.originRecordId)join.checked=true;else if(existing)join.checked=false;
 function refresh(){const plan=purposeSelect.value==='plan',entry=getEntries().find(e=>e.id===typeSelect.value);form.querySelector('.event-date-field').hidden=plan;form.querySelector('[name=date]').required=!plan;form.querySelector('[name=date]').disabled=plan;form.querySelector('.plan-date-field').hidden=!plan;form.querySelector('[name=dueDate]').required=plan;form.querySelector('[name=dueDate]').disabled=!plan;form.querySelector('#record-value-field').hidden=plan||entry?.type!=='weight';form.querySelector('[name=value]').required=!plan&&entry?.type==='weight';form.querySelector('[name=value]').disabled=plan||entry?.type!=='weight';form.querySelector('.record-todo-choice').hidden=plan;form.querySelector('.next-date-field').hidden=plan||!join.checked;form.querySelector('[name=nextDate]').required=!plan&&join.checked;form.querySelector('[name=nextDate]').disabled=plan||!join.checked;}
 purposeSelect.addEventListener('change',refresh);typeSelect.addEventListener('change',()=>{const entry=getEntries().find(e=>e.id===typeSelect.value);if(!joinTouched)join.checked=['vaccine','deworm'].includes(entry?.type);if(entry?.type==='weight'&&!form.querySelector('[name=title]').value.trim())form.querySelector('[name=title]').value=copy('体重记录','Weight record');refresh();});join.addEventListener('change',()=>{joinTouched=true;refresh();});
 enhanceType?.(typeSelect);enhanceAll?.();refresh();picker=mountAttachments?.(form);
 const api={form,picker,getState:()=>({mode:selectedMode,purpose:purposeSelect.value}),refreshLocale(){picker?.setLocale?.(getLocale());host.querySelector('[data-value=manual]').textContent=copy('手动填写','Manual entry');host.querySelector('[data-value=ai]').innerHTML=copy('一句话记入','Write a sentence')+'<small>'+copy('AI智能生成','AI generated')+'</small>';const label=form.querySelector('.record-todo-choice');for(const node of label.childNodes)if(node.nodeType===3)node.textContent=' '+copy('同时加入健康待办','Also add to health to-dos');},setMode(mode){selectedMode=mode;for(const b of host.querySelectorAll('[data-action=record-mode]')){b.classList.toggle('active',b.dataset.value===mode);b.setAttribute('aria-pressed',String(b.dataset.value===mode));}form.hidden=mode==='ai';const panel=host.querySelector('#record-ai-panel');panel.hidden=mode!=='ai';if(mode==='ai'&&!aiMounted){onAi?.(panel,()=>purposeSelect.value);aiMounted=true;}},destroy(){picker?.dispose?.();}};
 form.addEventListener('submit',event=>{event.preventDefault();const d=new FormData(form);onSubmit?.(form,{purpose:purposeSelect.value,type:typeSelect.value,petId,id:record?.id??reminder?.id,date:d.get('date'),dueDate:d.get('dueDate'),joinTodo:join.checked,value:d.get('value'),title:d.get('title'),note:d.get('note'),nextDate:d.get('nextDate')},api);});
 return api;
}
