import {isHealthTodo} from '../domain/health-plans.js';
import {mountRecordFields} from './record-fields.js';
export function mountRecordDialog({host,petId,type='daily',purpose='record',existing=null,reminder=null,completion=null,today,getLocale=()=> 'zh-CN',getEntries,enhanceType,enhanceAll,onSubmit,onAi,attachmentMarkup='',mountAttachments}={}){
 const copy=(zh,en)=>getLocale()==='en'?en:zh;
 let aiMounted=false,selectedMode='manual',picker=null;
 const record=existing,initialType=record?.customTypeId??reminder?.customTypeId??((record?.type??reminder?.recordType)==='other'?'historical:other':record?.type??reminder?.recordType??type);
 host.innerHTML=`<div class="record-mode-tabs" role="group" aria-label="${copy('录入方式','Entry mode')}"><button type="button" class="record-mode-button active" data-action="record-mode" data-value="manual" aria-pressed="true">${copy('手动填写','Manual entry')}</button><button type="button" class="record-mode-button" data-action="record-mode" data-value="ai" aria-pressed="false">${copy('一句话记入','Write a sentence')}<small>${copy('AI智能生成','AI generated')}</small></button></div><form id="record-form"><div class="form-grid" data-record-fields></div>${attachmentMarkup}<p class="form-tip" data-record-dialog-tip>${copy('已发生只保存成长记录；未来事项请使用安排计划。','Events are saved as records. Use Schedule a plan for future to-dos.')}</p><p class="form-error" role="alert" hidden></p><div class="form-actions"><button type="button" class="button secondary" data-action="close">${copy('取消','Cancel')}</button><button type="submit" class="button">${copy('保存','Save')}</button></div></form><section id="record-ai-panel" hidden></section>`;
 const form=host.querySelector('#record-form');
 const fields=mountRecordFields({root:form.querySelector('[data-record-fields]'),idPrefix:'record',values:{purpose:completion?'record':purpose,type:initialType,petId,date:record?.date??record?.occurredDate??today,dueDate:reminder?.dueDate??'',value:record?.value??'',title:record?.title??reminder?.title??'',note:record?.note??reminder?.note??'',...(reminder?.id?{includeInHealth:isHealthTodo(reminder)}:{})},today,getLocale,getEntries,enhanceType,enhanceAll,lockPurpose:!!(existing||reminder?.id||completion),lockType:!!completion});
 const purposeSelect=form.querySelector('#record-purpose');
 picker=mountAttachments?.(form);
 const api={form,picker,fields,getState:()=>({mode:selectedMode,purpose:purposeSelect.value}),refreshLocale(){fields.refreshLocale();picker?.setLocale?.(getLocale());host.querySelector('[data-value=manual]').textContent=copy('手动填写','Manual entry');host.querySelector('[data-value=ai]').innerHTML=copy('一句话记入','Write a sentence')+'<small>'+copy('AI智能生成','AI generated')+'</small>';host.querySelector('[data-record-dialog-tip]').textContent=copy('已发生只保存成长记录；未来事项请使用安排计划。','Events are saved as records. Use Schedule a plan for future to-dos.');},setMode(mode){selectedMode=mode;for(const b of host.querySelectorAll('[data-action=record-mode]')){b.classList.toggle('active',b.dataset.value===mode);b.setAttribute('aria-pressed',String(b.dataset.value===mode));}form.hidden=mode==='ai';const panel=host.querySelector('#record-ai-panel');panel.hidden=mode!=='ai';if(mode==='ai'&&!aiMounted){onAi?.(panel,()=>purposeSelect.value);aiMounted=true;}},destroy(){fields.destroy();picker?.dispose?.();}};
 form.addEventListener('submit',event=>{event.preventDefault();onSubmit?.(form,{...fields.read(),petId,id:record?.id??reminder?.id},api);});
 return api;
}
