import {createLocationSuggest} from '../features/location-suggest.js';
const error=code=>Object.assign(new Error(code),{code});
export function createRegionPicker({repository,initialValue={},onChange=()=>{},getGeneration=()=>0,onState=()=>{}}={}){
 let value={cityId:null,districtId:null,cityName:null,districtName:null,...initialValue},cities=[],districts=[],nextCursor=null,meta=null,query='',searchTurn=0,districtTurn=0,disposed=false;
 const getValue=()=>({...value}),getState=()=>({value:getValue(),cities:[...cities],districts:[...districts],nextCursor,meta});
 const notify=()=>{if(!disposed)onState(getState());};
 return {
  getValue,getState,
  async searchCities(nextQuery='',{more=false}={}){const turn=++searchTurn,generation=getGeneration();query=nextQuery;const reply=await repository.request('regions.search',{query,level:'city',limit:50,...(more&&nextCursor?{cursor:nextCursor}:{})});if(disposed||turn!==searchTurn||generation!==getGeneration())return;cities=more?[...cities,...reply.items.filter(r=>!cities.some(c=>c.id===r.id))]:reply.items;nextCursor=reply.nextCursor;meta={version:reply.version,updatedAt:reply.updatedAt,stale:reply.stale};notify();return getState();},
  async selectCity(city){if(disposed)return;value={cityId:city?.id??null,districtId:null,cityName:city?.name??null,districtName:null};districts=[];nextCursor=null;const turn=++districtTurn,generation=getGeneration();onChange(getValue());notify();if(!city)return;const reply=await repository.request('regions.children',{parentId:city.id});if(disposed||turn!==districtTurn||generation!==getGeneration())return;districts=reply.items;notify();return getState();},
  selectDistrict(id){if(disposed)return;const found=districts.find(r=>r.id===id&&r.parentId===value.cityId);if(id&&!found)throw error('INVALID_INPUT');value={...value,districtId:found?.id??null,districtName:found?.name??null};onChange(getValue());notify();},
  async applySuggestion(suggestion){if(disposed||!suggestion?.cityId)return;const city={id:suggestion.cityId,name:suggestion.cityName};value={...value,...suggestion};cities= cities.some(r=>r.id===city.id)?cities:[city,...cities];const turn=++districtTurn,generation=getGeneration();onChange(getValue());notify();const reply=await repository.request('regions.children',{parentId:city.id});if(disposed||turn!==districtTurn||generation!==getGeneration())return;districts=reply.items;notify();},
  async restoreDistricts(){if(!value.cityId||disposed)return;const turn=++districtTurn,generation=getGeneration(),reply=await repository.request('regions.children',{parentId:value.cityId});if(disposed||turn!==districtTurn||generation!==getGeneration())return;districts=reply.items;notify();},
  destroy(){disposed=true;searchTurn++;districtTurn++;cities=[];districts=[];},
 };
}
export function mountRegionPicker({root,container=root,repository,initialValue={},onChange=()=>{},onError=()=>{},getLocale=()=> 'zh-CN',locale,getGeneration=()=>0,allowEmpty=true,locationSuggest,visitorId}={}){
 root=container;if(!root)throw error('INVALID_INPUT');const doc=root.ownerDocument,en=(typeof locale==='string'?locale:getLocale())==='en',text=(zh,english)=>en?english:zh;
 root.innerHTML=`<div class="form-grid region-picker"><label class="field full"><span>${text('搜索城市','Search city')}</span><input type="search" data-region-query maxlength="80" autocomplete="off"></label><label class="field"><span>${text('城市','City')}</span><select data-region-city></select></label><label class="field"><span>${text('行政区 · 可选','District · optional')}</span><select data-region-district></select></label></div><p class="form-tip" data-region-status role="status"></p><div class="region-picker-actions"><button type="button" class="text-button" data-region-more hidden>${text('更多城市','More cities')}</button><button type="button" class="text-button" data-region-retry hidden>${text('重新读取地域','Retry regions')}</button><button type="button" class="text-button" data-region-locate>${text('用当前位置建议地区','Suggest my region')}</button><button type="button" class="text-button" data-region-confirm hidden></button></div>`;
 const query=root.querySelector('[data-region-query]'),city=root.querySelector('[data-region-city]'),district=root.querySelector('[data-region-district]'),status=root.querySelector('[data-region-status]'),more=root.querySelector('[data-region-more]'),retry=root.querySelector('[data-region-retry]'),locate=root.querySelector('[data-region-locate]'),confirm=root.querySelector('[data-region-confirm]');let disposed=false,debounce=null,suggestion=null;
 const option=(value,label)=>{const node=doc.createElement('option');node.value=value;node.textContent=label;return node;};
 function render(state){if(disposed)return;const current=state.value,cityOptions=[option('',text(allowEmpty?'未选择':'请选择城市',allowEmpty?'Not selected':'Choose a city'))];if(current.cityId&&!state.cities.some(c=>c.id===current.cityId))cityOptions.push(option(current.cityId,current.cityName||current.cityId));cityOptions.push(...state.cities.map(c=>option(c.id,c.name)));city.replaceChildren(...cityOptions);city.value=current.cityId??'';const districtOptions=[option('',text('不限／未选择','Any / not selected'))];if(current.districtId&&!state.districts.some(d=>d.id===current.districtId))districtOptions.push(option(current.districtId,current.districtName||current.districtId));districtOptions.push(...state.districts.map(d=>option(d.id,d.name)));district.replaceChildren(...districtOptions);district.value=current.districtId??'';district.disabled=!current.cityId;more.hidden=!state.nextCursor;if(state.meta?.updatedAt)status.textContent=text('地域目录更新于 ','Directory updated ')+new Date(state.meta.updatedAt).toLocaleString(en?'en-GB':'zh-CN',{timeZone:'Asia/Shanghai'})+(state.meta.stale?text('；使用上次可用版本','; using last available version'):'');retry.hidden=true;}
 const picker=createRegionPicker({repository,initialValue,onChange,getGeneration,onState:render}),helper=locationSuggest??createLocationSuggest({repository,getGeneration,visitorId});
 const failed=err=>{if(disposed)return;status.textContent=text('暂时无法读取地域。保留已选地区，可重试或继续手动选择。','Regions are unavailable. Your selection is kept; retry or choose manually.');retry.hidden=false;onError(err);};
 const search=()=>picker.searchCities(query.value).catch(failed);query.addEventListener('input',()=>{clearTimeout(debounce);debounce=setTimeout(search,200);});city.addEventListener('change',()=>{const selected=picker.getState().cities.find(c=>c.id===city.value);if(city.value&&!selected)return;picker.selectCity(selected??null).catch(failed);});district.addEventListener('change',()=>{try{picker.selectDistrict(district.value);}catch(err){failed(err);}});more.onclick=()=>picker.searchCities(query.value,{more:true}).catch(failed);retry.onclick=()=>{search();picker.restoreDistricts().catch(failed);};
 locate.onclick=async()=>{if(disposed)return;locate.disabled=true;confirm.hidden=true;status.textContent=text('正在请求位置，仅用于建议城市和行政区…','Requesting location to suggest a city and district…');const result=await helper.suggest();if(disposed)return;locate.disabled=false;suggestion=result.suggestion??null;if(suggestion){confirm.textContent=text('确认使用：','Use suggestion: ')+[suggestion.cityName,suggestion.districtName].filter(Boolean).join(' · ');confirm.hidden=false;status.textContent=text('确认后才更新所选地域。','Confirm to change the selected region.');}else status.textContent=result.reason==='LOCATION_RATE_LIMITED'?text('定位请求较多，请稍后重试，也可以手动选择地区。','Location requests are busy. Retry later or choose a region manually.'):result.reason==='LOCATION_QUOTA_EXCEEDED'?text('本期定位额度已用完，请手动选择地区。','The location allowance is exhausted. Choose a region manually.'):result.reason==='LOCATION_DENIED'?text('位置权限未开启，请手动选择地区。','Location permission was denied. Choose a region manually.'):result.reason==='LOCATION_TIMEOUT'?text('定位超时，请重试或手动选择地区。','Location timed out. Retry or choose a region manually.'):text('未获取到可用建议，请继续手动选择。','No region suggestion is available. Choose manually.');};confirm.onclick=()=>{if(!suggestion)return;const accepted=suggestion;suggestion=null;confirm.hidden=true;picker.applySuggestion(accepted).catch(failed);};
 render(picker.getState());search();picker.restoreDistricts().catch(failed);
 return {getValue:picker.getValue,getState:picker.getState,destroy(){disposed=true;clearTimeout(debounce);picker.destroy();if(!locationSuggest)helper.destroy();root.replaceChildren();}};
}
