export function mountRowSort({root,handleSelector='[data-pet-drag]',getIds,onCommit,onError=()=>{}}){
 let active=null,placeholder=null,startIds=null,keyboard=false,pointerId=null;
 const rows=()=>[...root.querySelectorAll('.pet-entry')],ids=()=>rows().map(row=>row.dataset.id);
 const restore=order=>{for(const id of order){const row=rows().find(r=>r.dataset.id===id);if(row)root.append(row);}};
 function reset(){if(active){if(placeholder)placeholder.replaceWith(active);active.removeAttribute('style');active.classList.remove('is-dragging');active.querySelector(handleSelector)?.setAttribute('aria-grabbed','false');}placeholder=null;active=null;keyboard=false;pointerId=null;}
 async function finish(commit){const changed=ids(),original=startIds,focus=active?.querySelector(handleSelector);reset();if(!commit){restore(original);focus?.focus();return;}try{if(JSON.stringify(changed)!==JSON.stringify(original))await onCommit(changed);focus?.focus();}catch(error){restore(original);onError(error);}}
 const down=event=>{const handle=event.target.closest(handleSelector);if(!handle||active||event.button>0)return;event.preventDefault();active=handle.closest('.pet-entry');startIds=getIds();pointerId=event.pointerId;const box=active.getBoundingClientRect();placeholder=document.createElement('div');placeholder.className='row-sort-placeholder';placeholder.style.height=box.height+'px';active.before(placeholder);root.append(active);active.classList.add('is-dragging');active.style.cssText=`position:fixed;top:${box.top}px;left:${box.left}px;width:${box.width}px;z-index:100;background:var(--paper,#fff);pointer-events:none`;active.__dragOffset=event.clientY-box.top;try{root.setPointerCapture(pointerId);}catch{}handle.setAttribute('aria-grabbed','true');};
 const move=event=>{if(!active||keyboard||event.pointerId!==pointerId)return;event.preventDefault();active.style.top=(event.clientY-active.__dragOffset)+'px';const others=rows().filter(r=>r!==active),before=others.find(r=>event.clientY<r.getBoundingClientRect().top+r.getBoundingClientRect().height/2);if(before)root.insertBefore(placeholder,before);else root.insertBefore(placeholder,active);};
 const up=event=>{if(!active||keyboard||event.pointerId!==pointerId)return;const row=active;placeholder.replaceWith(row);placeholder=null;finish(true);};
 const cancel=()=>{if(active&&!keyboard)finish(false);};
 const key=event=>{const handle=event.target.closest(handleSelector);if(!handle)return;if(!active&&(event.key===' '||event.key==='Spacebar')){event.preventDefault();active=handle.closest('.pet-entry');startIds=getIds();keyboard=true;active.classList.add('is-dragging');handle.setAttribute('aria-grabbed','true');return;}if(!keyboard||handle.closest('.pet-entry')!==active)return;if(event.key==='Escape'){event.preventDefault();finish(false);}else if(event.key==='Enter'||event.key===' '){event.preventDefault();finish(true);}else if(event.key==='ArrowUp'||event.key==='ArrowDown'){event.preventDefault();const list=rows(),index=list.indexOf(active),next=list[index+(event.key==='ArrowUp'?-1:1)];if(next){if(event.key==='ArrowUp')root.insertBefore(active,next);else root.insertBefore(next,active);handle.focus();}}};
 root.addEventListener('pointerdown',down);root.addEventListener('pointermove',move);root.addEventListener('pointerup',up);root.addEventListener('pointercancel',cancel);root.addEventListener('keydown',key);
 return {destroy(){reset();root.removeEventListener('pointerdown',down);root.removeEventListener('pointermove',move);root.removeEventListener('pointerup',up);root.removeEventListener('pointercancel',cancel);root.removeEventListener('keydown',key);}};
}
