'use strict';
const{createHash}=require('node:crypto');const{AiError}=require('./provider.cjs');const{DEFAULT_LIMITS}=require('./quota.cjs');const{parseRecords}=require('./record-parser.cjs');
const hash=s=>createHash('sha256').update(s).digest('hex');const id=s=>typeof s==='string'&&/^[A-Za-z0-9_-]{8,100}$/.test(s);const text=(s,max=1000)=>typeof s==='string'&&s.trim().length>=1&&s.length<=max;
function boundedSnapshot(raw){if(!raw||!Array.isArray(raw.pets)||!Array.isArray(raw.records)||!Array.isArray(raw.reminders))throw new AiError('INVALID_INPUT');const pets=raw.pets.filter(p=>p&&p.deletedAt==null).slice(0,50).map(p=>({...p}));return{...raw,pets,records:raw.records.filter(r=>r&&r.deletedAt==null&&pets.some(p=>p.id===r.petId)),reminders:raw.reminders.filter(r=>r&&r.deletedAt==null&&pets.some(p=>p.id===r.petId))};}
async function handleAiRequest(request,{principal,sourceIp,readSnapshot,quotaStore,model,clock=()=>new Date(),limits=DEFAULT_LIMITS}={}){
 try{if(request?.version!==1||!['ai.quota','ai.records.parse','ai.recaps.generate','ai.assistant.ask'].includes(request.action)||!id(request.requestId))throw new AiError('INVALID_INPUT');if(Object.hasOwn(request,'authToken')&&!principal)throw new AiError('UNAUTHENTICATED');if(!sourceIp||typeof sourceIp!=='string')throw new AiError('UNAUTHENTICATED');if(principal&&(!principal.userId||principal.emailVerified!==true||principal.isAnonymous!==false))throw new AiError('UNAUTHENTICATED');if(!principal&&!id(request.visitorId))throw new AiError('INVALID_INPUT');const payload=request.payload??{};if(payload.ownerId||payload.userId||Buffer.byteLength(JSON.stringify(payload))>96*1024)throw new AiError('INVALID_INPUT');
  const date=clock(),day=new Date(date.getTime()+8*3600000).toISOString().slice(0,10),month=day.slice(0,7);const input={actorKey:principal?'auth:'+principal.userId:'guest:'+request.visitorId,ipKey:hash(sourceIp),requestId:request.requestId,day,month,limits};
  if(!quotaStore)throw new AiError('UNAVAILABLE');if(request.action==='ai.quota')return{ok:true,data:await quotaStore.read(input)};
  if(request.action==='ai.records.parse'&&!text(payload.text)||request.action==='ai.assistant.ask'&&!text(payload.question))throw new AiError('INVALID_INPUT');
  const raw=principal?await readSnapshot(principal):payload.context,snapshot=boundedSnapshot(raw?.snapshot??raw);const pet=snapshot.pets.find(p=>p.id===payload.petId);if(!pet){if(request.action==='ai.assistant.ask'){const{HELP}=require('./assistant.cjs');const chosen=/备份|导出|恢复|backup|export|restore/i.test(payload.question)?HELP.find(s=>s.id==='help-backup'):HELP.find(s=>s.id==='help-record');return{ok:true,data:{answer:payload.uiLocale==='en'?'You can create a pet profile, then add a record from Health. Use the workspace menu to export or import a full backup. No pet records are available in this workspace.':chosen.text+' 当前空间还没有宠物记录，你可以先建立宠物档案。',sources:[{kind:'help',id:chosen.id,title:chosen.title,label:chosen.title,text:chosen.text}],quota:await quotaStore.read(input)}};}throw new AiError('INVALID_INPUT');}
  if(request.action==='ai.recaps.generate'&&(!/^\d{4}-\d{2}-\d{2}$/.test(payload.from??'')||!/^\d{4}-\d{2}-\d{2}$/.test(payload.to??'')||payload.from>payload.to))throw new AiError('INVALID_INPUT');
  if(request.action==='ai.recaps.generate'&&!snapshot.records.some(r=>r.petId===pet.id&&r.occurredDate>=payload.from&&r.occurredDate<=payload.to))return{ok:true,data:{...await require('./recap.cjs').generateRecap({snapshot,petId:pet.id,from:payload.from,to:payload.to,uiLocale:payload.uiLocale},model),quota:await quotaStore.read(input)}};
  if(request.action==='ai.assistant.ask'&&(payload.history&&!Array.isArray(payload.history)||payload.history?.length>8))throw new AiError('INVALID_INPUT');
  const quota=await quotaStore.reserve(input);if(!quota.accepted)throw new AiError(quota.reason);
  let data;if(request.action==='ai.records.parse')data=await parseRecords({text:payload.text,pets:snapshot.pets,activePetId:pet.id,today:day,uiLocale:payload.uiLocale},model);else if(request.action==='ai.recaps.generate')data=await require('./recap.cjs').generateRecap({snapshot,petId:pet.id,from:payload.from,to:payload.to,uiLocale:payload.uiLocale,now:date.toISOString()},model);else data=await require('./assistant.cjs').askAssistant({snapshot,petId:pet.id,question:payload.question,history:payload.history,uiLocale:payload.uiLocale,today:day},model);
  return{ok:true,data:{...data,quota:{remaining:quota.remaining}}};
 }catch(error){const code=error instanceof AiError?error.code:'UNAVAILABLE';return{ok:false,error:{code,messageKey:'errors.ai.'+code.toLowerCase()}};}
}
module.exports={handleAiRequest,boundedSnapshot};
