import test from'node:test';import assert from'node:assert/strict';import{createRequire}from'node:module';
const require=createRequire(import.meta.url);const enabled=process.env.PAW_REAL_TEXT_AI==='1';
test('real free text model parses fixed synthetic diary',{skip:!enabled},async()=>{
 assert.ok(process.env.SILICONFLOW_API_KEY,'SILICONFLOW_API_KEY must be configured');assert.equal(process.env.PAW_FREE_MODEL_CONFIRMED,'1','Current 0-price model must be confirmed');
 const{createTextModel}=require('../../backend/ai/provider.cjs');const{parseRecords}=require('../../backend/ai/record-parser.cjs');const model=createTextModel({apiKey:process.env.SILICONFLOW_API_KEY,model:'Qwen/Qwen2.5-7B-Instruct'});const started=Date.now();const out=await parseRecords({text:'昨天称重4.6公斤，今天驱虫了',pets:[{id:'synthetic-pet',name:'验收宠物',deletedAt:null}],today:'2026-10-07',uiLocale:'zh-CN'},model);assert.equal(out.drafts.length,2);assert.ok(out.drafts.some(d=>d.type==='weight'&&d.value===4.6&&d.occurredDate==='2026-10-06'));assert.ok(out.drafts.some(d=>d.type==='deworm'&&d.occurredDate==='2026-10-07'));console.log(JSON.stringify({smoke:'parse',model:'Qwen/Qwen2.5-7B-Instruct',elapsedMs:Date.now()-started,passed:true}));
});
const fixture={version:3,pets:[{id:'synthetic-pet',name:'验收宠物',deletedAt:null}],records:[{id:'synthetic-record-1',petId:'synthetic-pet',type:'weight',title:'体重记录',value:4.6,unit:'kg',note:'',occurredDate:'2026-10-06',createdAt:'2026-10-06T00:00:00Z',updatedAt:'2026-10-06T00:00:00Z',deletedAt:null},{id:'synthetic-record-2',petId:'synthetic-pet',type:'deworm',title:'驱虫',value:null,unit:null,note:'',occurredDate:'2026-10-07',createdAt:'2026-10-07T00:00:00Z',updatedAt:'2026-10-07T00:00:00Z',deletedAt:null}],reminders:[]};
function realModel(){assert.ok(process.env.SILICONFLOW_API_KEY);assert.equal(process.env.PAW_FREE_MODEL_CONFIRMED,'1');const model=require('../../backend/ai/provider.cjs').createTextModel({apiKey:process.env.SILICONFLOW_API_KEY,model:'Qwen/Qwen2.5-7B-Instruct'});return{complete:async options=>{const out=await model.complete(options);console.log(JSON.stringify({provider:'siliconflow',model:'Qwen/Qwen2.5-7B-Instruct',usage:out.usage}));return out;}};}
test('real free model generates a cited synthetic recap',{skip:!enabled},async()=>{const start=Date.now();const{generateRecap}=require('../../backend/ai/recap.cjs');const out=await generateRecap({snapshot:fixture,petId:'synthetic-pet',from:'2026-10-01',to:'2026-10-07'},realModel());assert.equal(out.recap.facts.recordCount,2);assert.ok(out.recap.storySources.length);assert.ok(out.recap.storySources.every(id=>fixture.records.some(r=>r.id===id)));console.log(JSON.stringify({smoke:'recap',model:'Qwen/Qwen2.5-7B-Instruct',elapsedMs:Date.now()-start,passed:true}));});
test('real free model answers synthetic current pet question with citations',{skip:!enabled},async()=>{const start=Date.now();const{askAssistant}=require('../../backend/ai/assistant.cjs');const out=await askAssistant({snapshot:fixture,petId:'synthetic-pet',question:'这只宠物最近的驱虫记录是什么？',today:'2026-10-07'},realModel());assert.ok(out.answer);assert.ok(out.sources.some(s=>s.id==='synthetic-record-2'));console.log(JSON.stringify({smoke:'assistant',model:'Qwen/Qwen2.5-7B-Instruct',elapsedMs:Date.now()-start,passed:true}));});
