'use strict';
const{randomUUID}=require('node:crypto');const{hash,hashOwner}=require('./store.cjs');const{handleProfiles,requirePrincipal}=require('./profiles.cjs');
const fail=code=>{throw Object.assign(new Error(code),{code});};
const READ_ACTIONS=new Set(['profiles.discover','profiles.getPublic','profiles.identity','community.list','community.get','comments.list','community.media.read','regions.meta','regions.search','regions.children','regions.suggest']);
const OWN_READS=new Set(['profiles.getOwn','auth.getOwn','community.hidden.list']);
const WRITE_ACTIONS=new Set(['profiles.saveOwn','community.save','community.delete','comments.save','comments.delete','likes.set','community.report','community.hide','community.media.prepare','community.media.confirm','community.media.remove']);
const stable=value=>Array.isArray(value)?value.map(stable):value&&typeof value==='object'?Object.fromEntries(Object.keys(value).sort().map(k=>[k,stable(value[k])])):value;
function receiptKey(ownerId,idempotencyKey){return hash(ownerId+'\0'+idempotencyKey);}
function receiptIdentity(request,deps){const ownerId=requirePrincipal(deps.principal),key=request.idempotencyKey;if(typeof key!=='string'||!key||key.length>128||/[\x00-\x1f\x7f]/.test(key))fail('INVALID_INPUT');return{ownerId,id:receiptKey(ownerId,key),signature:hash(JSON.stringify(stable({action:request.action,payload:request.payload,expectedRevision:request.expectedRevision??null})))};}
function readCommitted(receipt,identity){if(!receipt)return{found:false};if(receipt.ownerId!==identity.ownerId||receipt.signature!==identity.signature)fail('INVALID_INPUT');return{found:true,result:structuredClone(receipt.result)};}
async function readReceipt(request,deps){const identity=receiptIdentity(request,deps);return readCommitted(await deps.store.get('receipts',identity.id),identity);}
async function withReceipt(request,deps,callback){const identity=receiptIdentity(request,deps);return deps.store.transaction(async tx=>{const previous=readCommitted(await tx.get('receipts',identity.id),identity);if(previous.found)return previous.result;const result=await callback(tx);await tx.put('receipts',identity.id,{ownerId:identity.ownerId,signature:identity.signature,result:structuredClone(result),createdAt:new Date(deps.clock()).toISOString()});return result;});}
function validateRequest(request){if(!request||typeof request!=='object'||Array.isArray(request)||Object.keys(request).some(k=>!['version','action','payload','idempotencyKey','expectedRevision'].includes(k))||request.version!==1||typeof request.action!=='string'||(!READ_ACTIONS.has(request.action)&&!OWN_READS.has(request.action)&&!WRITE_ACTIONS.has(request.action)))fail('INVALID_INPUT');if(!request.payload||typeof request.payload!=='object'||Array.isArray(request.payload))fail('INVALID_INPUT');const size=Buffer.byteLength(JSON.stringify(request));if(size>(request.action==='community.media.confirm'?2*1024*1024:64*1024))fail('INVALID_INPUT');if(request.expectedRevision!==undefined&&(!Number.isInteger(request.expectedRevision)||request.expectedRevision<0))fail('INVALID_INPUT');}
async function handleCommunity(request,{principal=null,hasCredential=false,store,storage,regions,getOwnAccountInfo,clock=()=>new Date(),idFactory=randomUUID,handlers={},media,sourceIp,ipHash}={}){
 try{if(hasCredential&&!principal)fail('UNAUTHENTICATED');if(principal)requirePrincipal(principal);validateRequest(request);if(!store)fail('UNAVAILABLE');const isWrite=WRITE_ACTIONS.has(request.action);if(isWrite||OWN_READS.has(request.action))requirePrincipal(principal);if(isWrite&&(typeof request.idempotencyKey!=='string'||!request.idempotencyKey||request.idempotencyKey.length>128||/[\x00-\x1f\x7f]/.test(request.idempotencyKey)))fail('INVALID_INPUT');
 const deps={principal,hasCredential,store,storage,regions,getOwnAccountInfo,clock,idFactory,request,idempotencyKey:request.idempotencyKey,media,sourceIp,ipHash};deps.mutate=callback=>withReceipt(request,deps,callback);deps.readReceipt=()=>readReceipt(request,deps);
 let data;if(request.action.startsWith('profiles.'))data=await handleProfiles(request.action.slice(9),request.payload,deps);
 else if(request.action==='auth.getOwn'){if(Object.keys(request.payload).length||typeof getOwnAccountInfo!=='function')fail(Object.keys(request.payload).length?'INVALID_INPUT':'UNAVAILABLE');const account=await getOwnAccountInfo(principal);if(typeof account?.email!=='string'||!account.email.trim())fail('UNAVAILABLE');data={email:account.email};}
 else{const prefix=request.action.startsWith('community.media.')?'community.media':request.action.split('.')[0],handler=handlers[prefix];if(typeof handler!=='function')fail('UNAVAILABLE');data=await handler(request,deps);}
 return{ok:true,data};
 }catch(error){const known=new Set(['INVALID_INPUT','UNAUTHENTICATED','FORBIDDEN','NOT_FOUND','CONFLICT','UNAVAILABLE','QUOTA_EXCEEDED','QUOTA_EXHAUSTED','REGION_UNAVAILABLE','REGION_NOT_FOUND','LOCATION_QUOTA_EXCEEDED','LOCATION_RATE_LIMITED','LOCATION_UNRECOGNIZED','PROFILE_REQUIRED','TIMEOUT']);const code=known.has(error?.code)?error.code:'UNAVAILABLE';return{ok:false,error:{code,messageKey:'errors.community.'+code.toLowerCase()}};}
}
module.exports={handleCommunity,withReceipt,readReceipt,receiptKey,READ_ACTIONS,WRITE_ACTIONS,OWN_READS,hashOwner};
