'use strict';
const{onlyFields,communityId,validateCommentInput,publicComment}=require('../../src/domain/community.js');const{publicIdentity}=require('../../src/domain/public-profile.js');const{hashOwner,livePost}=require('./store.cjs');const{requirePrincipal}=require('./profiles.cjs');const{requireProfile,relationId,isHidden}=require('./posts.cjs');
const fail=code=>{throw Object.assign(new Error(code),{code});};
async function requireLiveParent(tx,id,ownerId=null){const post=await tx.get('posts',id);if(!livePost(post)||await isHidden(tx,id,ownerId))fail('NOT_FOUND');return post;}
async function commentView(tx,comment,principal){if(!comment||comment.deletedAt!==null)fail('NOT_FOUND');const profile=await tx.findProfileByAuthorId(comment.authorId);if(!profile?.nickname||profile.authorId!==comment.authorId)fail('NOT_FOUND');return{comment:publicComment(comment),identity:publicIdentity(profile),isOwn:!!principal&&comment.ownerId===hashOwner(principal.userId)};}
async function listComments(payload,deps){onlyFields(payload,['postId','cursor','limit']);const postId=communityId(payload.postId),ownerId=deps.principal?hashOwner(deps.principal.userId):null;await deps.store.transaction(tx=>requireLiveParent(tx,postId,ownerId));const result=await deps.store.listComments({postId,...(payload.cursor!==undefined?{cursor:payload.cursor}:{}),...(payload.limit!==undefined?{limit:payload.limit}:{})}),items=[];for(const row of result.items){try{const view=await deps.store.transaction(async tx=>{await requireLiveParent(tx,postId,ownerId);return commentView(tx,await tx.get('comments',row.id),deps.principal);});items.push(view);}catch(error){if(error.code!=='NOT_FOUND')throw error;}}await deps.store.transaction(tx=>requireLiveParent(tx,postId,ownerId));return{items,nextCursor:result.nextCursor};}
async function saveComment(payload,deps){const input=validateCommentInput(payload),ownerId=requirePrincipal(deps.principal);return deps.mutate(async tx=>{const post=await requireLiveParent(tx,input.postId,ownerId),profile=await requireProfile(tx,ownerId),id=communityId(deps.idFactory());if(await tx.get('comments',id))fail('CONFLICT');const comment={...input,id,ownerId,authorId:profile.authorId,createdAt:new Date(deps.clock()).toISOString(),deletedAt:null};await tx.put('comments',id,comment);post.commentCount=(post.commentCount??0)+1;await tx.put('posts',post.id,post);return commentView(tx,comment,deps.principal);});}
async function deleteComment(payload,deps){onlyFields(payload,['id']);const id=communityId(payload.id),ownerId=requirePrincipal(deps.principal);return deps.mutate(async tx=>{const comment=await tx.get('comments',id);if(!comment||comment.deletedAt!==null)fail('NOT_FOUND');if(comment.ownerId!==ownerId)fail('FORBIDDEN');const post=await tx.get('posts',comment.postId);if(!post)fail('NOT_FOUND');comment.deletedAt=new Date(deps.clock()).toISOString();await tx.put('comments',id,comment);post.commentCount=Math.max(0,(post.commentCount??0)-1);await tx.put('posts',post.id,post);return{id,deleted:true};});}
async function setLike(payload,deps){onlyFields(payload,['postId','liked']);const postId=communityId(payload.postId),ownerId=requirePrincipal(deps.principal);if(typeof payload.liked!=='boolean')fail('INVALID_INPUT');return deps.mutate(async tx=>{const post=await requireLiveParent(tx,postId,ownerId),id=relationId(ownerId,postId),previous=await tx.get('likes',id);if(previous&&(previous.ownerId!==ownerId||previous.postId!==postId))fail('FORBIDDEN');const wasLiked=previous?.liked===true;if(wasLiked!==payload.liked)post.likeCount=Math.max(0,(post.likeCount??0)+(payload.liked?1:-1));await tx.put('likes',id,{ownerId,postId,liked:payload.liked});await tx.put('posts',postId,post);return{postId,liked:payload.liked,likeCount:post.likeCount};});}
async function handleInteractions(action,payload,deps){const handler={'comments.list':listComments,'comments.save':saveComment,'comments.delete':deleteComment,'likes.set':setLike}[action];if(!handler)fail('INVALID_INPUT');return handler(payload,deps);}
module.exports={handleInteractions,requireLiveParent,commentView};
