'use strict';
const{validatePostInput,validateListInput,publicPost,communityId,onlyFields}=require('../../src/domain/community.js');const{publicIdentity}=require('../../src/domain/public-profile.js');const{requirePrincipal}=require('./profiles.cjs');const{hashOwner,hash,livePost}=require('./store.cjs');const{bindCommunityAsset,unbindCommunityAsset}=require('./media.cjs');
const fail=code=>{throw Object.assign(new Error(code),{code});};
const relationId=(ownerId,postId)=>hash(ownerId+'\0'+postId);
async function requireProfile(tx,ownerId){const profile=await tx.getOwnProfile(ownerId);if(!profile?.nickname||!profile.authorId)fail('PROFILE_REQUIRED');return profile;}
async function isHidden(tx,postId,ownerId){if(!ownerId)return false;const hidden=await tx.get('hidden',relationId(ownerId,postId));return !!hidden&&hidden.ownerId===ownerId&&hidden.postId===postId&&hidden.hidden!==false;}
async function postView(tx,post,principal){if(!livePost(post))fail('NOT_FOUND');const ownerId=principal?hashOwner(principal.userId):null;if(await isHidden(tx,post.id,ownerId))fail('NOT_FOUND');const profile=await tx.findProfileByAuthorId(post.authorId);if(!profile?.nickname||profile.authorId!==post.authorId)fail('NOT_FOUND');const like=ownerId?await tx.get('likes',relationId(ownerId,post.id)):null;return{post:publicPost(post),identity:publicIdentity(profile),liked:like?.ownerId===ownerId&&like?.postId===post.id&&like?.liked===true,isOwn:post.ownerId===ownerId};}
async function normalizePost(input,regions){const result=validatePostInput(input);if(!result.cityId)return{...result,cityName:null,districtName:null};const normalize=regions?.normalize??regions?.normalizeRegion;if(typeof normalize!=='function')fail('REGION_UNAVAILABLE');const region=await normalize.call(regions,{cityId:result.cityId,districtId:result.districtId});if(region?.cityId!==result.cityId||(region?.districtId??null)!==result.districtId)fail('INVALID_INPUT');return{...result,cityName:typeof region.cityName==='string'?region.cityName:null,districtName:typeof region.districtName==='string'?region.districtName:null};}
async function get(payload,deps){onlyFields(payload,['id']);const id=communityId(payload.id);return deps.store.transaction(async tx=>postView(tx,await tx.get('posts',id),deps.principal));}
async function list(payload,deps){const filters=validateListInput(payload),page=await deps.store.listPosts(filters),items=[];for(const post of page.items){try{const view=await deps.store.transaction(async tx=>postView(tx,await tx.get('posts',post.id),deps.principal));items.push(view);}catch(error){if(error.code!=='NOT_FOUND')throw error;}}return{items,nextCursor:page.nextCursor};}
async function save(payload,deps){const ownerId=requirePrincipal(deps.principal),receipt=await deps.readReceipt();if(receipt.found)return receipt.result;const input=await normalizePost(payload,deps.regions);return deps.mutate(async tx=>{const profile=await requireProfile(tx,ownerId),previous=input.id?await tx.get('posts',input.id):null;if(input.id){if(!livePost(previous))fail('NOT_FOUND');if(previous.ownerId!==ownerId)fail('FORBIDDEN');if(deps.request.expectedRevision===undefined)fail('INVALID_INPUT');if(deps.request.expectedRevision!==previous.revision)fail('CONFLICT');}else if(deps.request.expectedRevision!==undefined&&deps.request.expectedRevision!==0)fail('CONFLICT');
 const id=input.id??communityId(deps.idFactory());if(!previous&&await tx.get('posts',id))fail('CONFLICT');const now=new Date(deps.clock()).toISOString();if((previous?.imageAssetId??null)!==input.imageAssetId){if(previous?.imageAssetId)await unbindCommunityAsset(tx,{assetId:previous.imageAssetId,targetKind:'post',targetId:id});if(input.imageAssetId)await bindCommunityAsset(tx,{assetId:input.imageAssetId,ownerId,targetKind:'post',targetId:id,now:new Date(deps.clock()).getTime()});}
 const post={...input,id,ownerId,authorId:profile.authorId,likeCount:previous?.likeCount??0,commentCount:previous?.commentCount??0,revision:(previous?.revision??0)+1,createdAt:previous?.createdAt??now,updatedAt:now,deletedAt:null,moderationStatus:'visible'};await tx.put('posts',id,post);return postView(tx,post,deps.principal);});}
async function remove(payload,deps){onlyFields(payload,['id']);const id=communityId(payload.id),ownerId=requirePrincipal(deps.principal);if(deps.request.expectedRevision===undefined)fail('INVALID_INPUT');return deps.mutate(async tx=>{const post=await tx.get('posts',id);if(!livePost(post))fail('NOT_FOUND');if(post.ownerId!==ownerId)fail('FORBIDDEN');if(deps.request.expectedRevision!==post.revision)fail('CONFLICT');if(post.imageAssetId)await unbindCommunityAsset(tx,{assetId:post.imageAssetId,targetKind:'post',targetId:id});post.deletedAt=new Date(deps.clock()).toISOString();post.updatedAt=post.deletedAt;post.revision++;await tx.put('posts',id,post);return{id,deleted:true};});}
async function handlePosts(action,payload,deps){const handler={'community.list':list,'community.get':get,'community.save':save,'community.delete':remove}[action];if(!handler)fail('INVALID_INPUT');return handler(payload,deps);}
module.exports={handlePosts,postView,requireProfile,relationId,isHidden,normalizePost};
