'use strict';
const{validateProfileInput,publicIdentity,discoverableProfile,ownProfile,PROFILE_PURPOSES,PROFILE_PET_TYPES}=require('../../src/domain/public-profile.js');
const{hashOwner,livePost}=require('./store.cjs');
const fail=code=>{throw Object.assign(new Error(code),{code});};
function allowed(input,keys){if(!input||typeof input!=='object'||Array.isArray(input)||Object.keys(input).some(k=>!keys.includes(k)))fail('INVALID_INPUT');}
const id=value=>{if(typeof value!=='string'||!/^[a-zA-Z0-9_-]{1,128}$/.test(value))fail('INVALID_INPUT');return value;};
function requirePrincipal(principal){if(!principal?.userId||principal.emailVerified!==true||principal.isAnonymous!==false)fail('UNAUTHENTICATED');return hashOwner(principal.userId);}
async function normalizeProfile(input,regions){const profile=validateProfileInput(input);if(!profile.cityId)return{...profile,cityName:null,districtName:null};const normalize=regions?.normalize??regions?.normalizeRegion;if(typeof normalize!=='function')fail('REGION_UNAVAILABLE');const region=await normalize.call(regions,{cityId:profile.cityId,districtId:profile.districtId});if(!region||region.cityId!==profile.cityId||((region.districtId??null)!==profile.districtId))fail('INVALID_INPUT');return{...profile,cityName:typeof region.cityName==='string'?region.cityName:null,districtName:typeof region.districtName==='string'?region.districtName:null};}
async function getOwn(payload,{principal,store}){allowed(payload,[]);return ownProfile(await store.getOwnProfile(requirePrincipal(principal)));}
async function saveOwn(payload,deps){const ownerId=requirePrincipal(deps.principal);const committed=await deps.readReceipt();if(committed.found)return committed.result;const profile=await normalizeProfile(payload,deps.regions);return deps.mutate(async tx=>{const previous=await tx.getOwnProfile(ownerId);const revision=previous?.revision??0;if(previous&&deps.request.expectedRevision===undefined)fail('INVALID_INPUT');if(deps.request.expectedRevision!==undefined&&deps.request.expectedRevision!==revision)fail('CONFLICT');const now=new Date(deps.clock()).toISOString();let authorId=previous?.authorId;
 if(!authorId){authorId=id(deps.idFactory());if(await tx.get('profiles',authorId))fail('CONFLICT');}
 if(previous?.avatarAssetId!==profile.avatarAssetId){if(previous?.avatarAssetId||profile.avatarAssetId){const media=deps.media??require('./media.cjs');if(previous?.avatarAssetId)await media.unbindCommunityAsset(tx,{assetId:previous.avatarAssetId,targetKind:'profile',targetId:authorId,now:new Date(deps.clock()).getTime()});if(profile.avatarAssetId)await media.bindCommunityAsset(tx,{assetId:profile.avatarAssetId,ownerId,targetKind:'profile',targetId:authorId,now:new Date(deps.clock()).getTime()});}}
 const next={...profile,ownerId,authorId,revision:revision+1,createdAt:previous?.createdAt??now,updatedAt:now};await tx.put('profiles',authorId,next);await tx.put('profiles','owner:'+ownerId,{kind:'owner-index',authorId});return ownProfile(next);});}
function discoverFilters(payload){allowed(payload,['scope','cityId','districtId','petTypes','purposes','cursor','limit']);const scope=payload.scope??'all';if(!['all','city'].includes(scope))fail('INVALID_INPUT');const result={scope,petTypes:payload.petTypes??[],purposes:payload.purposes??[],...(payload.cursor!==undefined?{cursor:payload.cursor}:{}),...(payload.limit!==undefined?{limit:payload.limit}:{})};for(const[key,values]of[['petTypes',PROFILE_PET_TYPES],['purposes',PROFILE_PURPOSES]])if(!Array.isArray(result[key])||result[key].length>values.length||result[key].some(v=>!values.includes(v)))fail('INVALID_INPUT');if(scope==='city'){result.cityId=id(payload.cityId);if(payload.districtId)result.districtId=id(payload.districtId);}return result;}
async function discover(payload,{store}){const filters=discoverFilters(payload),result=await store.discover(filters);return{items:result.items.filter(p=>p.discoverable===true).map(discoverableProfile),nextCursor:result.nextCursor};}
async function getPublic(payload,{store}){allowed(payload,['authorId']);const profile=await store.findProfileByAuthorId(id(payload.authorId));if(!profile?.discoverable)fail('NOT_FOUND');return discoverableProfile(profile);}
async function identity(payload,{store}){allowed(payload,['authorId','reference']);const authorId=id(payload.authorId),reference=payload.reference;allowed(reference,['kind','id']);id(reference.id);if(!['profile','post','comment'].includes(reference.kind))fail('INVALID_INPUT');const profile=await store.findProfileByAuthorId(authorId);if(!profile||profile.authorId!==authorId)fail('NOT_FOUND');
 if(reference.kind==='profile'){if(reference.id!==authorId||!profile.discoverable)fail('NOT_FOUND');}
 else if(reference.kind==='post'){const post=await store.get('posts',reference.id);if(!livePost(post)||post.authorId!==authorId)fail('NOT_FOUND');}
 else{const comment=await store.get('comments',reference.id);if(!comment||comment.deletedAt!==null||comment.authorId!==authorId||!livePost(await store.get('posts',comment.postId)))fail('NOT_FOUND');}
 return publicIdentity(profile);
}
async function handleProfiles(action,payload,deps){const handler={getOwn,saveOwn,discover,getPublic,identity}[action];if(!handler)fail('INVALID_INPUT');return handler(payload,deps);}
module.exports={handleProfiles,getOwn,saveOwn,discover,getPublic,identity,requirePrincipal,normalizeProfile,discoverFilters};
